### ISSUE TITLE
Any plan on adding more block services?

### ISSUE THREAD

**Issue by imadockerman** [AdguardTeam/AdGuardHome#1128]
I love Adguard Home and the simplistic service blocker is amazing. However, as of right now, there are very many crucial services missing and I was wondering whether there are any chance of adding more services. Here are some suggestions:

1. Microsoft
2. Amazon
3. Reddit
4. Google
5. CloudFlare

**Comment by Eyeborgs** [comment]
You also need to add Yandex and Origin to the services block

**Comment by szolin** [comment]
Actually, you can add the services you want yourself and open a PR so that we can include your patch in AGH release.
1. Create a fork of AGH
2. Add more services here:
https://github.com/AdguardTeam/AdGuardHome/blob/e04ffde105f88b6665d90ae8d9fbf0c2e84dedbf/home/blocked_services.go#L22
3. Open PR

**Comment by ArchiveBase** [comment]
I think we should not add Microsoft and Google because it's the source for download, get latest updates as soon as released, important details related world top softwares that run on most people's devices. If adguard home server owners block access due own desire next clients may get them through thirdparty insecure websites or services then it's not suitable for lead to such risk however it still possible block manually even no such option.

It's ok block Amazon, CloudFlare, Reddit, Yandex, Origin. no problem at all.

**Comment by AnthonyBe** [comment]
I feel the distinction there is whether you are blocking a 'service' versus blocking a 'company'.
The former seems to be what should (in my mind) be the feature in AGH. The latter is not, it's like a sledgehammer vs a scalpel :)

**Comment by ArchiveBase** [comment]
Done. amazon, cloudflare, ebay, reddit, origin added. 

_when we blocked ex: reddit, origin then client softwares too become unusable however even prevent access to microsoft, google, yandex but clients still able use their web browsers, operating systems etc. if you think that's not risk then open PR or adguard may take care it own way😉_
