### ISSUE TITLE
Status: SERVFAIL

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/AdGuardHome#1136]
A large number of Status occurred in the above log: SERVFAIL
![`7I5E}6F)W%G7_SO~~QYT`H](https://user-images.githubusercontent.com/17548936/67856855-74f9e380-fb50-11e9-9fab-4d80e4774155.png)

**Comment by thb007** [comment]
@ameshkov

**Comment by phixion** [comment]
[servfail means](https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml) your **upstream** dns cant complete the request. This can be misconfiguration or simply cannot resolve the hostname. the issue is most likely with the upstream dns and not with agh.

Its also always helpful to use the templates when creating issues and not use screenshots of text, just copy the damn text. In other words provide more information such as debuglog when reproducing the issue and configfiles.

**Comment by ameshkov** [comment]
These `in-addr.arpa` requests are most likely sent by AGH -- it periodically tries to resolve clients' IP addresses hostnames. You can safely ignore these errors.
