### ISSUE TITLE
Provide a tool/script for converting browser blockers' lists to DNS-level compatible lists

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#1160]
https://github.com/AdguardTeam/AdGuardHome/issues/1026#issuecomment-551078519

Here's what we need to do:

1. [x] A python script (module?) that transforms an adblock-style syntax list to the list that AdGuard Home can understand.
2. [x] Update the [wiki article](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists) and mention this new script

Here is how this script should analyze a rule.

1. Parse the rule, split it into the "pattern" and the "modifiers"
2. If it is a cosmetic rule, discard it right away
3. Remove the modifiers we ignore:
    * `third-party`
    * `3p`
    * `all`
    * `document`
    * `empty`
4. Check the modifiers that are left. If there are any unsupported modifier left, discard the rule.
5. Currently, we support the following modifiers: `important`, `badfilter`

**Comment by ArchiveBase** [comment]
Can we integrate this to GH 'filters' area? because browser blockers' lists too regularly update by maintainers. If we provide tool/script then user need do it manually +we dont need bother or conflict with other people.

- New filter subscription(current) 
- Create local filter (https://github.com/AdguardTeam/AdGuardHome/issues/817#issuecomment-534275463)
- New browser blockers subscription (new)

1. Add filter > browser blockers' list(url) then click next
2. AdGuard Home does the (tool/script) task
3. Wizard last step preview rules window similar https://github.com/AdguardTeam/AdGuardHome/issues/817#issuecomment-547019637
(contain all discard, ignore rules with specific mark to identify or move that all invalid rules to end of valid contents) then able edit as necessary
4. Save (notify user invalid rules will be discarded)

Now those block lists too able get update same as other filters and adguard home perform additional convert task in background(silent)

**Comment by ameshkov** [comment]
Tbh, I don't want people to blindly add browser blocker's lists to AdGuard Home, that's why I want to have a separate tool.

It is targeted at filter lists maintainers who wish to provide hosts blocklists that reuse parts of traditional filter lists.

**Comment by ArchiveBase** [comment]
Got it ^_^

**Comment by alexsannikov** [comment]
It also would be useful to have a script which converts hosts-based file into DNS-level compatible list.
For myself I am using now scary mix of shell scripting and Python.
This script must be able:
1. to remove any unsupported and non-RFC compatible lines;
2. replace "0.0.0.0" or "127.0.0.1" or similar to "||";
3. if top-level domain (TLD) already presented, delete any lines which contains this TLD as a sub-string;
4. check duplicates among several files and delete any sub-domains if TLD is presented in another file
I have all but 4 (except that I re-invented wheel by the very ugly way) :)

**Comment by YBS-PC** [comment]
maybe this script https://github.com/mmotti/adguard-home-filters/tree/master/generator

**Comment by NetE1** [comment]
> Tbh, I don't want people to blindly add browser blocker's lists to AdGuard Home, that's why I want to have a separate tool.
> 
> It is targeted at filter lists maintainers who wish to provide hosts blocklists that reuse parts of traditional filter lists.

I also interest to see this come with Adguard Home. In this cause, you guys can place a check box option "Add DNS-level incompatible list" to new filter subscription window and it's possible to display additional acknowledge notice when enable it

**Comment by ameshkov** [comment]
Here it is:
https://github.com/AdguardTeam/HostlistCompiler
