### ISSUE TITLE
Multiple DHCP servers

### ISSUE THREAD

**Issue by Onepamopa** [AdguardTeam/AdGuardHome#1181]
It'd be nice if we could run multiple DHCP server instances (for various interfaces/vlans).

Also, please check my other DHCP issue: https://github.com/AdguardTeam/AdGuardHome/issues/1179

**Comment by Onepamopa** [comment]
Is there a plan to add this anytime soon?

**Comment by KamistixX** [comment]
VLANs support would be a good addition ideed, since with IOT, VLAN segmentation has become an important use case for home networking as well.

**Comment by RainmakerRaw** [comment]
I've just realised I can't fully deploy AdGuard Home for this very reason, so consider this +1. 

I run an x86 router with Arch Linux. I have a quad port NIC with WAN, LAN1 and LAN2. The WAN is self-explanatory, being my cable modem plugged into port 1. For LAN1 I have a switch plugged into port 2 and this is my 'trusted LAN', with my PCs and printer and so on. On port 3 I have another switch for LAN2 devices, where I keep CCTV, servers and such. At the moment, using dhcpd, I simply have two separate entries in the single dhcpd.conf file - 

```
subnet 192.168.1.0/24
options, hosts, etc

subnet 192.168.2.0/24
options, hosts, etc
```

And that works fine, because netctl (that handles my interfaces) knows that port 1 is for WAN, port 2 is 192.168.1.0/24 and port 3 is 192.168.2.0/24 and everything works accordingly. On AdGuard Home however, the webUI only has provision for a single server on a single chosen interface. I was hoping I could just manually edit AdGuardHome.yaml and add the second subnet as you would in dhcpd.conf - but it seems not. Please consider adding this so I can run AdGuard Home for DHCP as well as DNS on my router. It would simplify things so much!

**Comment by timcappalli** [comment]
Multiple DHCP scope support would be amazing. I just want DHCP forward from my core switch to AGH.

**Comment by timkgh** [comment]
DHCP for VLANs would be great, to fully replace dnsmasq on a router.

**Comment by tsvsj** [comment]
I'm kind of confused about the title of this issue, the content of the first entry and how it evolved to multiple subnets... :zany_face:

However, supporting multiple subnets would be a great addition. I'm currently planning on replacing my old ISC-DHCP-Server on Raspberry PI to AdGuard Home, but I need to support for multiple subnets. 

Additionally, it would be great to have https://github.com/bakito/adguardhome-sync natively integrated. I have two instances of AdGuard Home and planning to have my DHCP server high available as well. Based on how the BOOTP/DHCP protocol behave, there shouldn't be a problem, but to have the leases or at least the configuration synchronized, would be a very great addition.

Thanks for your work guys! :thumbsup:

**Comment by ainar-g** [comment]
I'm going to merge this issue into #3539.
