### ISSUE TITLE
[Feature request] Can hosts files also support blocking mode?

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1337]
I noticed only standard AdGuard filter rules can used in blocking mode, but most third-party filter use hosts files syntax, Is it possible AGH treat hosts files like standard AdGuard rules?

![image](https://user-images.githubusercontent.com/22477230/71877731-dfd52580-3164-11ea-9d46-3c9359fc2c89.png)

**Comment by DandelionSprout** [comment]
I think I see the cause for it, as AGH seems to me to be hardcoded to look in the system's own hosts file to look for 'Friendly names', as per https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuring-clients-friendly-names. This does however lead to AGH also interpreting *all IP adresses* in everything «Hosts»-related as being Friendly Names.

But since AGH's own client settings have in recent months become considerably superior to Friendly Names, I would more than merrily vote to discontinue Friendly Names in favour of having AGH treat client IPs more accurately, if such a dilemma was to theorethically come to a vote.

**Comment by ameshkov** [comment]
Duplicate https://github.com/AdguardTeam/AdGuardHome/issues/1284
