### ISSUE TITLE
OpenWrt: can't install the service

### ISSUE THREAD

**Issue by szolin** [AdguardTeam/AdGuardHome#1348]
OpenWrt 19.07-SNAPSHOT

The are many bugs:

1. `-s install` correctly creates the service file in /etc/init.d but fails to start the service, because `service` script doesn't exist.
2. `/etc/init.d/AGH status` always shows Stopped because `ps PID` command doesn't work.
2.1 `/etc/init.d/AGH stop` doesn't work
3. The service file isn't based on standard `/etc/rc.common`, that's why standard commands like `enable|disable` don't work.
4. There's no `boot()` section - the service won't start on boot.
4.1 There's no file in `/etc/rc.d`

**Comment by ameshkov** [comment]
Might be useful: https://github.com/kardianos/service/issues/116

**Comment by WildByDesign** [comment]
@szolin @ameshkov  I am curious about testing the latest commits for this because I use AGH primarily on OpenWrt. I don't use Docker though and have not compiled from source code yet. I do have a couple of questions regarding beta builds:

How do I know which commits made it into the latest beta build?
Or more specifically, which branch is the beta build built from?

Thank you.

**Comment by ameshkov** [comment]
@WildByDesign hi, beta builds are always built from the master branch.

Here's how version is composed:
```
version=`git describe --abbrev=4 --dirty --always --tags`
```

It contains the latest tag name + the last commit hash.
