### ISSUE TITLE
AG Home v0.100.9 caused BSOD on my Windows 10 Pro.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardHome#1366]
AG Home v0.100.9 caused Blue screen of death (BSOD) on my Windows 10 Pro.
I had exited GlassWire firewall, but BSOD still happened.
Additionally, I have Bitdefender and Malwarebytes installed.
.dmp file:
https://app.box.com/s/87zl6f4rissxzrdup1kzgp8c2hhl4ajp

May you tell me which driver causes BSOD?
Thanks.

**Comment by ameshkov** [comment]
The error code is "DPC_WATCHDOG_VIOLATION".

This error code means that some driver (or drivers) take too much time (it may be just a few milliseconds) and Windows considers it an error. The problem is that it's not possible to say what driver is responsible, it may be that you simply have too many network drivers installed.
