### ISSUE TITLE
How to filter custom protocols like "tbopen://" ?

### ISSUE THREAD

**Issue by Edward-Kong** [AdguardTeam/AdGuardHome#1542]
As the title says, js on a webpage always tries to wake up the APP in the background when opening a specific url with an android phone. Specifically, some js on some webpages try to wake up the taobao APP with a protocol that starts with **tbopen://**, it seems that only **https://** and **http://** filters can be added to AdGuard Home. How can I filter the protocol with the beginning of **tbopen://**?

**Comment by DandelionSprout** [comment]
While I have zero experience with `tbopen://` specifically, I know that browser-based adblockers support blocking some other protocols like `ws://` and `whatsapp://` with a single vertical line (`|`) instead of a double one, e.g. `|ws://*taobao.cn^`. Sadly I am not aware of this being possible to do with AdGuard Home's actually pretty narrow DNS filtering functionality.

**Comment by ameshkov** [comment]
`tbopen` is not a real network protocol, it has one and only purpose -- to be handled by some app installed on the device. Custom protocols like that do not provoke any network request so we simply can't do anything with it.
