### ISSUE TITLE
[beta] Couldn't save YAML config

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#1549]
### Issue Details

```
2020/04/06 09:36:13 [info] AdGuard Home, version v0.101.0-50-g1fa6, channel beta
, arch windows amd64%!(EXTRA string=)
2020/04/06 09:36:14 [error] Couldn't save YAML config: chmod C:\AdGuardHome\tmp913951859: not supported by windows
2020/04/06 09:36:14 [fatal] chmod C:\AdGuardHome\tmp913951859: not supported by windows
```

- **Version of AdGuard Home server:**
  - v0.101.0-50-g1fa6 x86, x64

- **Operating system and version:**
  - Windows 10 x64

**Comment by Che-Max** [comment]
Same thing after update from v0.101.0 to v0.101.0-50-g1fa6. 
Config not changed from previous version. If i delete config - service runs normally.

* **Version of AdGuard Home server:**
  * v0.101.0-50-g1fa6
* **How did you setup DNS configuration:**
  * System
* **Operating system and version:**
  * Windows 7 SP1 x86

### Expected Behavior
After update AdguardHome automatically restart and continues to work.

### Actual Behavior
After update AdguardHome automatically restart and ends with fatal error.

### Additional Information

```
2020/04/06 07:07:35 3936#3 [error] Couldn't save YAML config: chmod D:\Programs\AdGuardHome\tmp532768071: not supported by windows
2020/04/06 07:07:35 3936#3 [fatal] chmod D:\Programs\AdGuardHome\tmp532768071: not supported by windows
2020/04/06 07:07:34 3936#3 [debug] Writing YAML file: D:\Programs\AdGuardHome\AdGuardHome.yaml
2020/04/06 07:07:34 3936#3 [debug] Reading config file: D:\Programs\AdGuardHome\AdGuardHome.yaml
2020/04/06 07:07:34 3936#3 [debug] github.com/AdguardTeam/AdGuardHome/home.upgradeConfig(): got schema version 6
2020/04/06 07:07:34 3936#3 [info] AdGuard Home is running as a service
2020/04/06 07:07:34 3936#3 [debug] Current working directory is D:\Programs\AdGuardHome
2020/04/06 07:07:34 3936#3 [info] AdGuard Home, version v0.101.0-50-g1fa6, channel beta, arch windows 386%!(EXTRA string=)
```

[AdGuardHome.yaml.txt](https://github.com/AdguardTeam/AdGuardHome/files/4439502/AdGuardHome.yaml.txt)
[log.txt](https://github.com/AdguardTeam/AdGuardHome/files/4439504/log.txt)

**Comment by ameshkov** [comment]
Please update to the new beta version, the issue should be gone there
