### ISSUE TITLE
Add support for uBO's new "$cname" feature

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1570]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v0.101.0)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Long story short: [uBlock Origin introduced `$cname` in 1.25.3](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#cname), which took me wildly by surprise as I thought I'd suggest they could create such a qualifier. But nevertheless, it seems like a pretty good fit for AdGuard Home that also serves an actual unique purpose, of ensuring that domains are only blocked through their URL address **or** their CNAME responses, instead of both.

That being said, their current implementation is whitelisting-only, for whatever reason. I see no immediate reason for why using `$cname` to only block by CNAME responses can't be done.

### Proposed Solution

Add support for `$cname` to block based on CNAME **only**, and `$~cname` to block based on the main URL **only**.

### Alternatives Considered

Add support for `@@` + `$cname` in much the same way the uBO team did it; or maybe even convince the uBO team to give `$cname` the ability to block things. Either way to ensure cross-extension support.

### Additional Information

Had I known any earlier about uBO adding it, I'd have submitted this feature request several weeks ago... 😬

**Comment by ameshkov** [comment]
>I see no immediate reason for why using $cname to only block by CNAME responses can't be done.

Agreed

**Comment by ameshkov** [comment]
I am starting to think that `$cname` name might be misleading. AdGuard does not limit itself to CNAME scanning, it also checks A and AAAA responses so it's able to block domains by IP address.

Therefore, I suppose we should name this modifier `$dnsresponse` so that it was clear. `$cname` may be an alias kept just for compatibility.

I am also thinking about introducing a `$dnstype` modifier that would allow targeting specific DNS queries by type. For instance, `||example.org^$dnstype=A` or `||example.org^$dnstype=TXT`. It may be useful in conjunction with [`$dnsrewrite`](#2102).

Also, I have to reassign this task to v0.105 as I don't have enough time to take care of it before v0.104 is released.

**Comment by gwarser** [comment]
> That being said, their current implementation is whitelisting-only, for whatever reason. I see no immediate reason for why using `$cname` to only block by CNAME responses can't be done.

It's implemented like `generichide`. It stops blocking CNAME resolved requests for specified document. Not specified request by itself.

**Comment by ameshkov** [comment]
This makes little sense to me. DNS replies are cached by the browser, and if it's blocked once for any website, it will be blocked on other websites regardless of any $cname exclusions.

**Comment by ameshkov** [comment]
Actually, this can be avoided if the domain name is resolved with `bypass_cache`. Although, there would be some other complications due to that if we want to avoid making unnecessary DNS queries.

Anyways, according to @gwarser's description, uBO's $cname is quite different from what @DandelionSprout requested and we simply cannot implement it that way in AdGuard Home.

**Comment by ameshkov** [comment]
Opened two separate tasks: $dnsrewrite and $dnstype: 

* https://github.com/AdguardTeam/AdGuardHome/issues/2337
* https://github.com/AdguardTeam/AdGuardHome/issues/2102
