### ISSUE TITLE
Rolling log files

### ISSUE THREAD

**Issue by maxtar** [AdguardTeam/AdGuardHome#1573]
### Problem Description
At now if verbose logging is enabled producing very huge file. If issue reproducing in not regular time log size may be some hundreds megabytes and more.

### Proposed Solution
I suggest that log file has setting for rolling by time and size.

**Comment by ameshkov** [comment]
Hm, what about configuring the max size for a log file?

**Comment by maxtar** [comment]
As variant.

**Comment by DannyHinshaw** [comment]
@ameshkov I would like to implement this feature. Is there anything I need to do to call dibs and get assigned?

**Comment by ameshkov** [comment]
@DannyHinshaw hi and thank you!

Here's what we currently use for logging:
https://github.com/AdguardTeam/golibs/tree/master/log

In order to configure logging to file we simply call SetOutput:
https://github.com/AdguardTeam/golibs/blob/master/log/log.go#L64

The easiest way to add logs rotation here is to use https://github.com/natefinch/lumberjack and use its instance in `SetOutput` (unless you want to implement logs rotation on your own, in this case, you'd better pull request it to the "golibs" repo first).

The next step would be to extend configuration:
https://github.com/AdguardTeam/AdGuardHome/blob/master/home/config.go#L33

You should simply add the necessary properties to the `logSettings` struct:
https://github.com/AdguardTeam/AdGuardHome/blob/master/home/config.go#L26 

Add `log_` prefix to these new settings to avoid ambiguity.

**Comment by DannyHinshaw** [comment]
@ameshkov great, thank you!

**Comment by DannyHinshaw** [comment]
@ameshkov I'm working on getting this implemented but running into a small issue. To test this I am running the Docker image provided by the `make` file but cannot find the actual `querylog.json` file on the image...

According to the `l.logFile` attribute set in the [`newQueryLog` function](https://github.com/AdguardTeam/AdGuardHome/blob/master/querylog/qlog.go#L40) the full path to the querylog should be `/opt/adguardhome/work/data/querylog.json`. I've added `bash` to the image so I can `docker exec` into it and explore interactively, but when I go searching for that file it is nowhere to be found. 

Am I maybe missing something very simple?

**Comment by DannyHinshaw** [comment]
@ameshkov I have a question on implementation. 

It appears there is already some form of rotation going on with the querylog with the `periodicRotate` [here](https://github.com/AdguardTeam/AdGuardHome/blob/8b25a4886ef830a20d71009dda012fb6400e0db4/querylog/querylog_file.go#L101), the exact purpose of this isn't super clear to me... it appears to every 24hr "rotate" by naming the current `querylog.json` file to `querylog.json.1`... but what happens after `querylog.json.1` already exists? What purpose is this serving?

My initial thoughts are that this functionality will need stripped as it would conflict with `lumberjack`s file rotation. Thoughts?

**Comment by ameshkov** [comment]
@DannyHinshaw 

Query log is already rotated. There's some space for improvement, but not really that much.

This task is about rotating regular log files. Logging to file is enabled if you specify `log_file` in `AdGuardHome.yaml`

**Comment by ameshkov** [comment]
The problem that we're trying to solve is that when people enable verbose logging + logging to file, the log file size becomes really-really huge rather quickly. 

And this is important to be able to keep verbose logging all the time. For instance, when you're trying to catch some random bug.

**Comment by DannyHinshaw** [comment]
@ameshkov thank you for clarifying 👍 

I have a somewhat unrelated question at the risk of seeming dense, what development flow are most people using when working on the api? Are most creating their own `docker-compose` configs to cache everything but the server? 

Running `make docker` to test every small change hardly seems sane...

**Comment by ameshkov** [comment]
@DannyHinshaw can't say for everyone, but I don't usually use docker at all.

I simply have a couple of different launch configurations in Goland (you can have the same in VS Code if you prefer it) with the following changes:

* Add `-tags=delve` argument for `go`
* Add `-w PATH` argument for the program (so that I could switch between different data directories with different configurations).

That's more or less it.

**Comment by DannyHinshaw** [comment]
@ameshkov thank you 👍 

Can you tell me the purpose of this line, it isn't immediately clear to me... 
https://github.com/AdguardTeam/AdGuardHome/blob/32d1f385ff4252fdda5d81928caaa09052b62451/home/home.go#L417

If that block returns is no logfile ever created?

**Comment by ameshkov** [comment]
@DannyHinshaw yeah, that's right

By default, logs are written to stdout

**Comment by ameshkov** [comment]
I guess it makes sense to add a comment about that there
