### ISSUE TITLE
add time limit/control for specified device, such as: user_child only available on daytime

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1594]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
I'm very glad to see AGH has some function that can be used for parental control. Use tag to divide device is a good plan, but is there have someway to limit children's  Internet time? I know in mobile devices like Android/iOS both have ParentControl to limit screentime, but not in Windows, we all know that child have less self-control and easy to play computer too late, but they are asked for stay at home and use Windows on PC for online lesson, so it is a challenge to keep children a healthy digital life.
### Proposed Solution

add time limit/control for the specified device in current device tag system: device which tagged `user_child`  only available on daytime or limits total serve time.

**Comment by hnnweb** [comment]
Blocking this with DNS is bad.
the kids will learn to surf by ip or change dns servers.

**Comment by Mosney** [comment]
> Blocking this with DNS is bad.
> the kids will learn to surf by ip or change dns servers.
> 
> IMO this is out of scope for the product

Reasonable, but I think they cannot understand how to bypass now ( Even I still can block UDP53 or DoT/H in firewall). And if it is not product scope why develop user_child device tag? Block porn or something violence? But it still can be bypass easily too.

**Comment by ArchiveBase** [comment]
@Mosney You can use hardware firewall for that and as @hnnweb said, this seems not applicable as long as AGH develop as DNS server

>but is there have someway to limit children's Internet time?

This feature may help bit #1203 and you can add this regex: /.+/ to timed blocklist but i proposed to set maximum block or allow time 12hrs to prevent misuse that. however currently you can try to do above task manually
https://github.com/AdguardTeam/AdGuardHome/issues/951

>And if it is not product scope why develop user_child device tag?

For https://github.com/AdguardTeam/AdGuardHome/issues/817 https://github.com/AdguardTeam/AdGuardHome/issues/435

> Additionally, almost all other similar products have parental control ,for example NextDNS.

AGH has parental control facility as well.

**Comment by Mosney** [comment]
@ArchiveBase That's okay, but I still look forward a timer feature, I think it will enhance parental control.

**Comment by anoma** [comment]
After looking for the feature I hunted out this request.

I think this would be a strong feature to add. Useful for all the obvious reasons.

Just to reply specifically to this comment:

> Blocking this with DNS is bad.
> the kids will learn to surf by ip or change dns servers.
> 
> IMO this is out of scope for the product

The idea is not to consider kids as `bad actors` to be defended against, it is simply to give parents some tools to help them be parents.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdGuardHome/issues/951

**Comment by moshecom** [comment]
Hi everyone! 
I love AG, and I believe that every family should apply AG or similar given the growing threats around us. 
For example:
1) Blocking TikTok might be a good idea for a family with smaller children
2) Blocking TikTok might be desirable yet simply impossible for a family with teenagers

The "better" approach in case 2, would be to make sure the teenagers have access but are not constantly on it.
So in my TikTok example, they'd have access from 8am till 10pm. And then if they're on it for 15mins straight, they'll be blocked for a cooldown period, for example 45mins.

I'd love to contribute to help make time limits and time spans happen.
I can code, and have a strong background in product management. 
How can I help? Anyone wants to collaborate as a team?

**Comment by hnnweb** [comment]
> And then if they're on it for 15mins straight, they'll be blocked for a cooldown period, for example 45mins.

That would be great if the devices didn't cache DNS. Most devices cache DNS responses and respect the TTL value in DNS.
In which the result will not happen directly since AGH is not a proxy.

**Comment by tdruiva** [comment]
Hi, thank you for all job you do at AGH :heart: 

Currently I am supporting a group where they are having social issues because of "internet". Internet was not part of their life in the daily day but now it is more present, teens are avoiding in person social life and their obligations to be connected. Chatting with them seems not to solve (elders are still trying different approaches to change the situation).

Some of them found a way to solve like shutting down local connection completely but they would love to have a middle way solution where some could have connection (like the "responsables") and others to have less connectivity (like WhatsApp open all the time but TikTok and others restricted during some time)

Currently we are "solving" it with router management system but it has its restrictions, its interface is not user friendly; it is limited to 16 "full-connection" devices  and more.

We are using AGH to block spam/games/other websites and I saw AGH has a blocking interface where we can choose what to block and what time it can be open so my question is: can we expand this feature? I mean:
 - adding a list of "super power" users (devices) without restriction;
 - to add more flexibility for time picking, like: 2 hours free in the morning then +2 hours free in the end of the day;
 - to add a regex to block more websites;

I can contribute to get it done, it could be with code, testing or preparing some user stories. I just need some help :hugs:
