### ISSUE TITLE
Unable to configure AdAware to be a DoH / HTTPS DNS Client (Bootstrap DNS servers)

### ISSUE THREAD

**Issue by MelCrypto** [AdguardTeam/AdGuardHome#1628]
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ Y] I am running the latest version (Raspberry Pi4 running 2.3.3)
- [Y ] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed

### Issue Details
I would like to configure the AdGuard DNS Client on my Raspberry Pi4 to use ONLY HTTPS/DoH as a means to resolve DNS queries.

I am not able to configure Bootstrap DNS servers in DNS Client config area to perform DNS request over TLS/DoH.

I am only using IP addresses for the Upstream DNS Server and I do not want my Raspberry to send ANY DNS/UDP cleartxt request to the Internet

https://149.112.112.112/dns-query
https://8.8.4.4/dns-query
https://8.8.8.8/dns-query
https://1.1.1.1/dns-query
https://1.0.0.1/dns-query
===========================
➜  ~ ha dns info              
host: 172.30.32.3
locals:
- dns://192.168.252.11
- dns://192.168.252.12
- dns://8.8.8.8
servers:
- dns://1.1.1.1
- dns://8.8.8.8
version: "9"
version_latest: "9"

Please advise ?

* **Version of AdGuard Home server:**
2.3.3
* **How did you setup DNS configuration:**
System / DHCP
* **If it's a router or IoT, please write device model:**
Raspberry Pi 4 Model B
* **Operating system and version:**
Home Assistant latest build

### Expected Behavior
No DNS/UDP request should be sent to the Internet since there is no need to resolve the Upstream Resolvers

### Actual Behavior
UDP/53 DNS Request are seen leaving the Raspberry Pi4s to DNS resolver 1.1.1.1

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdGuardHome/issues/960

Meanwhile, there's an alternative solution. You can use a "DNS Stamp" with encoded server IP instead of a plain/text address.

Here's an example on how to do this:

1. Head to https://dnscrypt.info/stamps
2. Choose DNS-over-HTTPS protocol
3. Enter "8.8.8.8" to IP address
4. Enter "dns.google" to hostname and "/dns-query" to path

Here's the stamp that I've got:
`sdns://AgcAAAAAAAAABzguOC44LjgACmRucy5nb29nbGUKL2Rucy1xdWVyeQ`

Server IP address is encoded into that snap so AdGuard Home won't make any attempt to bootstrap the hostname.
