### ISSUE TITLE
cpu high usage

### ISSUE THREAD

**Issue by scfzr** [AdguardTeam/AdGuardHome#1688]
### Issue Details

* **Version of AdGuard Home server:**
AdGuard Home v0.102.0
* **How did you setup DNS configuration:**
> bind_host: 192.168.1.1
bind_port: 3005
users:
 name: xxx
  password: xxx
http_proxy: ""
language: pt-br
rlimit_nofile: 0
debug_pprof: false
web_session_ttl: 720
dns:
  bind_host: all
  port: 53
  statistics_interval: 1
  querylog_enabled: false
  querylog_interval: 1
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
  tls://1dot1dot1dot1.cloudflare-dns.com
  tls://dns.google
  bootstrap_dns:
   189.39.219.4
   201.87.150.8
  all_servers: true
  fastest_addr: false
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts: []
  cache_size: 0
  cache_ttl_min: 0
  cache_ttl_max: 0
  bogus_nxdomain: []
  aaaa_disabled: true
  enable_dnssec: false
  edns_client_subnet: false
  filtering_enabled: true
  filters_update_interval: 24
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 0
  safesearch_cache_size: 0
  parental_cache_size: 0
  cache_time: 30
  rewrites: []
  blocked_services: []
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  allow_unencrypted_doh: false
  strict_sni_check: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
filters:
 enabled: true
  url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
  name: AdGuard Simplified Domain Names filter
  id: 1
 enabled: true
  url: https://adaway.org/hosts.txt
  name: AdAway
  id: 2
 enabled: true
  url: https://www.malwaredomainlist.com/hostslist/hosts.txt
  name: MalwareDomainList.com Hosts List
  id: 4
 enabled: true
  url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
  name: NoCoin
  id: 1589392548
whitelist_filters: []
user_rules:
 '||manifest.googlevideo.com'
 '||an.facebook.com'
 ""
dhcp:
  enabled: false
  interface_name: ""
  gateway_ip: ""
  subnet_mask: ""
  range_start: ""
  range_end: ""
  lease_duration: 86400
  icmp_timeout_msec: 1000
clients: []
log_file: ""
verbose: false
schema_version: 6

* **If it's a router or IoT, please write device model:**
 Edgerouter ER-X
* **Operating system and version:**
 EdgeRouter X v2.0.8-hotfix.1

### Actual Behavior
High CPU consumption after restarting the router caused by AdGuardHome, causing system crash. After a few minutes it normalizes.

### Screenshots
![image](https://user-images.githubusercontent.com/65471332/82133024-0400dd00-97bd-11ea-90fa-e71f1e80b8ac.png)

**Comment by nzm001** [comment]
Almost exactly the same problem with AdGuard Home v0.102.0 and Raspberry Pi Zero (Raspbian Buster). Then I decide to implement  AdGuard Home v0.102.0 on Raspberry Pi 4B which works fine. Is Pi Zero not suitable as a DNS server any more?
I only change my configuration: 'ratelimit: 0' (unlimited) and use both cloudfare, adguard and quad9 dns server with 'Fastest IP address'. I guess this problem caused by 'Fastest IP address', the new feature added which I can't wait to upgrade to speed up my internet access. If I use Parallel requests, not Fastest IP address, AdGuard Home v0.102.0 will take less than 50% cpu. Maybe I should avoid using too many or too slow resolvers or even just use one resolver.
Reduce the number of upstream_dns might help. @scfzr

**Comment by ameshkov** [comment]
> Maybe I should avoid using too many or too slow resolvers or even just use one resolver.

If you're using `Fastest IP` or `Parallel requests` and you're running AGH on a slow device, you'd better use plain DNS resolvers instead of DOH/DOT. They require additional CPU time to establish an encrypted connection and might not be suitable.

@scfzr it'd help a lot if you could record the log on AGH startup and explain at what point the CPU usage is that high:

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue
3. Post the log file here.

**Comment by scfzr** [comment]
> @scfzr it'd help a lot if you could record the log on AGH startup and explain at what point the CPU usage is that high:
> 
> 1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
>    
>    * Specify `log_file`
>    * Set `verbose` to `True`
> 2. Restart AdGuard Home and reproduce the issue
> 3. Post the log file here.

The logs was too long, can it be leaner??? I couldn't reproduce the problem, it looks like it was temporary.

Disabled **Parallel requests** and change DOT for DOH, I felt an improvement.

**Comment by ameshkov** [comment]
> The logs was too long, can it be leaner???

Well, these are debug-level logs, they're supposed to be huge:)

**Comment by liuran001** [comment]
> > Maybe I should avoid using too many or too slow resolvers or even just use one resolver.
> 
> If you're using `Fastest IP` or `Parallel requests` and you're running AGH on a slow device, you'd better use plain DNS resolvers instead of DOH/DOT. They require additional CPU time to establish an encrypted connection and might not be suitable.
> 
> @scfzr it'd help a lot if you could record the log on AGH startup and explain at what point the CPU usage is that high:
> 
> 1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
>    
>    * Specify `log_file`
>    * Set `verbose` to `True`
> 2. Restart AdGuard Home and reproduce the issue
> 3. Post the log file here.

I felt an improvement when I use plain DNS resolvers instead of DOH/DOT.

**Comment by renannprado** [comment]
I don't have the `Fastest IP` nor the `Parallel Requests` set and I still have the CPU problems... I can't tell the cause though :(

**Comment by weedb0y** [comment]
I have had same issues with Pi Zero and Adguard Home. I ended up reverting to Pihole on Pi Zero and switching to AdGuard home on RPI 2B+. I have both parrallel and fastest IP unchecked as it does seem to cause performance issues over a longer period of time.
