### ISSUE TITLE
Recommended way to package AdGuardHome with systemd serivce

### ISSUE THREAD

**Issue by graysky2** [AdguardTeam/AdGuardHome#1699]
I am packaging the Arch Linux package of [AdGuardHome](https://aur.archlinux.org/packages/adguardhome/).  I want it to run as a non-privilege user using the following systemd service, but I am finding that I have to first run it manually as root to create `/var/lib/adguardhome/AdGuardHome.yaml` which is not optimal.  As well, I have to `chown -R adguardhome:adguardhome /var/lib/adguardhome` after I set it up initially which is also sub-optimal.

Is there a way I start it via my service and have that config file generated at the same time?

```
[Unit]
Description=AdGuard Home: Network-level blocker
ConditionFileIsExecutable=/var/lib/adguardhome/AdGuardHome
After=syslog.target network-online.target

[Service]
User=adguardhome
Group=adguardhome

AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/var/lib/adguardhome/AdGuardHome -s run

WorkingDirectory=/var/lib/adguardhome
StandardOutput=file:/var/lib/adguardhome/AdGuardHome.out
StandardError=file:/var/lib/adguardhome/AdGuardHome.err
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

**Comment by ameshkov** [comment]
> Is there a way I start it via my service and have that config file generated at the same time?

There's none, mostly because there was no need for that. However, we can add such way as it does indeed make sense to have something like that if we want to package AGH.

We were thinking about providing a command like this one:
`./AdGuardHome --init --web-port=80 --dns-port=53 --username=admin --password=admin`

It will generate `AdGuardHome.yaml` and the initial setup (and root) won't be needed when your run AGH afterward.

What do you think? Would it be sufficient for you?

**Comment by graysky2** [comment]
Could the software itself, upon not detecting `./AdGuardHome.yaml` default to create it in the directory where `AdGuardHome` is running?

I think in order for the service to be general enough, something like that would need to happen so that the config file could be owned by the non-root user.  As well, `./data/` would also be owned by that user.

**Comment by ameshkov** [comment]
> Could the software itself, upon not detecting ./AdGuardHome.yaml default to create it in the directory where AdGuardHome is running?

Currently, if `AdGuardHome.yaml` is not found, it starts up in the "initial setup" mode where the user is able to do some initial configuration (choose ports, user/password, etc).

I doubt that this is really necessary to even use this mode if we're talking about a package.

Here's what I was thinking about:

1. Add an install shell script: https://wiki.archlinux.org/index.php/PKGBUILD#install
2. Ask and validate desired ports (web, dns) and admin user name and password
3. Run `AdGuardHome --init` command that will generate the configuration with the desired ports/user

Alternatively, we can provide something like `--no-root` flag or use some other way to detect that root is not required.

**Comment by graysky2** [comment]
Main thing from my view is to have out-of-the-box functionality without having the user jump through hoops with permissions and such.  Currently, if you run `AdGuardHome -s run` as root, it behaves as I would expect creating the config file and making its data directory.  Why does it behave differently when called as a non-root user on initial run?

**Comment by ameshkov** [comment]
> Why does it behave differently when called as a non-root user on initial run?

The main reason for that is that people were trying to run AdGuard Home without root and simply could not go through the initial setup because without root AGH could not bind to the ports it needs (53,80,443,etc). You've already solved it by granting CAP_NET_BIND_SERVICE, though.

Other than that, root is not really necessary and we can live without it.

@szolin what if we replace root check on the first run with something less restrictive? For instance, we could check if AGH is able to bind to ports below 1024 instead.

**Comment by graysky2** [comment]
@ameshkov - I think that would be fine.  Currently, a post_install directs the user to:
```
  echo "==>   FIRST TIME SETUP"
  echo "::  1. First time run as root:  /var/lib/adguardhome/AdGuardHome"
  echo "::  2. Log in to web interface to create config: http://ip.of.server:3000"
  echo "::     Stop AdGuardHome with ctrl+c when complete"
  echo "::  3. Fix permissions:  chown -R adguardhome:adguardhome /var/lib/adguardhome"
  echo "==>   Now you can start AdGuardHome.service via systemd and run as the unprivileged user"
```

**Comment by ameshkov** [comment]
Got it, I'll do it then
