### ISSUE TITLE
More blocked services

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardHome#1721]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Proposed Solution
Add blocking of:
- Korean social network KakaoStory(kakao.com);
- LINE messenger (line.me)

**Comment by eoopx** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1692 
Anyway those two are mobile apps only local(korean) services :/

**Comment by Alex-302** [comment]
All services are not blocked by default.

**Comment by eoopx** [comment]
> All services are not blocked by default.

But when add new clients in clients settings page (all are blocked by default and needs to disable manually)

---

About my concern, i'm not interest to see any barrier for local based companies. Eg: communication services. Yandex messenger(russia), Line(korea), Viber(japan), WeChat(china) So it makes difficult for one country(USA) (facebook, whatsapp, imo etc) to gather all humans data in this planet.
In korea; most people, kpop idols and related all companies mainly use instagram and twitter or fb.

Months ago, when suggest to add tiktok(china) then no one talked against except helped alot because it mess everywhere. that's a one point

For social networks, you guys can do something like nextdns does. this also help to avoid new people(eg: foreigners) know about those local social platforms

![image](https://user-images.githubusercontent.com/61364121/82756747-3c7c6880-9e06-11ea-894b-4c3c407199fc.png)
https://github.com/olbat/ut1-blacklists/blob/master/blacklists/social_networks/domains

**Comment by eoopx** [comment]
_P.S.: comment_
I needed to block/unblock most of the internet access including mentioned services in the weekends. I remembered that i raised a dislike here. if required, you can reopen. According to 2 years ago blocklist, i thought that's for companies like over 1 billion or something like GAFAM 😀

**Comment by ainar-g** [comment]
@eoopx, hello.  I'm not sure what you mean.  Do you mean that the feature request should be reopened, and that those services should be added to our list?
