### ISSUE TITLE
Add new language: en-silk

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardHome#1796]

**Comment by ameshkov** [comment]
Mm, what's that?

**Comment by Archive5** [comment]
සිංහල (Sinhala)
Above the language code used in crowdin

**Comment by ameshkov** [comment]
@ArtemBaskal please consult with @aalpatkina and check if it's ready to be added, and if there are any other languages that can be added.

**Comment by aalpatkina** [comment]
@Archive5 the translation of AG Home into Sinhala is not completed on Crowdin. Please check it.

**Comment by Archive5** [comment]
@aalpatkina no technical words available for bootstrap, DHCP lease, upstream etc so these sentences remain untranslated and will be added soon. department of language has assisted to avoid modernize and use or promote english relational words among people then we usually ask help from government or language experts since no such serious knowledge for create words suitable for use in IT field.

Recent version eg: thai @szolin suggested new languages https://github.com/AdguardTeam/AdGuardHome/issues/1445 have untranslated strings more than sinhala.

**Comment by ArtemBaskal** [comment]
Closed https://github.com/AdguardTeam/AdGuardHome/commit/f8924f0785eaca6a79366de08af4cfbb4001bbad
