### ISSUE TITLE
Dashboard is loading very slowly when there are many IP/CIDR in the Disallowed clients list

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardHome#1920]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v0.103.2)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.103.2
* **How did you setup DNS configuration:**
  * N/A
* **If it's a router or IoT, please write device model:**
  * Raspberry Pi 4 4GB
* **Operating system and version:**
  * Windows 10 May 2020 Update

### Expected Behavior

The frontpage dashboard of my AGH server are loaded in 1sec, which was the case prior to v0.103

### Actual Behavior

The frontpage take considerable amounts of time to load, roughly related to how many queries that are in the *DNS Queries* tally. When the counter showed merely 14,000 queries (which is very little for a 7-day tally), the dashboard needed 4 *minutes* to load.

Resetting the statistics brought the loading times back to normal, and with 361 queries it needs 7-12sec to load.

This does not affect any other tab or page on the AGH server menu that I can see.

When the frontpage has finally been loaded, Chrome's dev console begins to show message port closing errors. This however affects all pages on the server. Sadly it is unknown to me if they also showed up in v0.102 or not.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/88358406-1c6a1680-cd6f-11ea-9bbf-76c69036ddcd.png)

![image](https://user-images.githubusercontent.com/22780683/88358505-82569e00-cd6f-11ea-926b-350c88347a0f.png)

</details>

### Additional Information

I'm unsure what kind of log-file information I'd have needed to provide to you guys or not, or even where those log files are...

**Comment by ameshkov** [comment]
Please check the network panel in dev tools, do you see any slow request there?

**Comment by DandelionSprout** [comment]
Oddly enough no. 
![image](https://user-images.githubusercontent.com/22780683/88363785-74aa1400-cd81-11ea-852c-e499f966d795.png)

It seems I can (most likely?) rule out the homepage's .js file from having been the culprit either.

**Comment by ameshkov** [comment]
Well, "find" seems to be slow, it's still in the "pending" state on the screenshot. How many clients (manual and runtime) do you have?

**Comment by ameshkov** [comment]
Just in case, try disabling the browser extensions to see if any of them could be messing with that request

**Comment by DandelionSprout** [comment]
Apparently the main culprit among the pending ones, is `https://dandelionsprout.asuscomm.com:2501/control/clients/find?ip0=192.168.1.130&ip1=192.168.1.1&ip2=2001%3A4666%3A3fa4%3A0%3A55b2%3Afd63%3Aff89%3A5754&ip3=74.82.47.2&ip4=192.168.1.85&ip5=2001%3A4666%3A3fa4%3A0%3A658b%3A199b%3A2aa3%3A20bd`. I can only partially make sense of it, so I presume you have more instinctive knowledge of that URI metadata than what I have.

Judging by "Client settings", I have 32 manually assigned clients, and 22 "runtime" clients.

I've tried on a fair few browsers, though not yet with a blank-state setup without extensions or cookies. Give me ~4min.

**Comment by DandelionSprout** [comment]
Testing on a blank-slate browser setup, shows that *no* files are shown as pending, yet the site needs 10sec to load. 
![image](https://user-images.githubusercontent.com/22780683/88364640-cc497f00-cd83-11ea-9d2f-4ea5c397b4ea.png)

**Comment by ameshkov** [comment]
Hm, I'll need to think a bit about how to troubleshoot this, no idea what's going on yet.

Anything strange in the console on this clean browser?

**Comment by DandelionSprout** [comment]
Not that Vivaldi is willing to tell me about, in that case. 
![image](https://user-images.githubusercontent.com/22780683/88365314-e4220280-cd85-11ea-963d-00310a66367a.png)

**Comment by Eyeborgs** [comment]
I have a problem loading the page too plus to everything, the browser loads both the CPU and RAM very much during page load which lasts about ~ 10 seconds
Windows Server 2012 R2

On the other machine, everything works fine and I can't figure out what the problem is
Windows 10

I was forced to return the previous version

Browser and tests conducted from different computers

**Comment by ameshkov** [comment]
@DandelionSprout I've figured out, the issue is caused by WAAAAY too slow parsing of the "disallowed clients" list.

We need to rework the way this check is conducted.

**Comment by ameshkov** [comment]
@szolin the only viable solution I see is to supply this information from the server-side. This is the only way to make it work fast enough.

Here's what I propose:

1. Change the `/control/clients/find` method, add information about whether this client is blocked or not (and if blocked - by what rule). If the "Allowed clients" list is not empty, and the client is not listed there, this needs to be indicated as well.
2. On the UI side, use this information to indicate client access status.
3. "Unblock" method should remove the corresponding item from the disallowed clients list (even if it's a CIDR).
4. If the client is not allowed because it's missing from the "Allowed clients" list, "Unblock" button must be shown, but be in the "disabled" state. Tooltip text: "The client is not allowed because it is not in the "Allowed clients" list."
