### ISSUE TITLE
add blocklist failed

### ISSUE THREAD

**Issue by jkle112** [AdguardTeam/AdGuardHome#1955]
Error: control/filtering/add_url | Couldn't fetch filter from url https://hblock.molinero.xyz/hosts: context deadline exceeded (Client.Timeout or context cancellation while reading body) | 400

Openwrt x64 in mini PC

Need support large file that custom blocklist over 50MB,or 100MB.

**Comment by DandelionSprout** [comment]
My unqualified guess, based on the warning (which implies the download was halted partway through due to timeout on the connection to Molinero), is that the mini-PC seems to be very slow, either in speed or its internet connection.

I can't off the top of my head come up with a solution for this one, besides difficult/unlikely ideas like a CPU upgrade or double-checking the stability of your internet connection.

**Comment by ameshkov** [comment]
Alternatively, you can download the blocklist manually and then add it to AdGuard Home by specifying the local path to it instead of the URL: `/path/to/file.txt`

**Comment by greensnow0815** [comment]
Although there is that "work around" I have to mention that big filters lists worked on small devices (like GL.int AR750 creta) upto version v0.107.21. Its from v0.107.22 (also tested .23, .25, .38 and v0.108.0-b.46) that AdGuard is not able to process filters fast enough. Even on a GL.iNet A1300 slate plus (which has slightly more power) it fails starting from v.107.22:

`Mon Sep 25 11:49:14 2023 user.notice AdGuardHome[25810]: 2023/09/25 09:49:14.454411 [error] os.Chtimes(): chtimes /etc/AdGuardHome/data/filters/1695634938.txt: no such file or directory
Mon Sep 25 11:49:14 2023 user.notice AdGuardHome[25810]: 2023/09/25 09:49:14.454875 [error] POST 192.168.8.1:3000 /control/filtering/add_url: Couldn't fetch filter from
url https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt:
scanning filter contents: context deadline exceeded (Client.Timeout or context cancellation while reading body)
`
