### ISSUE TITLE
Allow overriding subnet data on EDNS for privacy and accuracy

### ISSUE THREAD

**Issue by toomuchio** [AdguardTeam/AdGuardHome#1974]
Basically a text-field could be added in the configuration menu such that alternative public IPs could be given for generating EDNS sub-net data.

This would enhance privacy as you could pick random public IPs from your ISP (Or even another ISP) in different ranges, that still Geo-Locate to the same area as your real public IP, to be used for EDNS sub-net data sent to upstreams.

This would prevent your real subnet being exposed while still reaping the benefits of EDNS.

This is already implemented at NextDNS (described here https://medium.com/nextdns/how-we-made-dns-both-fast-and-private-with-ecs-4970d70401e5), but they do selection of the spoofed public IP for you, based on GeoIP look-ups on your origin AS' IP allocations.

For now I think a simple text-area allowing overrides and randomly selecting one would do, but perhaps it could be expanded later to do what NextDNS does.

Would also be useful if you have multiple public IPs and want to force a certain one.
Or if your ISP has bad GeoIP data for your public IP, you could override with a public IP that's correctly Geo-Located (Happening a lot lately due IP re-allocations).

**Comment by ameshkov** [comment]
This may be useful for those who run AdGuard Home on a public VPS server.

Alternatively, you can choose an upstream that does not send EDNS: Cloudflare, AdGuard, or use NextDNS with their EDNS spoofing.

**Comment by toomuchio** [comment]
> This may be useful for those who run AdGuard Home on a public VPS server.
There's actually already an option for that, it sends the clients public IP instead of the DNS servers public IP.

> Alternatively, you can choose an upstream that does not send EDNS: Cloudflare, AdGuard, or use NextDNS with their EDNS spoofing.
Correct but the idea is to get the benefits of EDNS while still keeping your privacy, trusting a 3rd party to spoof for you like NextDNS isn't something I want to do. Also you have to pay for their service.

> Note that dnsproxy that we're using as a DNS server implementation does support configuring EDNS address.
Not sure if that's true since there is an option to override with the clients public IP, see the first quote.

> those who can contribute this
I'm happy to do help or send a PR, but I figured I'd see if a developer who knows the code base wants to first, instead of me fumbling about trying to implement it.

**Comment by adrianmace** [comment]
@toomuchio would like a field in the UI that allows you to specify your own 'public IP' which is passed to `dnsproxy` similar to the _second_ example in the document listed here https://github.com/AdguardTeam/dnsproxy#edns-client-subnet.

Currently, if you run AGH internally and enable the "Enable EDNS Client Subnet" option in the UI, it will **not** correctly enable EDNS Client Subnet since the requestors IP will be an RFC1918 (192.168.0.x) address ie. that of the laptop submitting the query request. I believe the AGH code will just fall back to sending the it's own public IP if the requestors IP is a private one.

If there is second option - available only if you enable the "Enable EDNS Client Subnet" option - which lets you specify the IP that is submitted to the upstream resolver, then you can get the benefits of ECS as well as the privacy similar to how nextdns implemented their patch - without having to run AGH externally from your own network.

Practical example. Me in Melbourne, Australia with an IP assigned by Telstra's Melbourne IP range could override the ECS IP for one that I know is in Telstra Sydney's IP ranges. I'll still see benefits by receiving DNS responses relevant to a City _near_ me instead of one on potentially the other side of the world, but without exposing my IP address at all to authoritative DNS servers.

**Comment by toomuchio** [comment]
I've achieved it by setting EDNSAddr, the option exists it's just not exposed to AdGuardHome.
https://github.com/AdguardTeam/dnsproxy/blob/7b79d1c7e5292aa0a3a8440e9ac794e204ae29f3/main.go#L101

It's pretty trivial to add, I'll let your team do it since it needs translations and UI stuff. And I hard coded things to see if it would work *yuck*.

Initially I described a system that would allow the input of multiple IPs and selecting one at random but a single override is probably sufficient and easy to implement.

This request is a duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/1472

So that can be closed as well if this is implemented.

**Comment by ameshkov** [comment]
Yeah, you're right, closing as dup.

Regarding contribution and UI stuff, I guess I should add this to the README: we don't expect people to contribute to both UI and golang part of the program as that would be too complicated. Ideally, the golang part is implemented first - configuration, API and the functionality itself, and the UI part can be implemented later in a different PR by a different person.
