### ISSUE TITLE
Is there any principle for official filters?

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardHome#1988]
I noticed [anti-ad](https://github.com/privacy-protection-tools/anti-AD) has been included in the AdGuardHome official filters https://github.com/AdguardTeam/AdGuardHome/commit/304a51f17e2a6adf720b8c0eb62da041498415e9.

I suppose I should notice you this list includes some irrelevant item in it, for example, it includes many domain about [FaLunGong ](https://en.wikipedia.org/wiki/Falun_Gong) and its news/media site which banned from China authority but actually not AD or privacy-protection-purpose. I opened an [issue ](https://github.com/privacy-protection-tools/anti-AD/issues/140)(see this [screenshot](https://user-images.githubusercontent.com/22477230/83049623-0cd79580-a07e-11ea-94e6-40914c17ca69.png)) to the origin maintainer [gentlyxu](https://github.com/gentlyxu) but has been deleted  , he says "Yes, I extremely hate those idiot so I  will never unblock it and stop foolish and don't bother me again!". 

So whether AdGuardHome official recommend filters have some rules/principle? Even it contain subjective item, totally advertising irrelevant. just its maintainer's like or dislike. I think chose this list as official filter is irresponsible, not only to users but also to your reputation.

Therefore I think this list can't be trusted and collect some proof then create a new repo to let more people know what he did. 
See https://github.com/Mosney/anti-anti-AD

**Comment by ameshkov** [comment]
First of all, thank you for notifying us about this!

Please give me some time, I'll look into it. If this is true, the problem with this is not just that the rules are subjective, but that people don't expect this behavior. Nowhere in the list's repo I see a warning that it'll block more than just the ads.

Anyways, what alternative Chinese-focused lists do you suggest?

**Comment by Mosney** [comment]
> Nowhere in the list's repo I see a warning that it'll block more than just the ads.

Yep, that is the option I suggested before, but the maintainer ignore it and delete issue.

> Anyways, what alternative Chinese-focused lists do you suggest?

I list at https://github.com/Mosney/anti-anti-AD 's last, select some Chinese-focused list here.

> - [neoFelhz/neohosts](https://github.com/neoFelhz/neohosts) -  Strongly Recommend 
> - [ACL4SSR/ACL4SSR](https://github.com/ACL4SSR/ACL4SSR/tree/master)  - ACL rules, not sure AdGuardHome if compatible
> - [vokins/yhosts](https://github.com/vokins/yhosts) - Take over by [VeleSila/yhosts](https://github.com/VeleSila/yhosts) now

**Comment by ameshkov** [comment]
> Yep, that is the option I suggested before, but the maintainer ignore it and delete issue.

Could you please point out these non-ad domains in the list?

> I list at https://github.com/Mosney/anti-anti-AD 's last, select some Chinese-focused list here.

neoHosts seems to be abandoned?

**Comment by hezhijie0327** [comment]
![Xnip2020-08-03_21-08-58](https://user-images.githubusercontent.com/58100052/89185891-900cee80-d5cd-11ea-9d70-2e26dcf8fadb.jpg)

**Comment by DandelionSprout** [comment]
Although I haven't looked much into this breaking-news situation, there's two things about this that took me by surprise.

1) Like what hezhijie confirms in the comment above, I know that neoHosts used to actively disclose that it's heavily anti-Falun Gong. Looking into the lists, those entries seem to be limited to neoHosts Full, and is not in neoHosts Basic... at least not at the time of writing.

2) Since *anti-ad* makes official list versions for Surge and SmartDNS, tools commonly used to *evade* website blockings in PR-China, it seems confusing (although believable) to me that it'd add entries against one of the firewalls' most attacked targets.

**Comment by ameshkov** [comment]
@DandelionSprout well, this is explained in NeoHosts readme.

![image](https://user-images.githubusercontent.com/5947035/89231744-9bbcdd00-d5ee-11ea-9634-ce47340db787.png)

**Comment by DandelionSprout** [comment]
I guess that confirms my worries, which previously had been based on a much older README version that was immortalised in FilterListsCOM's database.

**Comment by ameshkov** [comment]
So it seems that at least two popular Chinese lists prefer to take some stance on political/religious issues in addition to their main purpose.

I see two options here:

1. Add a disclaimer in the UI that these lists may be blocking domains based on their authors' political/religious, or other preferences.
2. Don't add them to the list of "vetted" lists and keep only single-purpose lists there.

Any opinion is welcome, but since we're talking about Chinese lists, I'd like to understand what Chinese users think about it.

亲爱的中文用户们，对于这件事情你们什么看法？

**Comment by DandelionSprout** [comment]
Option 3 could've been to add an "Exclusions" section for each list, known from the AdGuardFilters repo. But in this case that'd be a shortterm solution at best.

**Comment by Mosney** [comment]
> Could you please point out these non-ad domains in the list?

You can search Falun gong relevant keyword below in that list,
```
minghui
falun
ntdtv
dongtaiwang

```
And another user also [found some media domain blocked](https://github.com/privacy-protection-tools/anti-AD/issues/160), still has been deleted by maintainer. See those domain [Screenshot](https://user-images.githubusercontent.com/22477230/86547998-654b5e00-bf6d-11ea-9d6b-fdd259e391ef.png) before deleted.

> neoHosts seems to be abandoned?

I don't think so, just not update frequently, he adds some AdGuardHome compatible in January after [I ask](https://github.com/neoFelhz/neohosts/issues/82).

**Comment by Mosney** [comment]
> Since anti-ad makes official list versions for Surge and SmartDNS, tools commonly used to evade blockings in PR-China, it seems confusing (although believable) to me that it'd add entries against one of the firewalls' most attacked targets.

I guess it's PRC particular circumstance that creates a lot of paradoxical psychology, or this maintainer just want spread subjective stance quietly. I also dislike those Falun Gong's website and its believer, but the question is you shouldn't use your position to make choices for others. Even don't mention these tricks to users who trust this list. neohost also block extra domain but he make a declaration clearly and still provide non-extra list. I think that's the biggest difference between them.

**Comment by Mosney** [comment]
> 亲爱的中国用户们，对于这件事情你们什么看法？

In my view, because integrating multiple other upstream sources and maintain frequently, anti-AD still has itself's value as an AD list. That's the reason I tried to let maintainer make some change, failed obviously. 

I have two options here:

1. Like @ameshkov option.1, add some disclaimer to explain what those lists will do, for this instance, reference [repo's link](https://github.com/Mosney/anti-anti-AD) enough I think.

2.  Totally abandon it, turn to collect its upstream which only have single-purpose lists, It's almost equally effective. Just lose a little part which is these maintainer efforts.

**Comment by fire-dotcom** [comment]
Anyway they may follow something righteous for people and its not a fun. i have seen this behaviour in projects under restrictions placed saudi arabia, iran and few other countries.

>So it seems that at least two popular Chinese lists prefer to take some stance on political/religious issues in addition to their main purpose.
>>I see two options here:
>>Add a disclaimer in the UI that these lists may be blocking domains based on their authors' political/religious, or other preferences.

Add a disclaimer: This may includes domains considered as inappropriate by regional law and blocklist author.

**Comment by DandelionSprout** [comment]
I've stumbled across https://raw.githubusercontent.com/Licolnlee/AdBlockList/master/AdBlock, which seems promising at a surface glance.

**Comment by llacb47** [comment]
These are mostly not hosts lists, but here are some Chinese adblock lists:
```
https://wsgzao.github.io/post/adguard/
https://kbsml.com/2020/06/21/adguard%e8%bf%87%e6%bb%a4%e8%a7%84%e5%88%99/
https://github.com/otobtc/ADhosts
```

**Comment by hezhijie0327** [comment]
I combined an [AdFilter](https://github.com/hezhijie0327/AdFilter) ([Subscription](https://source.zhijie.online/AdFilter/master/adfilter_adblock.txt)) suitable for China, and extracted only the rules suitable for AGH (except Easylist, Easyprivacy, Adblock-nocoin-List and CoinBlockerLists, all of which are collected for Chinese websites; also remove the dead domain or host from it).

**Comment by Mosney** [comment]
> I've stumbled across https://raw.githubusercontent.com/Licolnlee/AdBlockList/master/AdBlock, which seems promising at a surface glance.

I follow this and find maintainer [says](https://licolnlee.icu/tools/) "Project has been included in the NeoDevHost Project. https://github.com/neodevpro/neodevhost" Looks we have many alternative lists for chosen.

**Comment by Mosney** [comment]
> > I've stumbled across https://raw.githubusercontent.com/Licolnlee/AdBlockList/master/AdBlock, which seems promising at a surface glance.
> 
> I follow this and find maintainer [says](https://licolnlee.icu/tools/) "Project has been included in the NeoDevHost Project. https://github.com/neodevpro/neodevhost" Looks we have many alternative lists for chosen.

Actually not many, same issue in Licolnlee/AdBlockList and neodevpro/neodevhost, they may all subject-pollute by same upstream. But @hezhijie0327 's repo looks good, have no extra irrelevant domain.

**Comment by ameshkov** [comment]
Please note that it's crucial for a list to be actively maintained so that there was a place where people could report issues, and they would be solved. Simple compilations of other existing lists do not fit this description.

Among all the lists, Anti-Ad still seems to be the only one that's really actively developed. NeoHosts is not as active, there's a bunch of unaswered issues in NeoHosts.

**Comment by Mosney** [comment]
Another issue none about this topic, when I discussing anti-AD in some community's group, many people mentioned this rule is too radical, sometimes functional domains are blocked as well. Although current maintainer are diligent enough to make up for it, most people will not (or don't know how) to report to maintainer, in my observe. Anyway, list only one recommend regional list not a good idea, especially this unique list not good enough, you may think about add some more option for users.

**Comment by hplee0120** [comment]
> Please note that it's crucial for a list to be actively maintained so that there was a place where people could report issues, and they would be solved. Simple compilations of other existing lists do not fit this description.
> 
> Among all the lists, Anti-Ad still seems to be the only one that's really actively developed. NeoHosts is not as active, there's a bunch of unaswered issues in their repo.

Yes, I used the anti-AD anti-advertising list, and then stopped using it, because the list is often incorrectly blocked and overly aggressive. Sometimes it will affect daily use. This list is more like a list tailored by the author for himself  . During this period of time, I have also tried other more suitable lists, but there is no progress for the time being. Most Chinese lists seem to be incompatible with ADH.

**Comment by ameshkov** [comment]
Should we add NeoHosts Basic or yHosts or both of them?

**Comment by Mosney** [comment]
> Should we add NeoHosts Basic or yHosts or both of them?

I prefer to add both, at least give users choice.

**Comment by DandelionSprout** [comment]
Based on research I did this morning, which I forgot to tell about because I've felt tired today: (+ = good; • = thing to keep in mind)

### yHosts
\+ Very large coverage.
\+ Also has support for Taiwanese sites.
\+ Contains entries that attempt to make PC trial periods never end, which I approve of... provided the entries actually work.
\+ No entries that'd break international sites that I could see.
• Has various entries that are used to block things on non-Chinese sites, e.g. `CNN` and `deviantART`
• Seems to block `ieonline.microsoft.com` for slightly unclear reasons. I approve of its blocking of `toolbar.msn.com`, however.

### NeoHosts Basic
\+ Fairly good coverage
\+ No entries that'd break international sites that I could see.
\+ Focuses entirely on PR-Chinese sites, with no chance of overlapping with e.g. English and Japanese lists.
• The list contains IPv4 and IPv6 entries for each domain, when only one of them would really be needed in AdGuard Home.

**Comment by guanhemeng** [comment]
> 这样看来，至少有两个受欢迎的中国人除了主要目的之外，还倾向于在政治/宗教问题上采取立场。
> 
> 我在这里看到两个选择：
> 
> 1. 在用户界面中添加免责声明，这些列表可能基于其作者的政治/宗教或其他偏好而阻止了域。
> 2. 不要将它们添加到“经过审查的”列表的列表中，而只保留单一用途的列表。
> 
> 欢迎提出任何意见，但是由于我们在谈论中文列表，所以我想了解一下中国用户对此的看法。
> 
> 亲爱的中国用户们，对于这件事情你们什么看法？
I think Chinese users should be given the right to choose. Not everyone is interested in politics and religion. Most people are not associated with blocked domains.

**Comment by ZeroClover** [comment]
neoHosts lacks the necessary maintenance, has not been updated for a long time, and has a high number of false positives, which I find unacceptable.

Besides, yHosts maintainers seem to use QQ (a mainland Chinese IM software) more than GitHub to receive feedback, which doesn't seem to be conducive to community feedback and problem-solving.

I agree with @ameshkov, and the point is that the maintainers of the list should actively maintain these rules, even if there are some unnecessary entries added because of their personal opinions, it is effortless to override them in an ADH deployment.

**Comment by ZeroClover** [comment]
@ameshkov According to the license agreement indicated by the maintainer of yHosts on README.md, it is necessary to contact the maintainer to obtain the authorization before adding yHosts to ADH.

> 此项目仅限于个人研究。
> 未经作者或维护小组同意，不得擅自用于商业活动或用于其他公共项目（包括但不限于嵌入APP，浏览器等）。
> 不得违反国家相关法律法规。
> 请于测试后24小时内删除。

@Mosney Based on the topic of this issue, I think yHosts is even more out of line with your needs, as the wiki for the project explicitly states that it will block content that is not an ad or tracker.

https://github.com/VeleSila/yhosts/wiki/%E9%83%A8%E5%88%86%E9%97%AE%E9%A2%98%E8%AF%B4%E6%98%8E

I tend not to add either of the neoHosts or the yHosts to ADH.

**Comment by Mosney** [comment]
> @Mosney Based on the topic of this issue, I think yHosts is even more out of line with your needs, as the wiki for the project explicitly states that it will block content that is not an ad or tracker.
> 
> https://github.com/VeleSila/yhosts/wiki/%E9%83%A8%E5%88%86%E9%97%AE%E9%A2%98%E8%AF%B4%E6%98%8E

@ZeroClover Note what he mentions at the beginning, 
> 新版数据已经将下面这部分数据放置在了moot文件夹，你们可以每次check以后不要合并这部分数据就可以了
> Means: The new version of the data has placed the following part of the data in the moot folder, you can check each time without merging this part of the data.

In fact,  yHosts final lists do not contain what is stated domain anymore. You can check those domains in the final list.

> But the problem with yHosts is apparently much more serious than the anti-AD problem mentioned in this issue. 

So that is not a problem. As license and agreement, just open an issue to request authorization, anti-AD's upstream may include yHosts cause https://github.com/privacy-protection-tools/anti-AD#special-thanks-to . But if you decide to keep anti-AD, yHosts will become unnecessary, the reason to add it only "give user choice right" left.

**Comment by ZeroClover** [comment]
@Mosney Are you sure that this repository contains the so-called "moot" directory?

https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts.txt

https://github.com/VeleSila/yhosts/wiki/%E6%95%B0%E6%8D%AE%E5%90%8D%E7%A7%B0%E5%8F%8A%E5%90%AB%E4%B9%89

I'm not aware of any other lists that don't contain these unnecessary entries.

**Comment by Mosney** [comment]
> @Mosney Are you sure that this repository contains the so-called "moot" directory?

Sure, it contained in the original repo, the new repo just clone that statement but change the old file/directory. See https://github.com/vokins/yhosts/tree/master/data/moot

**Comment by ZeroClover** [comment]
@Mosney 

Obviously, we can't do such complex operations in ADH.

Since the project only provides hosts files, not ADH syntax format, this also makes it difficult to simply remove unnecessary entries via the `@@` qualifier.

> In fact, yHosts final lists do not contain what is stated domain anymore. You can check those domains in the final list.

This makes no sense, vokins no longer maintain the project, and the new maintainer does not provide such files.

**Comment by Mosney** [comment]
@ZeroClover You are right, I double-checked yHosts list, found moot directory domain still show in final host.txt, I thought yHosts as same as anti-AD, both of them contain subjective content. I agree not add yHosts, yHosts as same as anti-AD and anti-AD include yHosts, so yHosts is no need to be added.

**Comment by Mosney** [comment]
Given the realities about Chinese regional filter, no subjective list lack maintain and good maintain list almost all contain subjective entries. I suppose this issue hard to resolve, maybe Chinese people born to deserve it, I have done with it.
AdGuardHome has to keep that list if they need a regional list. I think this issue may be closed if there is no more way to resolve those conflict.

**Comment by ameshkov** [comment]
Please reopen this issue or post to #1913 if there emerges any other notable and well-maintained Chinese filter list. So far it seems you're right, there's no Chinese filter list that does not try to block just the ads and trackers.
