### ISSUE TITLE
No internet connection after each power loss

### ISSUE THREAD

**Issue by adizag** [AdguardTeam/AdGuardHome#2149]
- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
0.103.3

* **How did you setup DNS configuration:**
router

* **If it's a router or IoT, please write device model:**
Router - Orbi, Adguard is running on RPI3b+

* **Operating system and version:**
Raspbian GNU/Linux 10 (buster), Kernel:Linux 5.4.51-v7+

### Expected Behavior
After power loss, the modem, router, and adguardhome (on RPI) are rebooted. The internet is working.

### Actual Behavior
Adguardhome is loaded and accessible, but there is no internet connection, only internal network.
I have to reboot the RPI running AGH in order to have the router get access to the internet.

### Screenshots
N/A

### Additional Information
Internet setup - only AGH is defined as DNS server.
AGH is the DHCP server as well.

**Comment by ameshkov** [comment]
I am not sure what could be the issue here, not enough details.

> but there is no internet connection

What do you mean? There are many reasons why there could be no internet connection, it would help to know what exactly is the reason in your case.

Also, try enabling verbose log in AdGuard Home and check for errors there:

1. [Configure](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) AdGuard Home to collect logs:
    * Specify `log_file`
    * Set `verbose` to `True`
2. Restart AdGuard Home and reproduce the issue

**Comment by adizag** [comment]
It is 75 MB.
How can I send it to you?

**Comment by ameshkov** [comment]
First of all, archive it (use zip or something like this).

You can send it to `devteam at adguard.com` - mention this issue in the email please.

**Comment by adizag** [comment]
Sent by mail.
TNX!

____________________________________________
"יש המטביעים את צרותיהם - ויש המלמדים אותן לשחות..."
"אין מקום שהוא רחוק מדי"

**Comment by ameshkov** [comment]
Hm, I don't see it. Plz try my personal email (am at adguard.com)

**Comment by adizag** [comment]
Just did.
Tell me if you got it?

בתאריך יום ד׳, 14 באוק׳ 2020, 14:38, מאת Andrey Meshkov ‏<
notifications@github.com>:

**Comment by ameshkov** [comment]
@adizag I did, thank you.

I suppose the issue is caused by this:
```
2020/10/09 11:19:28 376#9 [info] Couldn't find IPv4 address of interface eth0 &{Index:2 MTU:1500 Name:eth0 HardwareAddr:b8:27:eb:07:74:4a Flags:up|broadcast|multicast}
2020/10/09 11:19:28 376#9 [error] DHCP: Couldn't find IPv4 address of interface eth0 &{Index:2 MTU:1500 Name:eth0 HardwareAddr:b8:27:eb:07:74:4a Flags:up|broadcast|multicast}
2020/10/09 11:19:28 376#9 [error] Failed to initialize DHCP server, exiting
```

For some reason, AdGuard Home service is initialized too early, before your network is initialized.

I am not sure why, it is specified in AdGuard Home service that it needs to be initialized after network:
`After=syslog.target network-online.target`

Try inspecting your systemd services configuration, something is wrong with it.

**Comment by adizag** [comment]
@ameshkov 
it is already defined as you mentioned, so it didn't solve my problem...
`
[Unit]
Description=AdGuard Home: Network-level blocker
ConditionFileIsExecutable=/home/pi/AdGuardHome/AdGuardHome
After=syslog.target network-online.target

[Service]
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/home/pi/AdGuardHome/AdGuardHome "-s" "run"

WorkingDirectory=/home/pi/AdGuardHome



StandardOutput=file:/var/log/AdGuardHome.out
StandardError=file:/var/log/AdGuardHome.err
Restart=always
RestartSec=10
EnvironmentFile=-/etc/sysconfig/AdGuardHome

[Install]
WantedBy=multi-user.target`
