### ISSUE TITLE
Wrong DoT ServerName shown in auto-generated .mobileconfig files

### ISSUE THREAD

**Issue by pm2kjiagm** [AdguardTeam/AdGuardHome#2235]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [○] I am running the latest version
- [○] I checked the documentation and found no answer
- [○] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.104.0
* **How did you setup DNS configuration:**
  * .mobileconfig file
* **Operating system and version:**
  * iOS 14.1

### Expected Behavior

DoT ServerName in .mobileconfig file should not be with port number.

### Actual Behavior

The DoT .mobileconfig file auto-generated by AdGuard Home was provided with WEBUI port number.

### Screenshots

<details><summary>Screenshot:</summary>

![Snipaste_2020-10-29_22-47-29](https://user-images.githubusercontent.com/12817466/97582162-c6c19c00-1a38-11eb-8717-a497dffd621b.png)
![Snipaste_2020-10-29_22-43-59](https://user-images.githubusercontent.com/12817466/97582361-ff617580-1a38-11eb-9b3f-8693cac6326a.png)
</details>

### Additional Information

I think iOS rules does not allow custom port number for DoT in this time.

**Comment by ainar-g** [comment]
<p>Hello!&#x2003;We will fix the naming shortly, but&#xA0;please be aware
that,&#xA0;according
to&#xA0;<a href="https://tools.ietf.org/html/rfc7858#section-3.1">RFC&#xA0;7858</a>,
the&#xA0;default port must always be&#xA0;853:</p>

<blockquote>
<pre>   By default, a DNS server that supports DNS over TLS MUST listen for
   and accept TCP connections on port 853, unless it has mutual
   agreement with its clients to use a port other than 853 for DNS over
   TLS.  In order to use a port other than 853, both clients and servers
   would need a configuration option in their software.</pre>
</blockquote>

<p>So&#xA0;you will have to&#xA0;set the&#xA0;port manually in&#xA0;your
client's&#xA0;settings.</p>

**Comment by pm2kjiagm** [comment]
> Hello! We will fix the naming shortly, but please be aware that, according to [RFC 7858](https://tools.ietf.org/html/rfc7858#section-3.1), the default port must always be 853:
> 
> > By default, a DNS server that supports DNS over TLS MUST listen for
> >    and accept TCP connections on port 853, unless it has mutual
> >    agreement with its clients to use a port other than 853 for DNS over
> >    TLS.  In order to use a port other than 853, both clients and servers
> >    would need a configuration option in their software.
> 
> So you will have to set the port manually in your client's settings.

Thanks for reply.

In fact, my AdGuard Home sets port 853 for DoT. (It is shown in Screenshot No.1)
But, AdGuard Home generate a wrong .mobileconfig to specify port 3001.
I think iOS doesn't work correctly in this situation.

And according to Apple's document, I think iOS doesn't support a DoT server with custom port number in this time.
(https://developer.apple.com/documentation/networkextension/nednsovertlssettings/3552332-servername)

**Comment by ainar-g** [comment]
<p>@pm2kjiagm&#x2003;The&#xA0;latest version on&#xA0;the&#xA0;edge channel must
fix this issue.&#x2003;If&#xA0;it doesn't, please message us
with&#xA0;details.</p>
