### ISSUE TITLE
DHCP Static Leases not saved in config file

### ISSUE THREAD

**Issue by samusangio** [AdguardTeam/AdGuardHome#2313]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Problem Description

DHCP Static Leases are not saved in the main configuration file. When running adguard home in a docker container, the static lease configuration is lost when a new container is created e.g. after an upgrade

### Proposed Solution

Include DHCP static leases in the main yaml config file

**Comment by RonKhondji** [comment]
Static leases are in 'leases.db'. Copy that file to the new container.

**Comment by ameshkov** [comment]
@RonKhondji, thank you!

**Comment by swissmaster1** [comment]
I run adguard home in docker. I can't find leases.db and on every update of adguard home all my static leases are lost. What can I do to get the static leases beeing safed in leases.db?

**Comment by ChrLipp** [comment]
I had the same issue and the reason was that I mounted the wrong directories (I followed this tutorial: https://mariushosting.com/how-to-install-adguard-on-your-synology-nas/). I noticed my error when I looked at  https://registry.hub.docker.com/r/adguard/adguardhome/

concrete: I mounted
docker/adguard/data to /opt/adguardhome/work/data
instead of 
docker/adguard/work to /opt/adguardhome/work

Now I am testing if DHCP leases are saved :-D
