### ISSUE TITLE
Wrong blocking source at logging

### ISSUE THREAD

**Issue by grubeli** [AdguardTeam/AdGuardHome#2328]
If a domain is not blocked by local blocklists but by a upstream service (quad9, nextdns, cloudflare family, etc), "Query Log" tab shows that the domain is blocked by a list which is the last on my local list.

* **Version of AdGuard Home server:**
  * 0.104.1
* **How did you setup DNS configuration:**
  * Router
* **Operating system and version:**
  * Ubuntu 20.04

### Expected Behavior
Log that the domain is blocked (not found) by upstream service or similar error.

### Actual Behavior
Logging that the domain is blocked by the latest list on my local list, even if there is no such domain in my list.

### Screenshots
![image](https://user-images.githubusercontent.com/74614193/99420205-dc6a0900-28f4-11eb-9ca8-4587fba9cdc0.png)

### Additional Information
The domain is not blocked by my lists but NextDNS

**Comment by ameshkov** [comment]
> If a domain is not blocked by local blocklists but by a upstream service (quad9, nextdns, cloudflare family, etc), "Query Log" tab shows that the domain is blocked by a list which is the last on my local list.

Well, it is blocked by both NextDNS and AdGuard Home it seems.

You see, the status is "Blocked by CNAME or IP" so it means that AdGuard Home actually loaded DNS response from the upstream, and that's why you see it in NextDNS logs. Then AdGuard Home inspected the response and decided to block, that's why it is marked as blocked in our query log.
