### ISSUE TITLE
Blocking google causes android WiFi status issues

### ISSUE THREAD

**Issue by Iconology** [AdguardTeam/AdGuardHome#2356]
Hey there,
I'm trying to slowly move away from google, so added a block to google.com via custom rules but it is causing an android phone (Galaxy s8) WiFi to show as internet may be unavailable. I've whitelisted every other requests being blocked so the only domain being blocked is google.com. 

I'm curious if this is an unintentional bug, or why one would correlate with the other, as it seems quite random for it to effect WiFi connectivity status. It's purely cosmetic, WiFi still functions just has the error on the symbol at the top and error code in notifications.

**Comment by ameshkov** [comment]
I'd suggest recording Android logs and trying to figure out what's causing it from there.

Here's how you can capture logs on Android:
https://developer.android.com/studio/debug/bug-report

Look for huge txt files in the "bug report", it'll contain the log.
Additionally, it's possible to enable debug logging via Android developer options.

**Comment by michaelb-ae** [comment]
@Iconology it's normal because (i don't remeber whats the one who check that) but Google check if you are connected to internet with their domain but you can find it with the adb command

`settings get global captive_portal_server`
modifying it with your own check address
`settings put global captive_portal_server addresse.here`
or disable it totally
`settings put global captive_portal_detection_enabled 0`
`settings put global captive_portal_mode 0`

**Comment by EntropySmoke** [comment]
Use ADB Shell to input the following commands in this order:
settings put global wifi_watchdog_background_check_enabled 0
settings put global ntp_server time.cloudflare.com
settings put global captive_portal_mode 0
settings put global wifi_watchdog_on 0
pm disable com.android.captiveportallogin

OR you can try blacklisting google.com, but whitelisting gstatic.com or whitelisting only connectivitycheck.gstatic.com. What sucks is that VPN apps do not prevent Android phones from contacting those domains when Android phones go into sleep mode. It defeats the point of a VPN...
