### ISSUE TITLE
custom block page

### ISSUE THREAD

**Issue by chenks** [AdguardTeam/AdGuardHome#2373]
How can i add a custom block page on my AdGuard Home when it blocks website from filters?
at the moment all it does it display the stock browser error page, which doesn't tell you that adguard blocked it.

settings > DNS Settings > DNS server configuration > Block mode > IP address

not sure if there is how you would do it, but entering an IP address of a webserver (for example) doesn't result in a page being displayed.

**Comment by ainar-g** [comment]
<p>Hi,&#xA0;what&#xA0;kind of&#xA0;error page does the&#xA0;browser show
exactly?&#x2003;Setting a&#xA0;custom IP in&#xA0;<i>DNS Settings</i> works
for&#xA0;me.&#x2003;Perhaps it shows a&#xA0;ceritficate error?&#x2003;Also, you
might be interested
in&#xA0;<a href="https://github.com/AdguardTeam/AdGuardHome/issues/454#issuecomment-548269055">these</a>
settings if&#xA0;you're using safe browsing or&#xA0;parential
blocking&#xA0;features.</p>

**Comment by chenks** [comment]
here's an example. if i set to block "mail.ru", the default error page i get is

This site can’t be reachedCheck if there is a typo in mail.ru.
DNS_PROBE_FINISHED_NXDOMAIN

if i set it to point to my local webserver (192.168.50.2) i get

Your connection isn't private
Attackers might be trying to steal your information from mail.ru (for example, passwords, messages or credit cards).
NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by ainar-g** [comment]
<p>That's&#xA0;the&#xA0;certificate error, and&#xA0;that is the&#xA0;correct
behaviour from&#xA0;the&#xA0;browser's side.&#x2003;The&#xA0;browser expects
to&#xA0;see the&#xA0;<i>Mail.RU</i> certificate there, but&#xA0;since
the&#xA0;IP is different, the&#xA0;browser warns you that&#xA0;something's
wrong.&#x2003;You can confirm that by&#xA0;doing the same
to&#xA0;a&#xA0;non-HTTPS websire, for&#xA0;example&#xA0;<a
href="http://neverssl.com/">NeverSSL.COM</a>.</p>

<p>As&#xA0;for&#xA0;redirecting to&#xA0;a&#xA0;path, as&#xA0;far
as&#xA0;I&#xA0;know this is not&#xA0;possible to&#xA0;do over&#xA0;DNS,
so&#xA0;you're better&#xA0;off setting your server to&#xA0;serve
the&#xA0;required page on&#xA0;every&#xA0;path.</p>

<p>Feel&#xA0;free to&#xA0;reopen, if&#xA0;you think we've
missed&#xA0;something.</p>

**Comment by chenks** [comment]
so because my webserver forces HTTPS (which all should be doing) i can't use this feature?
i can't set my webserver to server the page on every path as it's an actual live webserver.

**Comment by ainar-g** [comment]
<p>No,&#xA0;that's how&#xA0;HTTPS works.&#x2003;You're trying to&#xA0;access
<i>Mail.RU</i>, so&#xA0;the&#xA0;browser expects to&#xA0;see the&#xA0;correct,
valid certificate issued by&#xA0;a&#xA0;known CA for&#xA0;<i>Mail.RU</i>,
but&#xA0;your server doesn't have that certificate, so&#xA0;the&#xA0;browser
shows the&#xA0;error.</p>

<p>You&#xA0;can still configure your server to&#xA0;look
at&#xA0;the&#xA0;<code>Host</code> header, and,&#xA0;if&#xA0;the&#xA0;header
doesn't match the&#xA0;server's actual host, show the&#xA0;block&#xA0;page.</p>

**Comment by chenks** [comment]
yes i know how HTTPS works, but the point i'm getting as it that maybe adguard should have the option to provide it's own custom block page, so you the end-user knows that the page has been blocked on purpose, rather than a vague browser error page which could result in support calls being received.

**Comment by afi-dev** [comment]
Hello, I agree with chenks and I am disappointed that there is no page like for dns such as Cisco Umbrella or NextDNS. 😢 It would be interesting to integrate it in a future update of Adguard Home.

**Comment by quaintdev** [comment]
I may be wrong but the way this works is

your request -> adblock home -> actual server -> sends right cert -> your browser

In case of block scenario

your request-> adblock home -> request is not allowed -> can't get right cert -> your browser shows https error

You get response from your local server not actual site so browser will SSL report error. This is exactly how it should be because if it isn't then I can't be 100% sure whether the content is coming from my remote site or someone else is sitting in the middle.

**Comment by JReming85** [comment]
Just to add onto this, Pihole will do the same if its a HTTPS page.  You can only view if its trying to get the HTTP version.

You can however have this but requires you to setup a "content filtering"/mitm proxy.  Downside is it can break a lot of things, but give you a lot more control to where you can edit html/js on websites and inject new content.
