### ISSUE TITLE
Support multiple matched rules in the UI

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#2451]
During the work on #2102 we've added the ability to return multiple matched rules in the `GET /filtering/check_host` and `GET /querylog` _HTTP_ APIs.  Now we need to support that on the frontend.

**Comment by ameshkov** [comment]
Here's what we should do:

1. Use `Rule` only when `Rules` is not set.
2. Change the "Rule:" field in the filtering log (see the description below)
3. Remove the "Filter:" field (it's now included in the "Rules:")
4. Change the way we print filter names
5. Change the "Check the filtering" output

#### Rules output should now look like this:

https://uploads.adguard.com/up04_AdGuard_Home_gbjjm.png
![image](https://user-images.githubusercontent.com/5947035/102475262-b73ef680-406a-11eb-9c29-6b453a8fcda2.png)

**Note that the rules are grouped by the filter name**

Use the very same layout in the "Check the filtering" block.

#### "Response" column in the query log

Since there may be multiple filter lists now, just put a comma-separated list of filter lists there:
![image](https://user-images.githubusercontent.com/5947035/102475641-2c123080-406b-11eb-8324-1d8c7f093397.png)

If for some reason there are no rules in the query log item, fallback to the "elapsed" value there.

**Comment by ameshkov** [comment]
@ArtemBaskal one more thing. Where there're no rules, you shouldn't print "Rule(s)" at all:

![image](https://user-images.githubusercontent.com/5947035/103206260-81bcc780-490c-11eb-8d6c-c34c9f3dd26d.png)
