### ISSUE TITLE
OpenWRT version needs shorter query log retention options due to free space limitations

### ISSUE THREAD

**Issue by egalitarian** [AdguardTeam/AdGuardHome#2504]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description

The smallest query logs retention setting of 24h still creates a log far too big for most OpenWRT devices filling up all of the available space.

### Proposed Solution

Adding option for 1h or any other smaller than 24h would allow to check all latest queries and still be of some use when debugging problems.

### Alternatives Considered

An alternative would be to stop logging altogether and just start it from when you debug things but that would be more inconvenient.

**Comment by emlimap** [comment]
Another option that would be good to have rather than completely disable logging is to have limited in memory logs. This feature would be useful to extend the lifetime of sd card on SBC's like Raspberry Pi by not writing any logs to disk but have enough logs to troubleshoot blocked domains. Amount of logs held in memory can be set by user.

There is already a parameter `querylog_size_memory` which set the number of logs to queue up before it writes to disk. We could use this but not write to disk when logging is completed disabled

**Comment by ameshkov** [comment]
> Another option that would be good to have rather than completely disable logging is to have limited in memory logs

As I recall, that's exactly what happens when `querylog_file_enabled` is set to `false`

**Comment by agneevX** [comment]
Can this be documented in Raspberry Pi install instructions, @ameshkov? Would help users to a great extent, thanks.

**Comment by EugeneOne1** [comment]
We'll close the issue for now.  Please, feel free to reopen it if you'll face any problems with it.
