### ISSUE TITLE
#2563

### ISSUE THREAD

**Issue by brian31405** [AdguardTeam/AdGuardHome#2564]
> Not really.
> 
> 
> 
> However, you can simply add `pizzaseo.com` to the list of "Disallowed domains" in DNS settings. This way AGH will simply drop queries from such clients and they won't spam your stats.
> 
> 
> 
> Here's a list of the most popular domains used by them:
> 
> ```
> 
> *dot199q1w2e3rty.*
> 
> version.bind
> 
> id.server
> 
> hostname.bind
> 
> *.tstng.net
> 
> pizzaseo.com
> 
> 5hz.org
> 
> 1x1.cz
> 
> dd0s.ga
> 
> hitnslab.cn
> 
> *.hitnslab.cn
> 
> 67b.org
> 
> ```

Ameshkov:
  I think you misunderstand my question, I mentioned that there's many wilful clients requesting "pizzaseo.com".
About 20 request are sent to my server per second. All of them are sent by different ip addresses. I ment to block clients who make this request because every time I block them they came back with another ip address

__Originally posted by @brian31405 in https://github.com/AdguardTeam/AdGuardHome/issues/2563#issuecomment-760813470__

**Comment by ameshkov** [comment]
You need not open a new issue for that, we could continue this in the original one.

I did understand, and we don't have it in the plans.

Instead of that, we have a different option -- setting a list of "disallowed domains" (don't confuse it with blocking domains), which effectively prevents all these queries from being processed. 

These clients are not likely to send different queries, they just spam you with the same domain all the time, and disallowed domains solves this issue.
