### ISSUE TITLE
Restrict the access to the private hosts from the external networks

### ISSUE THREAD

**Issue by EugeneOne1** [AdguardTeam/AdGuardHome#2889]
Our autohosts feature works for any client for now.  But just like in #2704, it's obvious that the external clients shouldn't be able to resolve such hosts.

**Comment by EntropySmoke** [comment]
This issue is so confusing... Are you saying that random people can connect to my local AdGuard Home device from WAN and use it as a DNS resolver? I do set my local AdGuard Home IP for WAN DNS IP address to make sure it filters all outbound DNS traffic, but I it to filter traffic only for local clients, not for someone from WAN.

**Comment by ainar-g** [comment]
@EntropySmoke, this issue is about resolving of automatic hosts (the `.lan` ones) in private networks.  AdGuard Home won't accept external queries unless you configure it to listen on an externally visible address or `0.0.0.0`.
