### ISSUE TITLE
autohost_tld: fritz.box  - not starting up

### ISSUE THREAD

**Issue by kultfigur** [AdguardTeam/AdGuardHome#2961]
v0.106.0-a.126+b3f6592a
I set autohost_tld in AdGuardHome.yaml to fritz.box  (the default domain name of all Fritz-Box routers)
AdGuardHome not reachable anymore

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:*
* v0.106.0-a.126+b3f6592a
* **How did you install AdGuard Home:**
  Github releases, etc.
* **How did you setup DNS configuration:**
 Unbound on 127.0.0.1:5335
* **If it's a router or IoT, please write device model:**
  Raspberry Pi 4 Model B) 
* **CPU architecture:**
  ARM 
 **Operating system and version:**
  Raspbian
  

### Expected Behavior
AdGuardHome coming up after a reboot 

### Actual Behavior
AdGuardHome not reachable

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ainar-g** [comment]
Hi, and thank you for the report.  Currently, the autohost TLD is expected to be a top-level domain, so second-level domains aren't supported.

@ameshkov, should we allow any level in that setting?  Should we also rename it into something like `autohost_namespace`?

**Comment by kultfigur** [comment]
Would be nice. I thought I could replace these dns settings with it. 

# resolve local 
[/168.192.in-addr.arpa/]192.168.178.1
[/fritz.box/]192.168.178.1

**Comment by ameshkov** [comment]
> Would be nice. I thought I could replace these dns settings with it.

These aren't needed anymore anyway since PTR resolution is done with the local resolver anyway.

> @ameshkov, should we allow any level in that setting? Should we also rename it into something like autohost_namespace?

I am not entirely sure about it.

**Comment by kultfigur** [comment]
But without this line [/fritz.box/]192.168.178.1
my browser never resolves http://fritz.box 
That's why I thought autohost_tld was made for it

**Comment by ainar-g** [comment]
We'll see if we can do this during the current development cycle.  I will write if we have any updates.

**Comment by ainar-g** [comment]
@kultfigur, it turned out that this feature was easier to implement than we initially thought.  It should be available as of snapshot `v0.106.0-a.132+d83091fc` on the edge channel.  On restart, the name of the parameter will be automatically changed from `autohost_tld` to `local_domain_name` to reflect the change.

Can you please check if the new feature works for you?

**Comment by kultfigur** [comment]
Wow, that was fast  I have the latest version now and see that the parameter is named local_name now, but even after a restart the value is still "lan"


![26BD0A3F-45DB-4C75-B899-A33F04F9DA19](https://user-images.githubusercontent.com/82587581/114911327-311b9c80-9e1f-11eb-98df-1895ba6a0561.jpeg)

#

**Comment by kultfigur** [comment]
oh, what dumb I am. I have to change it to fritz.box manzally. Somehow I thought it will cgange automatically … Will test now.

**Comment by kultfigur** [comment]
Ok, here my results.  I set everything accordingly, uncommented my old dns settings, restarted, cleared the browser cache, but Safari and also chrome on Windows 10 won't open http://fritz.box 


![23906D6A-547D-4746-80F8-2E5F7FE8F157](https://user-images.githubusercontent.com/82587581/114913972-139c0200-9e22-11eb-8664-4cf82163473b.jpeg)
![85BF9F11-E545-4D59-8C0E-F4F541F57C1A](https://user-images.githubusercontent.com/82587581/114913976-14cd2f00-9e22-11eb-9ad1-803c98d9ae68.jpeg)

![A6034A98-7F31-4C29-9E45-D11A6966E62A](https://user-images.githubusercontent.com/82587581/114913952-10a11180-9e22-11eb-9b34-08ff3cd24d13.jpeg)se
![B8E75A9A-E482-4B84-AF3D-C7192D24CE4F](https://user-images.githubusercontent.com/82587581/114913954-1139a800-9e22-11eb-8286-762583b424b3.jpeg)t 
![48BB52D8-CCBF-4E6E-B520-F63AAC62ADE3](https://user-images.githubusercontent.com/82587581/114913956-1139a800-9e22-11eb-8cb0-346f19dc38c3.jpeg)l
![F1C9DCF6-57B4-4B49-8AFC-33A6185A94C6](https://user-images.githubusercontent.com/82587581/114913960-11d23e80-9e22-11eb-84ae-ce8e3597d1b9.png)
![E21CFBC5-76A9-4D5E-8F5B-4B76E3734950](https://user-images.githubusercontent.com/82587581/114913964-126ad500-9e22-11eb-9875-0c19dcda0537.jpeg)





![40235075-39C0-4E48-8682-B33EBA4B3DA8](https://user-images.githubusercontent.com/82587581/114913937-0d0d8a80-9e22-11eb-9b64-d10d6f97a8b2.jpeg)

**Comment by kultfigur** [comment]
Ok, here my results.  I have set everything accordingly, uncommented my old dns settings, cleared my wlan leases, cleared the browser cache, but still Safari and Chrome on W10 won't open http://fritz.box

![9FE76C30-95A8-40EC-B65F-5284E7534879](https://user-images.githubusercontent.com/82587581/114914590-c53b3300-9e22-11eb-8f69-dd04029a169c.jpeg)
![00D238E8-6F04-4EB6-A34E-D88F0CF5B3BE](https://user-images.githubusercontent.com/82587581/114914630-d6843f80-9e22-11eb-9b6e-85f44ff080ec.jpeg)
![9729D519-9099-46F9-9574-0E1F8D6945B9](https://user-images.githubusercontent.com/82587581/114914685-e865e280-9e22-11eb-9d1c-41266f46c671.jpeg)

**Comment by ainar-g** [comment]
I think there is a misunderstanding here.  `fritz.box` is now the domain name under which the other machines in your networks are found.  That is, if you have a machine called `myphone`, and it got its IP from AdGuard Home's DHCP server, you can now access it using the host `myphone.fritz.box`.  `local_domain_name` has nothing to do with the address of the router in this case.

https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP#autohosts

**Comment by kultfigur** [comment]
ok, understood.  AdGuard is not my DHCP server, that is the Fritz.box router.  But nevertheless, why are the browser requests  for fritz.box send upstream? And not to the private dns server?
![BB98AF29-CF75-4091-8F3E-DD472CEBE2D2](https://user-images.githubusercontent.com/82587581/114917184-f406d880-9e25-11eb-9d12-a69ebc577f2b.jpeg)

**Comment by ainar-g** [comment]
Because currently we only consider hostnames of the form `*.fritz.box` to be local to the network and not `fritz.box` itself.  We'll see if we can make it work that way as well in an acceptable time frame.  Please keep the issue open.

In the meantime, writing something like:

```none
192.168.178.1      fritz.box
```

Into the `/etc/hosts` file on the machine where AGH is started should make `http://fritz.box` work for clients.  (Assuming your router has the address `192.168.178.1`.)  The upstream rule for `fritz.box` should also be kept until we resolve this.

**Comment by ainar-g** [comment]
After considering the issues and the system more thoroughly, I think there was a bit of confusion here:

1.  The local domain name feature currently only makes sense when AGH is the DHCP servers of the network.  If AGH is not the DHCP server, it will simply respond with `NXDOMAIN` to all such queries.  So perhaps it's currently better that you **don't** set your `local_domain_name` to `fritz.box`.

2.  Your custom upstream rule seems perfectly fine for the issue at hand.  Since AGH is not the DHCP server in your case, using a custom upstream for the requests that you know are local is exactly what you would want.  At least with AGH's current feature set.

The two enhancements we can make in a future version are:

1.  If AGH receives a query about a host in the local domain, and AGH doesn't know anything about the host, perhaps it should forward the query to private DNS resolvers.  That would probably make your setup work without the custom upstream rule as long as you set the router as your private DNS resolver.

2.  Perhaps we should also make the runtime clients accessible using the local domain.  On your screenshot I can see that AGH actually does know about `fritz.box` and the other machine thanks to AGH's rDNS feature.

We'll look into these enhancements further.  In the meantime, does keeping the custom upstream rule and changing the `local_domain_name` to something else (for example, the default value, `lan`) make your system work better?

**Comment by kultfigur** [comment]
Hi,

thank you very much, I appreciate your efforts.  Yes, maybe there are different ideas in our heads what the autohost_tld parameter is all about.  What I simply want, after installing AGH, is reaching my local devices via their IP and their names. Including my router on http://fritz.box. Like before I installed AGH. Currently it's only possible when I add  these two rules to AGH dns settings:
[/168.192.in-addr.arpa/]192.168.178.1
[/fritz.box/]192.168.178.1
With those two rules everything is fine. So there is no real issue on my side. But, as you say, AGH already has all the necessary information about my local devices and could do without those extra rules. Would make it easier for the users.

**Comment by ainar-g** [comment]
@kultfigur, are you absolutely sure that the first rule is still required?  The second rule will have to stay for a while.

**Comment by jkreileder** [comment]
For me PTR resolution works fine without extra rules (IPv4 and 6). But I also ran into the same problem, i.e. I also tried replacing [/<local domain>/]<private ns> by setting local_domain_name.  Maybe the documentation should be made clearer here.

**Comment by ainar-g** [comment]
Thank you all for the input!  The documentation definitely needs improvement.  I filed #3003 as an issue for these improvements.  We'll continue keeping possible changes in mind.  I'll close this issue for now.
