### ISSUE TITLE
I see incredible speed differences with Security web features

### ISSUE THREAD

**Issue by bryshaw** [AdguardTeam/AdGuardHome#3084]
With this feature on my average is ~800ms with it off it is ~10ms

What is this feature? And what do I loose with that setting turned off?

**Comment by ainar-g** [comment]
Hello!  Do you mean the safe browsing one (the “Use AdGuard browsing security web service” checkbox on the “General settings” page) or the safe search one (“Enforce safe search”)?  Also, can you please provide [verbose logs] showing the slow queries?  Thanks!

[verbose logs]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by ameshkov** [comment]
> With this feature on my average is ~800ms with it off it is ~10ms

Probably, your connection to AdGuard DNS is not stable since we use it to do browsing security lookups.

> What is this feature? And what do I loose with that setting turned off?

AdGuard Home checks with our malicious website's database before making a query.
It's not mandatory and you can use some blocklist locally instead of using it so don't worry, it can be replaced.
