### ISSUE TITLE
Defect: Blocked Services are not being blocked

### ISSUE THREAD

**Issue by Raeth666** [AdguardTeam/AdGuardHome#3139]
The “Blocked Services” functionality is not working (under Filters>Blocked Services). I can select services to block (e.g. Facebook) but after saving the settings, the services selected for blocking are still reachable (even after giving AdGuard some time to processes the new settings). I assume this shouldn’t be possible, can you help?

Running the latest version of AdGuard v0.106.2 on a RaspberryPi 4B, with latest Raspberry OS.

**Comment by ainar-g** [comment]
Hello.  We cannot reproduce this issue.  Did you add any custom settings for the client?

**Comment by Raeth666** [comment]
Hi, I'm new at this so maybe you can elaborate on what exactly you mean by custom settings? I configured the client during setup to my network (set IP etc). I don't consider that customization of settings but maybe it is?

**Comment by ameshkov** [comment]
Note that some apps (FB, whatsapp) may cache the IP address and blocking on the DNS level would take quite some time to kick in.

**Comment by Raeth666** [comment]
> Hello. We cannot reproduce this issue. Did you add any custom settings for the client?

Haven’t heard from you yet. Please elaborate on your question and let me know what you need to resolve this.

**Comment by Raeth666** [comment]
> Note that some apps (FB, whatsapp) may cache the IP address and blocking on the DNS level would take quite some time to kick in.

Yes, I’m aware. It’s been a couple of days and still the blocking doesn’t work.

**Comment by ainar-g** [comment]
@Raeth666, hello again.  I don't know why the issue is closed.  But please add the following information to help us identify the problem:

1.  My question about clients was basically this: did you go to the _Settings_ → _Client settings_ page and set up any clients?
1.  How did you install AdGuard Home?
1.  How did you check if the service is blocked?  Can you provide a hostname that still gets resolved?
1.  Can you [configure] AdGuard Home to collect logs by setting  `verbose` to `true` and post the logs here as an attachment?

Thanks!

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by Thoroslives** [comment]
I am getting the same issue.

Services are blocked when accessing the URL directly, e.g. facebook.com, instagram.com but when accessed thorugh the app they work as if they are not blocked. i have flushed dns on all devices and checked settings. 
I have checked and ensured all dns servers are set to the primary so there is no fallback.

Any help would be appreciated

**Comment by Thoroslives** [comment]
> <img alt="@Thoroslives" width="40" height="40" src="https://avatars.githubusercontent.com/u/78023877?s=80&amp;v=4">

UPDATE

Fixed, i had Blocking mode set to REFUSED, tried NXDOMAIN didnt work. Switched back to Default and now its working.
