### ISSUE TITLE
Raccourci défectueux

### ISSUE THREAD

**Issue by fafa77** [AdguardTeam/AdGuardHome#3143]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by fafa77** [comment]
Bonjour,
Le port lors du lancement reste en 6052 et ne fonctionne donc pas.
Nous sommes obligés de passer par un raccourci du navigateur pour le lancer.
Merci.

**Comment by ainar-g** [comment]
Hello.  I'm sorry, we cannot infer the issue from the provided information.  Please fill the whole issue template, in any  language, and also add the following information:

1.  Is 6052 the port of the web interface, DNS, or something else?
2.  What exactly is the “shortcut” that is mentioned?  Are you sure that your issue is with AdGuard Home and not one of the other products?

* * *

(Traduction automatique.)

Bonjour.  Je suis désolé, nous ne pouvons pas déduire le problème à partir des informations fournies.  Veuillez remplir l'intégralité du formulaire de problème, dans n'importe quelle langue, et ajoutez également les informations suivantes :

1.  Est-ce que 6052 est le port de l'interface web, _DNS_, ou autre chose ?
2.  Quel est exactement le "raccourci" mentionné ?  Êtes-vous sûr que votre problème concerne _AdGuard Home_ et non l'un des autres produits ?
