### ISSUE TITLE
Pause internet function webpage

### ISSUE THREAD

**Issue by Final-Hawk** [AdguardTeam/AdGuardHome#3161]
### Prerequisites

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description
It would be awesome to have the ability to pause the internet (block dns requests) of a device and have a webpage show. This is already  possible, but it doesn't show a webpage

### Proposed Solution
Add a page that shows a "your device has been paused/blocked" when i client is blocked. Similar the malware detected page, just with different wording

**Comment by ainar-g** [comment]
Sounds like a duplicate of #2823?

**Comment by Final-Hawk** [comment]
> 
> 
> Sounds like a duplicate of #2823?

Not really, i was more asking for when a device is blocked using the button on the main page, all web traffic will redirect to an adguard page saying the device has been blocked. This would  look almost exactly like the current malware detected page, just with some different wording. Also sorry for my crappy explanation, it has been edited.
***
I really should create a separate issue for this, but is it intentional that the block client function on the main page doesn't show when the client is identified by the client id for DNS-over-HTTPS

Thanks

**Comment by ainar-g** [comment]
> I really should create a separate issue for this, but is it intentional that the block client function on the main page doesn't show when the client is identified by the client id for DNS-over-HTTPS

Yes, please create a separate issue about that.  Please also fill the whole issue template and attach a screenshot, if you can.

> Not really, i was more asking for when a device is blocked using the button on the main page, all web traffic will redirect to an adguard page saying the device has been blocked. This would look almost exactly like the current malware detected page, just with some different wording.

That probably won't be possible, because the way that blocking currently works in AGH is that our DNS server drops the request *completely*.  It won't even show up in the query logs, because it doesn't even reach any internal processing.  If you do want to process it and replace the DNS result with a different address, you can use custom filtering rules with the [`$dnsrewwrite`] modifier.

[`$dnsrewwrite`]: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#dnsrewrite

**Comment by Final-Hawk** [comment]
I see. Thanks
