### ISSUE TITLE
Document ways to make AGH show a custom block page

### ISSUE THREAD

**Issue by mbrking** [AdguardTeam/AdGuardHome#3176]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Feature request

hello adguardHome team,

Can you possibly add a feature so that ADGuard Home users can create a custom page where to see which page was blocked.
For example, if Hulu.com is blocked, you can only see a blank page.
Would it be possible to create your own simple custom page with "this page What blocked by ADGuard Home" Or Something Like That if someone in my network visit hulu.com?

Ty Guys for This Amazing Work

**Comment by ainar-g** [comment]
Hi.  The current way to do that is documented [here].  We really should document that on the Wiki, since these requests keep coming.

I'll relabel this issue as a documentation one, if you don't mind.  Thanks!

[here]: https://github.com/AdguardTeam/AdGuardHome/issues/454#issuecomment-548269055

**Comment by ameshkov** [comment]
We should probably mention on the documentation page that we're not going to implement a custom TLS pixel, users need to run nginx or something similar that would serve the custom block page.

The reason is that we're waiting for two RFC to be implemented in browsers, they'd allow us to provide custom block page without the need to mess with TLS certs etc.

1. Extended DNS errors would allow to specify the reason for blocking access: https://datatracker.ietf.org/doc/html/rfc8914 (see https://github.com/AdguardTeam/AdGuardHome/issues/2261)
2. DNS access denied error page: https://datatracker.ietf.org/doc/html/draft-reddy-dnsop-error-page-07

**Comment by DandelionSprout** [comment]
>*"The current way to do that is documented here. (…)"*

That link only explains how to replace the blocking pages for the malware and parental modules, not how to create a new one for normal blocking.

**Comment by ameshkov** [comment]
Yeah, we should also mention `Custom IP` blocking in the doc

**Comment by ainar-g** [comment]
We have now added the FAQ entry about a custom block page: <https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#customblock>.  Please feel free to open new issues if you think that the documentation there could improve.
