### ISSUE TITLE
Dockerfile does not have health check 

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#3290]
Continuation of #1426

There's no health check for Docker images.

This is how [Pi-hole](https://github.com/pi-hole/docker-pi-hole/blob/0954c9f3ddf421495cac1817c68cebe28c103260/Dockerfile#L55) does it:

```Dockerfile
HEALTHCHECK CMD dig +norecurse +retry=0 @127.0.0.1 pi.hole || exit 1
```

**Comment by agneevX** [comment]
Using `curl` for web UI:

```Dockerfile
HEALTHCHECK CMD curl -fs http://localhost:3000 -o /dev/null || exit 1
```

**Comment by ainar-g** [comment]
Unfortunately, it's not that straightforward.  AGH's initial HTTP API port is 3000, but the user can change it.  In fact, the port that we currently propose by default is 80.  And people can change it in the config file.  We could include some sort of a script that would read the config file and use that value, but definitely not in this release cycle.

**Comment by sachinwadhwa** [comment]
I have used following healthcheck in my compose file. Port 53 is most important for me (as I am not using DoH).

    healthcheck:
      test: "/bin/netstat -pant | /bin/grep 53"
      interval: 45s
      timeout: 30s
      retries: 3

**Comment by ameshkov** [comment]
DNS server is not working until the initial setup is finished

**Comment by agneevX** [comment]
Seems like a separate script is needed to accomplish this.

**Comment by lolgast1987** [comment]
I made something to do exactly that. Checks for the Setup to be done and if so, which port is configured for bind_port.

https://github.com/lolgast1987/adguard-unbound/blob/master/files/healthcheck.sh

**Comment by PeterDaveHello** [comment]
Can we at least accept to use maybe 53 port with nslookup or dig to do a basic health check? I'd like to send a pull request for it if it's acceptable. We could have some further improvement later, when the more complete and complex idea came up?

**Comment by PeterDaveHello** [comment]
My current healthcheck config using docker-compose:

https://github.com/PeterDaveHello/dnslow.me/blob/master/docker-compose.yml#L9-L14

```yaml
healthcheck:
  test: nslookup www.google.com || exit 1
  timeout: 5s
  interval: 60s
  start_period: 10s
  retries: 1
```

**Comment by JaneJeon** [comment]
For those of us using DNS-over-HTTPS, what is the best option here?

**Comment by PeterDaveHello** [comment]
> For those of us using DNS-over-HTTPS, what is the best option here?

https://github.com/PeterDaveHello/dnslow.me-uptime/blob/master/.upptimerc.yml#L8

You can use http get method to perform a query like https://dnslow.me/dns-query?dns=AAABAAABAAAAAAABBmRuc2xvdwJtZQAAAQABAAApAgAAAAAAAFoADABWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by JaneJeon** [comment]
What in the world is the random string of letters in the ?dns= query and how do I construct it myself?

**Comment by PeterDaveHello** [comment]
> What in the world is the random string of letters in the ?dns= query and how do I construct it myself?

It's not random, I just do it the lazy way, use any DoH client to send a http get query to a https server, then you can find it in the access log.

**Comment by ookangzheng** [comment]
Another example to perform `www.example.com` 

```
https://doh-jp.blahdns.com/dns-query?dns=AAABAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB
```

**Comment by alexsannikov** [comment]
As an example: Node Red docker container uses healthcheck....

**Comment by EugeneOne1** [comment]
Hello again, @agneevX, and everyone here.  The latest edge build now uses implements the healthcheck via Dockerfile.  Could you please check if it works for you?

**Comment by stavros-k** [comment]
@EugeneOne1 
Hello, healthcheck does not account for the `--port` flag when it's not yet run through the wizard.
https://github.com/AdguardTeam/AdGuardHome/blob/132ec556dc206c7f4453b194d58112944b5b96db/docker/healthcheck.sh#LL25C27-L25C31

**Comment by EugeneOne1** [comment]
@stavros-k, thanks for the feedback.  Actually, the current implementation expects the port `3000`, specified in the official Dockerfile, to be used for installation.  Since this use case exists, we've filled the separate issue (#5645) about taking custom ports specified via command-line options into account.

Are there any other issues happened?

**Comment by leo15dev** [comment]
> @stavros-k, thanks for the feedback. Actually, the current implementation expects the port `3000`, specified in the official Dockerfile, to be used for installation. Since this use case exists, we've filled the separate issue (#5645) about taking custom ports specified via command-line options into account.
> 
> Are there any other issues happened?

If the health check status showing unhealthy, it will produce a lot of zombie process.

e.g. 
root      119494  0.0  0.0      0     0 ?        Z    19:01   0:00 [ssl_client] <defunct>
root      119495  0.0  0.0      0     0 ?        Z    19:01   0:00 [ssl_client] <defunct>
root      119939  0.0  0.0      0     0 ?        Z    19:01   0:00 [ssl_client] <defunct>
root      119956  0.0  0.0      0     0 ?        Z    19:01   0:00 [ssl_client] <defunct>
root      120419  0.0  0.0      0     0 ?        Z    19:02   0:00 [ssl_client] <defunct>
root      120420  0.0  0.0      0     0 ?        Z    19:02   0:00 [ssl_client] <defunct>
root      120900  0.0  0.0      0     0 ?        Z    19:02   0:00 [ssl_client] <defunct>
root      120901  0.0  0.0      0     0 ?        Z    19:02   0:00 [ssl_client] <defunct>
root      121332  0.0  0.0      0     0 ?        Z    19:03   0:00 [ssl_client] <defunct>
root      121341  0.0  0.0      0     0 ?        Z    19:03   0:00 [ssl_client] <defunct>
root      121816  0.0  0.0      0     0 ?        Z    19:04   0:00 [ssl_client] <defunct>
root      121817  0.0  0.0      0     0 ?        Z    19:04   0:00 [ssl_client] <defunct>
root      122284  0.0  0.0      0     0 ?        Z    19:04   0:00 [ssl_client] <defunct>
root      122285  0.0  0.0      0     0 ?        Z    19:04   0:00 [ssl_client] <defunct>
root      122792  0.0  0.0      0     0 ?        Z    19:05   0:00 [ssl_client] <defunct>
root      122793  0.0  0.0      0     0 ?        Z    19:05   0:00 [ssl_client] <defunct>
root      123281  0.0  0.0      0     0 ?        Z    19:05   0:00 [ssl_client] <defunct>
root      123282  0.0  0.0      0     0 ?        Z    19:05   0:00 [ssl_client] <defunct>
root      123721  0.0  0.0      0     0 ?        Z    19:06   0:00 [ssl_client] <defunct>
root      123722  0.0  0.0      0     0 ?        Z    19:06   0:00 [ssl_client] <defunct>
root      124209  0.0  0.0      0     0 ?        Z    19:07   0:00 [ssl_client] <defunct>

all above  zombie process was found  after upgrading the edge container  at   19:01 by watchtower.

Thank you!

**Comment by EugeneOne1** [comment]
@leo15dev, what exact version are you using?  We've investigated the case and have some assumptions.  The Docker container runs the command specified by the `ENTRYPOINT` under PID=1.  In UNIX systems this exact process is intended to handle orphan processes (and zombies too) and is usually occupied by some init system.  In case of Docker container, this PID is occupied by AdGuard Home itself, so these processes are becoming its children and stay in the process table forever due to lack of appropriate handling.

However, we've only been able to reproduce this "process zombification" requesting the web UI by `wget` with HTTPS scheme which triggered the `ssl_client`.  We've been using the HTTPS scheme for these requests in the initial version of our healthcheck script, but the current implementation avoids it, so it's not really clear what calls `ssl_client` now.

**Comment by EugeneOne1** [comment]
@leo15dev, well, it shouldn't be the case, since the health check script runs inside the same container it checks.

Since the `v0.108.0-a.493+2eb3bf6e` is 1 revision ahead of the one, which started avoiding HTTPS, I should ensure, if the issue still relevant?  If these zombies are present after the update?

**Comment by leo15dev** [comment]
I think AdGuard Home, version v0.108.0-a.495+f191cb07 fixed it, thank you!

**Comment by EugeneOne1** [comment]
@leo15dev, great, thanks for your help.  I suppose, the issue can be closed for now.  Please feel free to open new ones for faced problems.

**Comment by agneevX** [comment]
I sort of regret creating this issue as I've learnt over time that Docker healthchecks create unexpected issues and do more harm than good.

1. https://forums.unraid.net/topic/110999-guide-on-how-to-stop-excessive-writes-destroying-your-cache-ssd/
2. https://forum.openmediavault.org/index.php?thread/38480-plex-pms-container-creates-constant-disk-access-load/

I therefore ask that this feature be removed or that docs be updated to mention issues with this and how it can interfere with something as critical as DNS.

**Comment by chennin** [comment]
> What in the world is the random string of letters in the ?dns= query and how do I construct it myself?

This is apparently hard to find an answer to, but I found your question via Google when I had the same question, so here's the answer for anyone who needs it.

It seems Adguard doesn't take a name/type parameter. But here's how to craft the `dns` parameter it does take in one Python line. Note: requires `dnspython` >= 2.2.0, or for you to remove the `,id=0` piece.  Change `example.com` as you wish.

```bash
    DOMAIN="example.com" python3 -c "import os, dns.message, requests, base64; req = dns.message.make_query(os.environ['DOMAIN'], 'A', id=0).to_wire(); print(base64.urlsafe_b64encode(req).decode('utf-8').rstrip('='))"
```

Note that the response will be binary, so do not use with curl and output to a terminal.  Interpreting the response can also be done in Python, example [here](https://stackoverflow.com/a/68668641/6791494).

(reference re padding and id: [here](https://github.com/dohwg/draft-ietf-doh-dns-over-https/issues/30#issuecomment-345850479) and on)

**Comment by Taverius** [comment]
@agneevX Iunno man all the issues you linked seem to come from misconfiguration/misuse of the hardware.

I believe If you have to disable logging to solve disk write issues, maybe you should move your docker to somewhere where *having logs* doesn't destroy your storage device, i.e. not a consumer SSD that's part of a zfs vdev, and that is a hill I am willing to die on.

In the specific case of docker healthchecks, the classic `curl` test already writes to sdtout and not to file, and the equally common `wget` one is easily adjusted to do so:
```yaml
    healthcheck:
      test: wget -t1 -qO - http://localhost:XXXX/ || exit 1
```
If the page they're fetching doesn't give anything useful in case of a failure you can end them with `> /dev/null || exit 1` instead, and if you don't think the error messages would be useful you can use `> /dev/null 2>&1 || exit 1` instead.

In AGH's case I'm using:
```yaml
    healthcheck:
      test: nslookup HOSTNAME 127.0.0.1 > /dev/null
      start_period: 30s
      start_interval: 3s
      interval: 15s
      timeout: 15s
      retries: 1
```
This will of course fail if AGH is not configured at all yet, and I consider this a feature, as that will only happen if something goes wrong.

Choose the lookup hostname carefully.

1. To test basic name resolution, set an alias of `healthcheck.yourdomain` to `0.0.0.0` or something in "Filters > DNS Rewrites" in the AGH UI, put it in your querylog/stats exclusions, and check for that.
2. To test one level up in your configuration tier:
    * ensure AGH is set to read `/ect/hosts` with:
    ```yaml
    dns:
      hostsfile_enabled: true
    ```
    * Then a dummy host in the compose with:
    ```yaml
    extra_hosts:
      - "healthcheck.yourdomain=0.0.0.0"
    ```
    * Exclude and check for that.

3. The docker dns name of another container that's always up - say, `portainer` - or an alias set in the host machine's `/etc/hosts` can be used too, assuming you set `127.0.0.11` for local domain resolution.
  This will also check that nothing has gone subtly wrong with the AGH container's network configuration; I recommend the host's `/etc/hosts` option.
  You could also set a specific upstream for that hostname only, with `[healthcheck.yourdomain]127.0.0.11` in your AGH DNS Settings so that the wider LAN won't get name resolutions they can't use for docker containers.
4. A static DNS record set on your router, assuming you're not doing *all* of your DNS on AGH and still have your router as the final hop for any local domain names that you don't set in AGH. This also checks that AGH can *see* said router, but will also false positive in case the router is rebooting for upgrades. A dummy only used for tests is recommended so you can add it to exclusions, that way other things on your LAN can use it too if needed.
5. The classic `www.google.com` or `www.example.com` will also check for WAN, and I don't think is a good idea - you should be looking at your router's logs for that info, and its tricky to decide on what to use assuming you want to add it to exclusions.

Personally I use option 3, with `healthcheck.internal` on the docker host's `/etc/hosts`, although I also have `test.internal` on the router for other network infrastructure to check that the router is up.

If you're *really* serious about it, I guess you could write a script that checks all levels, and echoes the exact failure resolution tier if happens, mount that into the container with a bind, and use that, although I don't think the AGH container's healthcheck is the right place for something like this.
