### ISSUE TITLE
OpenWRT: command "arp" has failed

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#3597]
`2021/09/15 01:06:11.931024 24345#18 [debug] command "arp" has failed: "exec: \"arp\": executable file not found in $PATH" code:-1`

On OpenWRT `arp` seems to be defined as a shell function `arp() { cat /proc/net/arp; }`

Should AGH switch to using `ip neigh` if `ip` is installed and fall back to `arp`, if it exists as an executable or just look in `/proc/net/arp`?

**Comment by ainar-g** [comment]
Hello and thanks for the suggestion.  I actually see a few issues in our current implementation:

1.  AGH doesn't use alternative ways of getting the ARP info from the kernel, including `/proc/net/arp` and `ip neigh`.

1.  AGH doesn't stop the attempts to get the client info after several failures.  One could assume that this is a feature, since the `arp` binary can technically still appear later, but I personally think that this is a rather weak excuse.

1.  This functionality should really be moved to package `aghos` and not just stay in package `home`.

I think we can refactor it all together in the v0.108 cycle.

**Comment by EugeneOne1** [comment]
@timkgh, hello again.  We've improved ARP-related logic a bit.  It's available in the latest edge build and it should use some different sources of data including parsing `/proc/net/arp` file.   It should also notify about occured errors only once at the start.  Could you please check if it fixes the issue for you?

**Comment by EugeneOne1** [comment]
@timkgh, hello.  I'll close the issue for now.  Feel free to file new ones if you'll face any bugs with our solution.
