### ISSUE TITLE
Errors when using web GUI

### ISSUE THREAD

**Issue by lukeswitz** [AdguardTeam/AdGuardHome#3739]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Issue anytime attempting to change custom rules or add a domain to block/unblock from the logs view. Possibly a schema version issue in the .yaml file?

`Error: control/version.json | Network Error`

The error message changes, sometimes about rules. Doesn’t immediately appear, I have to toggle WiFi to see them. 

* **Version of AdGuard Home server:**
  - v0.107.0-b
* **How did you install AdGuard Home:**
  * Built from source
* **How did you setup DNS configuration:**
  * rPi 3 & 4
* **CPU architecture:**
  64bit but running the 32bit version as recommended in the guide on here. 

### Expected Behavior
Green dialog message “rule added: xxxxx”

### Actual Behavior
No response followed by a red error message

**Comment by ainar-g** [comment]
Hello.  To be honest, that sounds like a network error somewhere in the chain, because we cannot reproduce that.  Please add the following information:

1.  What version exactly are you using?  As far as I remember, we don't have a version `v0.107.0-b` without the number.

2.  Can you [configure] AdGuard Home to collect logs by setting  `verbose` to `true`, reproduce the situation, and post the logs here as an attachment?

Thanks.

[configure]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog
