### ISSUE TITLE
API query log endpoint returns queries for a larger scope than requested

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardHome#3838]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.106.3
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * arm64
* **Operating system and version:**
  * Ubuntu 20.04 LTS

### Issue Details

When calling the `/control/querylog` endpoint with `offset=0&limit=100&response_status=all&search=10.0.0.1` parameters, the API is returning logs for all queries matching `10.0.0.1*`, that means all queries for `10.0.0.1-10.0.0.199`.

Cannot reproduce this with other IPs, just `10.0.0.1`.

**Comment by jojost1** [comment]
Additionally, it seems like v0.106.3 adds quotes around the search parameter while v0.107 beta does not. Is this intentional behaviour?

v0.106.3
![image](https://user-images.githubusercontent.com/8880568/141443679-d1e37c42-516b-407c-8e25-73655b015da8.png)

v0.107.0-b.14
<img width="625" alt="image" src="https://user-images.githubusercontent.com/8880568/141443728-199bbc6c-1da8-4842-90eb-36e6f88654d2.png">

I might be wrong but wanted to make sure anyways :-)

**Comment by EugeneOne1** [comment]
@agneevX, this is an expected behavior actually – you have to put `10.0.0.1` into double quotes (`search="10.0.0.1"`) to perform a strict search by the exact address.  Unless it's done, you'll got all the results containing the entered text.

Could you please try it and tell if it works?

**Comment by agneevX** [comment]
Thanks for getting back @EugeneOne1. I'm in contact with @jojost1 regarding this issue.

That does work in fact. So this is intended behavior?

**Comment by EugeneOne1** [comment]
@agneevX, absolutely.
