### ISSUE TITLE
AdGuard Home in an Active Directory Environment

### ISSUE THREAD

**Issue by RavHilton** [AdguardTeam/AdGuardHome#3902]
Whilst looking for a way to make internal filtering DNS Servers work in a somewhat managed and redundant fashion, I found Pihole was not really suited to this kind of configuration, but that AdGuard Home, with the additional AdGuardHome-Sync container, was suited quite nicely.

I can get this set up and running on pretty much any network, providing an AdGuard Home primary filtering DNS server in one docker environment, an AdGuard secondary filtering DNS Server in a second docker environment, and using AdGuardHome-Sync to keep the configurations of these two (or more) servers in sync.  Works great, and AdGuard provides some nice features over Pihole.

The one thing that Pihole seems to have a win with is in an Active Directory environment - whereas AdGuard Home simply allows the rDNS resolution of private IPs by a DNS Server configured through the Settings, DNS Settings, Upstream DNS servers, Private DNS servers (and enabling this), Pihole also allows Conditional Forwarding using a local network address, conditional forwarder, and also a local domain name.

The major advantage of the functionality Pihole provides is that Active Directory lookups are passed from the Pihole to the local AD-integrated DNS Server using this Conditional Forwarding function.  It means that when an Active Directory connected device wants to request one of the myriad of AD-related DNS records, Pihole will pass this straight to the AD-integrated DNS Server, and all other traffic out to the regular upstream DNS resolver.

Is there a similar capability in AdGuard Home that I am missing?  If not, is this something that would be able to be added as a feature request?  As I mentioned, I do rather like AdGuard Home and its ability to run multiple, synchronised DNS Servers on a single network (unless Active Directory is involved).

**Comment by EugeneOne1** [comment]
@RavHilton, hello.  What is the domain of your AD?  If I understand you correctly, you may achieve this behavior with [domain-specific](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#upstreams-for-domains) upstream configuration.  Something like:

```
[/my.ade.domain/]1.2.3.4
```

**Comment by RavHilton** [comment]
Aahhh, yes, that looks like it should do the job.  I'll have a bit of a look at documentation about that.  Thanks...

**Comment by RavHilton** [comment]
And yeah, after a read, looks like it will do the trick quite nicely.  I'll wait until after hours, drop the Pihole servers that are now running again, reload the AdGuard Home servers, implement these changes and test - and I'm pretty sure that this will address the issue quite nicely.

**Comment by Birbber** [comment]
Closing this issue as completed.

**Comment by outofsight** [comment]
I try to resurrect this topic before opening another one because my issue is related with Active Directory and Windows DNS Server.

I deployed ADGuard Home in my network and I was planning to make clients use ADGuard as DNS Server and let ADGuard forward query to Windows DNS Server for LAN domain and to public external DNS Server for others names. So I made upstream servers configuration similar to

```
[/lan.mycompany.com/]10.20.50.33
1.1.1.1
```

But when from a Windows computer on the lan (whose DNS domain suffix is **lan.mycompany.com**) I try make a name query for, say, **www.google.com**, it happens that the os resolver send to ADGuard a query for **www.google.com.lan.mycompany.com** and later **www.google.com.mycompany.com**.

Both queries goes, I suppose, from ADGuard to Windows DNS Server who can't solve internally and, I suppose, forward to public DNS server: the first one is not resolved externally, but the second one is resolved, because *.mycompany.com is registered and point to my public ip.

Any idea?

I could disable Windows DNS Server forwarding, but I would'nt be able to use it as DNS Server for other critical servers.

I could use AdGuard after Windows DNS Server instead of before but I would'nt be able to apply DNS resolution rules policy based on client.
