### ISSUE TITLE
DHCP hostnames not resolved by DNS server

### ISSUE THREAD

**Issue by aserrallerios** [AdguardTeam/AdGuardHome#3974]
Version: 0.107.0.b.7

I'm expecting the DNS server to return DHCP hostnames. Both the DNS server & the DHCP server work properly in isolation.

<img width="974" alt="Screenshot 2021-12-21 at 17 45 09" src="https://user-images.githubusercontent.com/3159593/146967154-9be6f4d7-84b3-4e2a-8915-bba84b0f4d36.png">

```
❯ nslookup alberts-mbp 192.168.1.6
Server:		192.168.1.6
Address:	192.168.1.6#53

** server can't find alberts-mbp: NXDOMAIN
```

**Comment by ainar-g** [comment]
That's what the `local_domain_name` setting in `AdGuardHome.yaml` is for.  By default, it's set to `lan`, so in your case it'll be `alberts-mbp.lan`.

**Comment by aserrallerios** [comment]
My bad! (the project is bigger than I thought and it's very configurable)

BTW, looking at the docs [here](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration) I don't know if _empty_ domain name is allowed.

**Comment by ainar-g** [comment]
The “Configuration” Wiki page is going to be rewritten in the nearest future, as it has multiple issues, unfortunately.

If I recall correctly, the reason why we don't allow resolving DHCP domains without an upper-level domain name is to prevent overwrites, since the hostnames used by the DHCP server are sent by the clients.  Since they're single-level, it's not that bad, but if we ever allow accepting multi-level domain names from clients, and some DHCP client sends a hostname of, say `google.com`, that might be an issue.
