### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by savenok93** [AdguardTeam/AdGuardHome#4033]
Hi, I have been using Adgurdhome for over a year, before everything worked and everything was fine. A couple of weeks ago, I moved to another hosting, and decided to completely reinstall the service. I get stable error for (Certificate chain is invalid) and (Your certificate does not verify: x509: certificate signed by unknown authority). I've already tried everything, and the docker version and installation on the server, and I just can't get it to work properly. The problem is observed from the certificates of cloudflare and ionos (Sorry for google translation)
https://0x0.st/orDI.png
https://0x0.st/orDl.png

**Comment by Funny-T** [comment]
You need to provide more information, otherwise no one can answer your question.

**Comment by savenok93** [comment]
What information should you provide?

**Comment by ainar-g** [comment]
@savenok93, hello.  In order to debug this issue, please respond to the following questions:

1.  What version of AGH are you using?

2.  Is the time on the machine correct?  That is, if you run `date`, does it show the correct date and time?

3.  Are the root certificates on the machine up-to-date?

4.  If you [enable verbose logs][1] and open the page, does it show any more information in these logs?

Thanks!

P.S.  We could switch to Russian or another language, if that is more comfortable for you.

[1]: https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog

**Comment by savenok93** [comment]
> @savenok93, hello. In order to debug this issue, please respond to the following questions:
> 
> 1. What version of AGH are you using?
> 2. Is the time on the machine correct?  That is, if you run `date`, does it show the correct date and time?
> 3. Are the root certificates on the machine up-to-date?
> 4. If you [enable verbose logs](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#verboselog) and open the page, does it show any more information in these logs?
> 
> Thanks!
> 
> P.S. We could switch to Russian or another language, if that is more comfortable for you.

Решилось добавлением сертификата в корень
