### ISSUE TITLE
validating ports: duplicated values: [3000]

### ISSUE THREAD

**Issue by faisalramly** [AdguardTeam/AdGuardHome#4095]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 
* **How did you install AdGuard Home:**
  * 
* **How did you setup DNS configuration:**
  * 
* **If it's a router or IoT, please write device model:**
  * 
* **CPU architecture:**
  * 
* **Operating system and version:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by v2raye** [comment]
After the new installation, I also encountered the same problem as you, and I fell back to v0.106.3 (Google Translate)

**Comment by EugeneOne1** [comment]
@faisalramly, hello.  Could you please fill in the issue template since we couldn't determine the actual problem otherwise.  However I suppose you're trying to set the port `3000` somewhere during the initial setup.  The thing is that the initial setup web page is using it so it can't be assigned to anything else at this moment.  You may try to set another temporary port (e.g. `4000`) and change it afterwards via the `AdGuardHome.yaml` configuration file.  Please let us know if it worked for you.

**Comment by Kratosak** [comment]
I was running AdguardHome via docker smoothly without issues but then I found out that AGH is not working anymore. I had port 3000 assigned for web interface and when I opened link to web interface I get initial setup page. So whole configuration seems to be deleted. I tried assign port 3000 to web interface  in step 2/5 but I get error validating ports: duplicated values: [3000]. I thought that another application is using port 3000 but it is not true. So in this case because of this bug I probably lost whole AGH setup and need to do whole process again when it will be fixed.

**Comment by EugeneOne1** [comment]
@faisalramly, @Kratosak, hello again.  After a little internal discussion we've decided to allow specifying `3000` for web interface's port during the initial setup.  The latest build in the `edge` channel should implement it.  Could you please try it and check if it now works?  Thanks.

**Comment by Kratosak** [comment]
@EugeneOne1 hello. I did following thing:
docker pull adguard/adguardhome:edge
Now I was able to use port 3000 for web interface. I see that version is v0.108.0-a.34+2fdda8a2. What was the reason for denying port 3000? 
I would be ok to use port 3001 for web interface but I would like to avoid situation in the future that also 3001 would be denied. 

Thank you.

**Comment by EugeneOne1** [comment]
@Kratosak.  That was a bug actually, no actual reasons for denying it, sorry for confusion.

As for port `3001`, it is used for beta web interface but only in development builds like `edge`/`beta` ones.  In release builds it should also be free for binding.

**Comment by EugeneOne1** [comment]
@faisalramly, I'll close the issue for now since it seems being resolved.  Please feel free to reopen it if the problem remains.
