### ISSUE TITLE
[Bug] DNS unresolved when fastest server returns SERVFAIL in parallel mode

### ISSUE THREAD

**Issue by SesioN** [AdguardTeam/AdGuardHome#4314]
Version v0.107.3

I have the following DNS servers configured and set the parallel requests mode:

sdns://AgUAAAAAAAAABzguOC44LjigHvYkz_9ea9O63fP92_3qVlRn43cpncfuZnUWbzAMwbkgdoAkR6AZkxo_AEMExT_cbBssN43Evo9zs5_ZyWnftEUKZG5zLmdvb2dsZQovZG5zLXF1ZXJ5
sdns://AgcAAAAAAAAABzEuMC4wLjGgKSuRcnA2MM_hchL0ZJ7FEqZPzVRgCT9UlgxyXqDXa84g63Ul-I8NlFj4GplQGb_TTLiczclX57DvMV8Q-JdjgRgSY2xvdWRmbGFyZS1kbnMuY29tCi9kbnMtcXVlcnk
https://dns11.quad9.net/dns-query
sdns://AQcAAAAAAAAADTUxLjE5NS4xMTcuMjYgI0N2y9-Xq_-5VbF43rxF6u10RV5LphBpRaTRNZuAOnAdMi5kbnNjcnlwdC1jZXJ0Lm1vdWx0aWNhc3QtZGU
sdns://AQcAAAAAAAAADjE3Ni41Ni4yMzcuMTcxIGfADywhxVSBRd18tGonGvLrlpkxQKMJtiuNFlMRhZxmJTIuZG5zY3J5cHQtY2VydC5yZXNvbHZlcjEuZG5zY3J5cHQuZXU
sdns://AQcAAAAAAAAAETQ1Ljc2Ljg4LjIwOjE1MzUzINbOAK_t2sDdDpnwEM5WcsL0dmRlTINGnjXcKyx7KXaTIjIuZG5zY3J5cHQtY2VydC5kbnN3YXJkZW4tdW5jZW5zb3I

Today I've noticed that sometimes suddenly dns queries fail and thus my devices cannot reach the target hosts.

After researching I found out that for some reason 
https://dns11.quad9.net/dns-query is at the moment not stable. 

The response code is then SERVFAIL. 

![Screenshot_20220219-125808_Samsung Internet](https://user-images.githubusercontent.com/9612749/154799824-43e85749-d3b9-40c4-983c-401400e06287.jpg)

When having so many dns servers defined I would expect that a failed request is skipped and the next fastest response is taken instead. 

With the current behavior you end up with unresolved dns.

**Comment by fernvenue** [comment]
As the AdGuardHome [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration) said:

> `all_servers` — Enables parallel queries to all configured upstream servers to speed up resolving. If enabled, the queries are sent to each server simultaneously and the first response is chosen. If disabled, the queries are sent to each upstream server one-by-one and then sorted by RTT. Note that more stable upstream servers are preferred by the algorithm.

Therefore, there is no problem in the behavior of AdGuardHome returning the fastest response in Parallel Requests mode. What you need to know is that `SERVFAIL` is also a return, which means that the DNS server rejected the resolution, not that the DNS server failed or did not return. That's why the wiki said *Note that more stable upstream servers are preferred by the algorithm*. The Parallel Requests mode works better when all your upstreams are credible and stable.

And as [ameshkov](https://github.com/ameshkov) said in https://github.com/AdguardTeam/AdGuardHome/discussions/3207#discussioncomment-801779:

> Hm, you know, it's not handled and AGH will simply respond with what it gets first.

All in all, this is how Parallel Requests mode works, `SERVFAIL` is also a response type, that's **NOT A BUG**.

**Personally**, I recommend that you use the following upstreams in Parallel Requests mode:

- For IPV4:

```
#google
tls://8.8.8.8
tls://8.8.4.4
https://8.8.8.8/dns-query
https://8.8.4.4/dns-query

#cloudflare
tls://1.1.1.1
tls://1.0.0.1
tls://162.159.36.1
https://1.1.1.1/dns-query
https://1.0.0.1/dns-query
https://162.159.36.1/dns-query
```

- For IPv6:

```
#google
tls://[2001:4860:4860::8888]
tls://[2001:4860:4860::8844]
https://[2001:4860:4860::8888]/dns-query
https://[2001:4860:4860::8844]/dns-query

#cloudflare
tls://[2606:4700:4700::1001]
tls://[2606:4700:4700::1111]
https://[2606:4700:4700::1001]/dns-query
https://[2606:4700:4700::1111]/dns-query
```

These upstreams use encrypted protocols and they all have SSL certificates configured on their IP addresses, so there is no need for additional resolution by Bootstrap DNS servers, that means they can respond to requests as quickly as possible in Parallel Request mode with trusted and unfiltered answear.

**Comment by SesioN** [comment]
Thanks for a very informative response. Now definitally understand it better.

All my DNS servers are unfiltered. Meaning in my use case a SERVFAIL while still being a valid response has a context of being invalid.

Maybe a feature, where we can say "do not accept SERVFAIL as valid response" would make sense.

Then it would just go to the next fastest response and try to use that.

**Comment by fernvenue** [comment]
> Thanks for a very informative response, that's highly appreciated. Now I definitally understand it better.
> 
> All my DNS servers are unfiltered. In my use case a SERVFAIL while still a response has defintily a context of being invalid.
> 
> Maybe a feature, where we can say "do not accept SERVFAIL as valid response" would make sense.
> 
> Then it would just go to the next fastest response and try to use that.
> 
> As all my dns servers are external resources, I have zero power to guarantee their stability.
> 
> Theoretically, even using what you suggest could lead to the very same problem. Where suddenly your dns is not resolving as one of your parallel requests gives a SERVFAIL.
> 
> Like look how often AWS had big impact issues recently. This can happen to any provider.

Yes, we have no power to guarantee their stability, that's true. But just like what I said above: `SERVFAIL` is also a response, **that not means DNS Server dead**. Let me give you an example:

```
~# nslookup dnssec-failed.org 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find dnssec-failed.org: SERVFAIL

~# nslookup dnssec-failed.org 1.1.1.1
Server:         1.1.1.1
Address:        1.1.1.1#53

** server can't find dnssec-failed.org: SERVFAIL
```

Like this, for some reason, it is normal for some requests to return `SERVFAIL`, and they should always be returned with `SERVFAIL`. **If a DNS server is really dead, it doesn't return any results**, but other DNS servers should be able to return results normally.

Also, in my personal recommendation, these servers are as stable and reliable as possible, and none of them need the help of Bootstrap DNS Servers to resolve themselves, which on the other hand can alleviate resolution errors due to other causes and provide a shorter average processing time. Of course, those are just my personal recommendations, just for reference.

**Comment by SesioN** [comment]
> > Thanks for a very informative response, that's highly appreciated. Now I definitally understand it better.
> > All my DNS servers are unfiltered. In my use case a SERVFAIL while still a response has defintily a context of being invalid.
> > Maybe a feature, where we can say "do not accept SERVFAIL as valid response" would make sense.
> > Then it would just go to the next fastest response and try to use that.
> > As all my dns servers are external resources, I have zero power to guarantee their stability.
> > Theoretically, even using what you suggest could lead to the very same problem. Where suddenly your dns is not resolving as one of your parallel requests gives a SERVFAIL.
> > Like look how often AWS had big impact issues recently. This can happen to any provider.
> 
> Yes, we have no power to guarantee their stability, that's true. But just like what I said above: `SERVFAIL` is also a response, **that not means DNS Server dead**. Let me give you an example:
> 
> ```
> ~# nslookup dnssec-failed.org 8.8.8.8
> Server:         8.8.8.8
> Address:        8.8.8.8#53
> 
> ** server can't find dnssec-failed.org: SERVFAIL
> 
> ~# nslookup dnssec-failed.org 1.1.1.1
> Server:         1.1.1.1
> Address:        1.1.1.1#53
> 
> ** server can't find dnssec-failed.org: SERVFAIL
> ```
> 
> Like this, for some reason, it is normal for some requests to return `SERVFAIL`, and they should always be returned with `SERVFAIL`. **If a DNS server is really dead, it doesn't return any results**, but other DNS servers should be able to return results normally.
> 
> Also, in my personal recommendation, these servers are as stable and reliable as possible, and none of them need the help of Bootstrap DNS Servers to resolve themselves, which on the other hand can alleviate resolution errors due to other causes and provide a shorter average processing time. Of course, those are just my personal recommendations, just for reference.

I see. However in my specific case this one dns server was giving SERVFAIL to all responses, leading to the reported issue. 

What do you think about an option that allows you to verify SERVFAIL responses if multiple DNS servers are defined?

eg: "Verify SERVFAIL with at least X DNS servers" or "Accept SERVFAIL after verifying with: X DNS servers" 

That way, when using parallel request mode one could define if a SERVFAIL is to be accepted straight away or verified with another DNS servers response. 

eg. If you set the option to 2, and the fastest DNS server gives a SERVFAIL, then Adguard goes for the 2nd fastest DNS and checks whenever it also gives a SERVFAIL for the query. And so on.
