### ISSUE TITLE
very slow response time with ipv6 enabled on AGH

### ISSUE THREAD

**Issue by alleway** [AdguardTeam/AdGuardHome#4393]
while configuring AdGuard Home DNS server to use on router, by adding ipv4 address works fine with 192.168.x.x only.  if enabled with ipv6 on router by adding AdGuard Home DNS server ipv6 address, the internet response time is very slow.  currently turning off ipv6 on router solves the issue by using one AdGuard Home DNS server address(192.168.x.x).  any assistance will be appreciated with a optimised configuration to handle it along with ipv6

**Comment by daryll-swer** [comment]
I'm using AdGuard home with IPv6 and no problems. There are many possible factors that can be root cause @alleway 

I am assuming you're a residential customer of your ISP:
1. If the ISP is using PPPoE and RFC4638 isn't deployed correctly, it will create MTU problems and get worse if they blocked ICMPv6 on the BNG
2. Your own router is blocking ICMPv6
3. You misconfigured SLAAC/RAs/DHCPv6 on the router
4. A simple case of sub-optimal routing of the IPv6 prefix handed to you by your ISP which of course would lead to high latency and slow things down considerably

This is less of an AGH problem and more of a problem between your router, the ISP and their global routing.
