### ISSUE TITLE
When I add a list adguard home dashboard saids dns server is starting up and dns server goes down for a 2 minutes

### ISSUE THREAD

**Issue by Dynasty-Dev** [AdguardTeam/AdGuardHome#4414]
AdGuard Home Version  
v0.108.0-a.88+77858586 Edge branch

Installed from curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -c edge

AdGuard Home is setup on raspberry pi zero 2 w

OS is raspbian lite 64 bit

Issue: 

Whenever i add a blocklist under filters > dns blocklists adguard home dns goes down for 2 minutes then it starts back up and the list is added

I expected for this to be fast like the stable branch

**Comment by agneevX** [comment]
The Zero 2W has 0.5GB of RAM, much less available. I'd say it's memory-constrained. What else do you run on it?

Can you post logs?

**Comment by Dynasty-Dev** [comment]
> The Zero 2W has 0.5GB of RAM, much less available. I'd say it's memory-constrained. What else do you run on it?
> 
> Can you post logs?

sorry, ive since reinstalled raspbian os but this time i install buster instead of bullseye and install adguard home from beta branch instead of edge and this issue no longer happens.

**Comment by EugeneOne1** [comment]
@Dynasty-Dev, hello.  As @agneevX noted, it's most likely a memory lack.  Since the beta release doesn't behave the same, I'll close the issue as resolved if you don't mind.  If the problem remains, please consider reopening the issue and collect a [verbose log](https://github.com/adguardTeam/adGuardHome/wiki/FAQ#verboselog) to help us troubleshoot it.  Thanks.
