### ISSUE TITLE
DDNS和DNS缓存

### ISSUE THREAD

**Issue by dfbb9216** [AdguardTeam/AdGuardHome#4458]
是这样的，有的时候主路由器会因为一些原因重启，这时候IP更换，然后在旁路由上的ADGH上缓存的DDNS地址会继续使用造成DDNS无法使用。能不能设置一个某些地址禁用缓存？或者目前有无办法可以解决，感谢，新人提问,水平很差。

**Comment by fernvenue** [comment]
Duplicate of https://github.com/AdguardTeam/AdGuardHome/issues/4197.

So now you can't, it's still just a feature request. For now you should set a low TTL on your NS for your DDNS domain or you can rewrite your DDNS domain to its LAN address if your router and second router in the same LAN. Actually you should set a low TTL for your DDNS domain whether you can disable caching for specific domains in AdGuardHome, because even if you disable the cache on AdGuardHome, other users or devices using your domain will still use the cache because of the high TTL. That's what's causing the problem, AdGuardHome's current caching behavior is normal and reasonable. Rather than just disabling the cache for yourself you should be addressing the problem at the source right?

**Comment by dfbb9216** [comment]
> 

感谢，通过你的解答，我知道如何解决了

**Comment by dfbb9216** [comment]
感谢，通过你的回答，我知道如何解决了
