### ISSUE TITLE
Not Working after server restart

### ISSUE THREAD

**Issue by souravbrock** [AdguardTeam/AdGuardHome#4460]
When I reboot the server the services don't come up, the web interface is not accessible, unable to find out a proper solution for this, please help, on the other hand plex never had this problem it works smoothly event after reboot

**Comment by fernvenue** [comment]
You may need to provide more information:

- What operating system are you using?
- How do you install AdGuardHome?
- What is the status of AdGuardHome after you reboot? Any error meessage?
- What is the version of your AdGuardHome?

Waiting for your reply :)

**Comment by Fofer** [comment]
Have you tried accessing it at port 3000 instead?

Asking because I was having this exact same problem after server restarts. I couldn't access AdGuardHome on my chosen port, of 8080. I assumed AdGuard was broken and needed to be uninstalled/reinstalled. Eventually I learned the port number wasn't persisting, and everything was actually working fine. I just needed to update my bookmarks to access it on port 3000 instead.

I'm running mine alongside Homebridge, using AdGuard's own installer, if that matters:
I wrote about it [here.](https://github.com/homebridge/homebridge-raspbian-image/issues/71)
And [here](https://www.reddit.com/r/homebridge/comments/shy431/hbconfig_adguard_home_installation_and_retention/). 
Which helped [another user here.](https://www.reddit.com/r/homebridge/comments/shy431/hbconfig_adguard_home_installation_and_retention/i5oa1v4/
)

**Comment by souravbrock** [comment]
- What operating system are you using? (Ubuntu 18.04.6 LTS (GNU/Linux
   4.15.0-175-generic i686))
   - How do you install AdGuardHome? (curl -s -S -L
   https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh
   | sh -s -- -v)
   - What is the status of AdGuardHome after you reboot? Any error
   meessage? (no error messages found)
   - What is the version of your AdGuardHome? (Version: v0.107.6)



Thanks Regards,
Sourav Mukherjee
Mail to: ***@***.***
Call at: +91-9836180680 <http://voice.google.com/calls?a=nc,%2B919836180680>
---------------------------------------------------------------
Dare to be Different
----------------------------------------------------------------

**Comment by BrutalCoding** [comment]
I believe this issue is ongoing, any news?

**Comment by Fofer** [comment]
> I believe this issue is ongoing, any news?

This was fixed back in May:
https://github.com/homebridge/homebridge-raspbian-image/issues/71#issuecomment-1120341120
