### ISSUE TITLE
certificate and keys 

### ISSUE THREAD

**Issue by jeromelarras** [AdguardTeam/AdGuardHome#4711]
hi

i setup an adguard home on my ds720plus synology nas without trouble

now i want to add encryption with certificates from my nas

so when the nas generates the zip file, i unzip them, private key and rsa or ecc pem files 
when i put the private key, that seem to be ok until 2035 nice shot :)

but when i push the cert file, adguardhome doesn't want it

what can i try to fix that issue ?

thanks

**Comment by fernvenue** [comment]
That’s because your self generated certificate can’t be varified, that means AdGuardHome will not gonna know is your connection safe or not.

Here’s my suggestion, if you wanna use your AdGuardHome on public side, you may need a real certificate like [Let’s Encrypt](https://letsencrypt.org/) or something. But if you are using AdGuardHome just for your private network, just ignore it and keep using your self generated certificate :)

**Comment by cyb3rz3us** [comment]
> so when the nas generates the zip file

What does this mean?  Does the NAS actually generate the cert + private key?

**Comment by fernvenue** [comment]
> > so when the nas generates the zip file
> 
> What does this mean? Does the NAS actually generate the cert + private key?

I believe so, cause he got a certificate that works until 2035, that can’t be a public certificate.

**Comment by cyb3rz3us** [comment]
> only can be a self generated certificate.

I tend to agree but it is possible Synology does something where it generates a widely accepted CA signed cert - not sure.  Important to understand before diving into providing feedback...

**Comment by fernvenue** [comment]
> I tend to agree but it is possible Synology does something where it generates a widely accepted CA signed cert - not sure. Important to understand before diving into providing feedback...

Cloudflare also provides 15 years certificate, but they are all self-generated certificate some way, can't be used directly on public.

> Also, when I tried a self-signed cert it simply wouldn't work which then led to an invalid encryption config. And without a valid encryption config, IIRC, then DoH and DoT wouldn't work...

Because you should ignore it on client side also, like skipping verification technically. Again, we should use self-generated certificate only for testing or in private network :)

**Comment by fernvenue** [comment]
> > you should ignore it on client side also
> 
> I'm not aware of any DoH\DoT client that ignores cert verification - if you or others are aware, please share.

Most of the clients don't allow you to skip certificate verification, in this case, you can add your self-generated certificate to the trust list, you can find a lot of information on Google about that. Also, there are indeed DNS clients that provide to skip certificate verification, like [kdig](https://www.knot-dns.cz/docs/2.6/html/man_kdig.html).

**Comment by cyb3rz3us** [comment]
We're kind of going in circles and distracting from the thread - so back to the OP's question...

In the many AGH servers I've built, I have not been able to get a valid AGH encryption config using a self-signed cert.  And if the encryption config is not valid, then AGH will not be able to serve client-side DoH\DoT requests.  The upstreams worked fine but the client side never worked until I installed a cert signed by a public CA.

**Comment by fernvenue** [comment]
> We're kind of going in circles and distracting from the thread - so back to the OP's question...
> 
> In the several AGH servers I've built, I have not been able to get a valid AGH encryption config using a self-signed cert. And if the encryption config is not valid, then AGH will not be able to serve client-side DoH\DoT requests. The upstreams worked fine but the client side never worked until I installed a cert signed by a public CA.

Short answer: Add your self-generated certificate to the trust list on your devices.

**Comment by cyb3rz3us** [comment]
> Short answer: Add your self-generated certificate to the trust list on your devices.

You're misunderstanding the issue.  This has nothing to do with the client --- it has to do with the AGH server.  When entering in the cert chain and key under `Settings --> Encryption settings`, AGH checks to see if they are valid.  If it determines they aren't, then AGH throws and error and will not serve DoH\DoT client requests.

Th client side plays no role in AGH determining if the cert + key are valid.

**Comment by fernvenue** [comment]
In my tests, I pasted the self-generated certificate and key, then AdGuardHome told me:

```
Certificate chain is invalid.
Your certificate does not verify: x509: certificate signed by unknown authority
```

But I can still save the certificate and key, next, I added it to the trust list on my local devices, and it's fully working now:

```
~# curl -I https://www.gstatic.com/generate_204 --doh-url https://router.lan/dns-query
HTTP/2 204
date: Wed, 06 Jul 2022 16:36:20 GMT
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

And if you also add the certificate to the trust list of the server where AdGuardHome is installed, it will even be verified by AdGuardHome.

Given that I think your discussion is a little off-topic and this is actually a solved issue, and I think I've also given a clear enough answer, if you continue to question my answer, I suggest you move on to the relevant issue like https://github.com/AdguardTeam/AdGuardHome/issues/2266 to learn more about how self-generated certificates are used on AdGuardHome.

**Comment by JakeTrans** [comment]
Hi, little different but same principle I think I'm running adguard in docker , I've used the follow tutorial to setup my own CA and use that to sign my certificates for my home setup

https://github.com/ChristianLempa/cheat-sheets/blob/main/misc/ssl-certs.md

this works on other services - Portainer / Cockpit etc - to give me a signed cert (with the CA Trusted on the box)

for Adguard however I get certificate chain invalid, and I can't seem to generate a correct chain. this is less because I want to use it publicly - more as part of learning certs and etc I want to give certs to any of the services I'm running I can so shouldn't need a outside cert in my view.

![image](https://github.com/AdguardTeam/AdGuardHome/assets/29899935/c2c4332f-f1f6-4ab2-bdea-89bc436ea1d8)

Do I need to set the CA as trusted somewhere in Adguard

Thanks,
