### ISSUE TITLE
为什么我在ROS+openWrt上使用adguardhome，但youtube广告不起作用？

### ISSUE THREAD

**Issue by sshappys** [AdguardTeam/AdGuardHome#4712]
你好：
        我使用adguardhome的web版，单独一个服务器，我的路由器是ROS+OPENWRT，ROS系统的DNS=adguardhome的ip地址，openWrt系统的DNS和网关为ROS地址，目前，adguardhome可以工作，但是，在浏览器中打开youtube，观看视频的时候还是会有广告，其他的网站可以起作用，只是youtube不行。。。不知道什么原因？
还有一个问题，就是DNS拦截列表，如果使用的地址是空的或异常的，就会卡顿，一段时间没有反应。

**Comment by fernvenue** [comment]
It is impossible to block YouTube ads by DNS filters, because YouTube use the same domain for video service and ads, that means by DNS filters you can't block ads only and keep the video service, you will block whole YouTube in this way. And actually this is a duplicate issue: https://github.com/AdguardTeam/AdGuardHome/issues/238.

AdGuardHome hangs while updating block list also a duplicate issue: https://github.com/AdguardTeam/AdGuardHome/issues/1232, that is most likely because the connection with the upstream timeout. Don't worry about it, make sure the upstream reachable and wait, or you can enable verbose log to see the details :)

**Comment by sshappys** [comment]
ok ,thanks

**Comment by fernvenue** [comment]
Could you please provide screenshots or something? And what kind of block list does your Windows AdGuardHome use?

**Comment by fernvenue** [comment]
Okay, you are talking about AdGuard, AdGuard and AdGuardHome are completely different things. AdGuardHome only works with DNS, but AdGuard can do more, because AdGuard directly work on your device, ability to handle network request details.

**Comment by sshappys** [comment]
oh,thanks. 我了解。

**Comment by howellleawo** [comment]
你用ros+op 分流了没

**Comment by fernvenue** [comment]
@sshappys I think maybe we can close this issue now.

**Comment by sshappys** [comment]
> @sshappys I think maybe we can close this issue now.

yes,ok

**Comment by sshappys** [comment]
> 你用ros+op 分流了没
OP有分国内国外，ROS没有，可以私聊。
