### ISSUE TITLE
AdGuardHome is unable to response to query type ANY or ALL

### ISSUE THREAD

**Issue by Marsupilani** [AdguardTeam/AdGuardHome#4741]
When I try the following
nslookup
server \<AdguardHomeServerIP\>
set q=any (or set q=ALL)
<FQDN>

I got 
*** [\<AdguardHomeServerIP\>] can't find \<FQDN\>: Not implemented

When I use a 'real' DNS-Server it works as designed...

**Comment by cyb3rz3us** [comment]
AFAIK, the DNS RFCs do not mandate that `QTYPE=any` be answered.  And unless AGH supports RFC 8482, then what you see may be by design.

It's also worth pointing out that while some large DNS providers do provide answers to ANY queries, others such as CloudFlare, do not.  Or it doesn't appear so when using interactive `nslookup` and Cloudflare's IPs for the server.

For a more in depth discussion, I recommend the following: https://blog.cloudflare.com/rfc8482-saying-goodbye-to-any/

```
> set q=any
> server 1.1.1.1
Default server: 1.1.1.1
Address: 1.1.1.1#53

> set all
Default server: 1.1.1.1
Address: 1.1.1.1#53

Set options:
  novc			nodebug		nod2
  search		recurse
  timeout = 0		retry = 3	port = 53	ndots = 1
  querytype = any     	class = IN
  srchlist =

> cisco.com
Server:		1.1.1.1
Address:	1.1.1.1#53

** server can't find cisco.com: NOTIMP

> server 1.0.0.1
Default server: 1.0.0.1
Address: 1.0.0.1#53

> cisco.com
Server:		1.0.0.1
Address:	1.0.0.1#53

** server can't find cisco.com: NOTIMP

> set q=a

> cisco.com
Server:		1.0.0.1
Address:	1.0.0.1#53

Non-authoritative answer:
Name:	cisco.com
Address: 72.163.4.185
```

**Comment by EugeneOne1** [comment]
@Marsupilani, hello.  Please take a look at the [`dns.refuse_any`](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file) setting.  It's the one responsible for processing `ANY` requests.  If that helped?

**Comment by ainar-g** [comment]
Closing since there was no response.
