### ISSUE TITLE
block sercice doesn't work

### ISSUE THREAD

**Issue by EsawaAzusa** [AdguardTeam/AdGuardHome#4755]
Version 0.107.6
Openwrt on Virtualbox
Windows 10

No website and software are blocked.
Such as Youtube, I received a lot of blocking record but can still watching Youtube videos.
And my hosts file is nearly empty.

 Screenshots
![image](https://user-images.githubusercontent.com/54569511/179400600-cc4e789a-376f-44e0-9baa-24573d1c2a1e.png)
![image](https://user-images.githubusercontent.com/54569511/179402448-d320eb44-2fd3-4bc2-8fd0-0724ad7670ba.png)

Maybe I should upgrade to the latest version?

**Comment by ainar-g** [comment]
@EsawaAzusa, hello and apologies for the delay.  The first screenshot is a bit confusing, because it doesn't show any blocked services.  We've made some tests, and while we've found that there is one domain that seems to not be blocked, blocking generally should work.

Please make sure that:

1.  The *Block domains using filters and hosts files* checkbox is checked.

2.  There are no separate settings for the `localhost` client.

3.  Your browser doesn't use some kind of third-party resolver.

**Comment by nabil86** [comment]
Hello, 
I'm trying to block youtube and facebook services but it does'nt works for me, see below a screenshot 
![Capture d’écran du 2022-08-24 13-15-02](https://user-images.githubusercontent.com/3588044/186405166-372ab075-1ede-41d4-b6ab-43718e1cfa57.png)

**Comment by ainar-g** [comment]
@nabil86, please make sure that your browser is actually using AdGuard home as its DNS resolver.  See the questions in my previous comment.

**Comment by nabil86** [comment]
@ainar-g 
I have checked the 3 proposals you mentioned in your previous comment

I don't want to configure DNS on all my browsers,on the other hand how to do it on android ( through private DNS ?? )
I thought that's what adguard home was about, to do this in a centralized way.

**Comment by ainar-g** [comment]
@nabil86, unfortunately, configuring individual clients in a centralized manner is not exactly possible.  Especially now that every browser prefers to use its own DNS settings, which override the system defaults, including ones received over DHCP.
