### ISSUE TITLE
reset statistics, clear logs and filter queries by date/time

### ISSUE THREAD

**Issue by dvaguirre** [AdguardTeam/AdGuardHome#4785]
### Problem Description
Cant reset statistics, clear logs or  filter queries by date/time

### Proposed Solution
add "reset statistcs", "clear logs" and "filter queries by date/time" on gui

### Alternatives Considered
add export to syslog (siem/soar/xdr)

**Comment by agneevX** [comment]
> Cant reset statistics, clear logs

It's already there in Settings > General settings

![image](https://user-images.githubusercontent.com/19761269/181253276-0393cd40-b892-4b37-9462-097a5ddd900a.png)

> filter queries by date/time

Already a feature request being tracked in #481. Clearly you did not bother to search for existing issues first, instead you opted to remove the prerequisites that mention doing so.

**Comment by dvaguirre** [comment]
Tanks @agneevX, and sorry... I looked but didnt find about the https://github.com/AdguardTeam/AdGuardHome/issues/481.

**Comment by TheRayJohnson** [comment]
Found this via Search! Is it possible to ONLY clear `Average upstream response time`? I assume the `Clear statistics` button clears everything including General statistics etc? I [did ask ChatGPT but yano](https://imgur.com/a/VADq6lK), AI isn't *always* right so don't want to run the command.

As I can see some of it is incorrect about simply restarting clears statistics cause in memory (can't be true? as I restart weekly) I'm troubleshooting slow DNS as 1,068ms [nextdns], 677ms [1.0.0.1:53], 289ms [adguard-dns] isn't great since Friday no idea what's happened.
