### ISSUE TITLE
ublock origin blockers add

### ISSUE THREAD

**Issue by jeromelarras** [AdguardTeam/AdGuardHome#4813]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?
adguard home doessn't block add on youtube without premium account,
 
#### Proposed solution
it seems that adguard blocker extension does it not at all but that seems to be first step
https://microsoftedge.microsoft.com/addons/detail/adguard-adblocker/pdffkfellgipmhklpdmokmckkkfcopbh

#### Alternatives considered
for better result, i try 
https://microsoftedge.microsoft.com/addons/detail/ublock-origin/odfafepnkmbhccpbejgmiehpchacaeak

#### Additional information
is there a solution to import ublock filter in adguard home ?

Thanks

**Comment by ainar-g** [comment]
I'm not sure if I understand you correctly.  AdGuard Home doesn't have any premium accounts, you can import your own filtering rule lists, and DNS-level blocking can't block all ads.  Did you intend to post this to the AdGuard browser extension issue tracker?

**Comment by jeromelarras** [comment]
sorry

no i'd tell youtube premium account

**Comment by ainar-g** [comment]
DNS adblocking has known limitations.  Please see [this section in our README][1].  As for additional rules, as discussed, you can add them on the _DNS blocklists_ page.

I'm going to close this issue, since this doesn't seem to be a bug or a feature request for AdGuard Home.  Feel free to reopen with new information if you think that the issue may actually be related to AGH.  Thanks.

[1]: https://github.com/AdguardTeam/AdGuardHome#how-does-adguard-home-compare-to-traditional-ad-blockers

**Comment by jeromelarras** [comment]
Hi and to hide or block the cookies advertising, is there a solution ?
thanks

**Comment by ainar-g** [comment]
Anything that goes on inside a browser could be blocked by an extension.  Please refer to the Discussions forum for additional questions.  Thanks.
