### ISSUE TITLE
Linux Non-Root

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdGuardHome#489]
I am using Solus OS
When i run AdGuardHome as sudo 
Everything works after i set the linux ip of my laptop as dns
But if i change the port from the .yaml file so that i can run it as non sudo
Everything gets stuck at resolving host :(
Maybe its a bug 
For this i cant run it at startup as it doesn't work without root privilege :(
If i can't run it as non-root
Can u tell me how to make it start at boot as root :(

**Comment by hmage** [comment]
Hi!

The most likely problem -- everything gets stuck at resolving host because they only try port 53, if you can find a way to tell the software on your other computers to use different port, you can run without root.

Another way if you don't want to use root but still use port 53 is possible on Linux (and Solus OS is Linux), you can do this:
```
sudo setcap cap_net_bind_service=+ep <path_to_AdGuardHome>
```
Replace `path_to_AdGuardHome` with path to AdGuardHome binary, afterwards, it will be able to bind to port 53 without requiring root.

**Comment by Bhooty** [comment]
Cant start without root shows permission denied on 53 port

**Comment by Bhooty** [comment]
Ok got it work had to change permisions after putting the code u gave <3

**Comment by Bhooty** [comment]
Can u put this code in the wiki page along with the info that to change permission of the folder to run at boot :)
But parental control doesnt work :(

**Comment by Bhooty** [comment]
Hmage can u maark this as solved :D
It seems i can only close this
And now the parental control also works ☺ 
Thanks a lot
But the enforce safe search broken xD
