### ISSUE TITLE
v0.92-hotfix1 fresh install gives me 0 rules and is 'up to date'

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardHome#533]
When I fresh install v0.92-hotfix1 on my Pi, my rule count for AdGuard Simplified is on 0, even though the update time is when AdGuard Home was enabled and started.

Clicking on Check Updates refuses to update and tells me "All filters are already up-to-date".
Wish there was a way to force update...?

<img width="1318" alt="screen shot 2019-01-06 at 3 40 43 pm" src="https://user-images.githubusercontent.com/46271764/50732193-c43de480-11c9-11e9-81bd-3562e14271d6.png">

**Comment by planet0** [comment]
I was able to delete the SDNS filter and manually add it again which gave me a valid rule count.
But I wish I could force an update with the existing lists.

**Comment by ameshkov** [comment]
I mean could it be that when you first started it, there was no DNS available and that's why it failed to download the filter contents?

**Comment by planet0** [comment]
I think I figured it out, your bootstrap_dns is 8.8.8.8:53 and I have Google DNS blocked on my router. Would this be the reason? Any reason why this isn't 1.1.1.1:53 out of curiosity?

**Comment by ameshkov** [comment]
The problem with 1.1.1.1, in general, is that it is unavailable from some locations due to the history of the IP address. For instance, @hmage home ISP blocks it for some unknown reason. The second problem is that you can't change bootstrap DNS via the web admin interface, so we had to choose the most reliable DNS.

We can change the default to `1.1.1.1` or `176.103.130.130` once we expose the bootstrap DNS in the settings UI.
