### ISSUE TITLE
Users Time Online Tracking!

### ISSUE THREAD

**Issue by imranext** [AdguardTeam/AdGuardHome#5348]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

#### What problem are you trying to solve?

Can i track how many hours devices requesting? 
and how many hours they're offline.

example i want to track 192.168.0.103 (My Cousin's phone) how many hours they stay online.

#### Proposed solution
Please add users online/request time tracking feature in parental section.

**Comment by ppfeufer** [comment]
I guess your cousin is using a smartphone? These things are pretty much online all the time even if your cousin is not "actively" using it.

**Comment by imranext** [comment]
> I guess your cousin is using a smartphone? These things are pretty much online all the time even if your cousin is not "actively" using it.

Reply: It was just an example,  laptop , smartphones, tv etc. It'd be nice feature to track how many hours they're online and making request in AdGuard Home.

**Comment by ppfeufer** [comment]
Wasn't meant to dismay your feature request, just as food for thought. Smartphones and Tablets are online all time by design.

Being online and making DNS requests are also 2 different things. Just because a device is not making any DNS requests doesn't mean it's not online. It just means there is nothing running on it that phones home all the time. For example, my Laptop can be online for hours without any DNS request as long as I don't open an app that needs to connect to anything.

A DNS request takes a couple of milliseconds. If there is an app running that does fire a DNS request every x minutes (Mail client for example), how long is the device online according to that metric? X minutes or just a couple of milliseconds?

Again, food for thought.
