### ISSUE TITLE
[REQUEST] Add StevenBlack's hosts collection to the default filters' list

### ISSUE THREAD

**Issue by nezorflame** [AdguardTeam/AdGuardHome#565]
Would be nice to have this included in the default list.

Could even replace the AdAway list with this.

Source: https://github.com/StevenBlack/hosts#list-of-all-hosts-file-variants

**Comment by alexsannikov** [comment]
StevenBlack's hosts collection requires review and adjustment, as there:
1. "127.0.0.1" instead of "0.0.0.0";
2. Multiple records for the same domain name, describing multiple sub-domains (necessary for hosts file);
3. Lists are merged into single group.
I personally made my own repo, change all the raw file as I need and use them separately for each group (ad-malware/fakenews/pron/gampling/social). In such a case I can manage my filter's set independently.
Quick and dirty, but works.

**Comment by hdtvspace** [comment]
"0.0.0.0" ist the fastest solution, because it does not exist. 127.0.0.1 is localhost and here bad and with latency...

**Comment by mHatsune** [comment]
This mentioned in closed issue #1325

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1913
