### ISSUE TITLE
Protection pause timer loses synchronization with the actual pause time

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/AdGuardHome#5759]
First of all thank you very much for this feature! It's really useful and I use it quite often 👍🏼 

I think I found a minor cosmetic bug: When a pause timer is active while the browser or browser tab is inactive (in the background, not visible, etc.), the value of the countdown is not properly updated when returning to the page (Chrome `112.0.5615.121`). So what could happen is that the countdown is still running although from server side it's already completed and protection enabled again.

Without knowing anything of how this is implemented technically, I assume that the countdown is only updated in frontend (JavaScript) code? If so, when a browser (tab) is paused, so are `setTimeout` invocations which could lead to errors with the countdown calculation.

_Originally posted by @svenjacobs in https://github.com/AdguardTeam/AdGuardHome/issues/1333#issuecomment-1516445402_

**Comment by svenjacobs** [comment]
Thanks for creating a ticket.

I believe [this](https://github.com/AdguardTeam/AdGuardHome/blob/757ddb06f8973b8c550f309ca8771a53b68aaa87/client/src/components/ProtectionTimer/index.js#L21-L23) is the problematic code. Chrome is throttling timers of background tabs. This might affect other Chrome-based browsers, too.

Instead of subtracting a second every second what you could do is remember the target time in milliseconds when the timer is over and then calculate the remaining milliseconds. You can still use `setInterval` but it doesn't require to be called every second.

```
TARGET_TIME_MS - CURRENT_TIME_MS = SECONDS_LEFT_MS
```
