### ISSUE TITLE
Not showing dns queries in parental control

### ISSUE THREAD

**Issue by reg8110** [AdguardTeam/AdGuardHome#5820]
### Prerequisites

- [x] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [x] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Windows

### CPU architecture

x86

### Installation

GitHub releases or script from README

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

0.107.29

#### What did you do?
just viewing all dns queries in parental control

#### Expected result
fixing slow result in dns queries in parental control

#### Actual result
see on screenshot below

#### Screenshots (if applicable)
![Screenshot 2023-05-12 214507](https://github.com/AdguardTeam/AdGuardHome/assets/57027620/cdb4a82a-9081-489b-81be-aee800d16778)

#### Additional information
I will fix this to new version of ad guard

**Comment by Khaled0Ebrahim** [comment]
This happens normally because the data you are trying to get is happening in the first bit of datebase
for example if you have 1 query that matches parental control happend two days ago
and then more than 20k queries in any type came after
this request you are trying to get is buried deep in the database so it takes time to reach it
also it happens when you search about something that doesn't exist at all in big number of stored query log
the normal way web UI use to get the data is get 20 by 20 and there is something like a date saying where are the next 20
I am not really sure why they are doing that but this is one of the causes
because for example let's say if i am trying to reach the first query in 1M stored results
doing it 20 by 20 is gonna take forever
get the first 20 see if the thing is in them, not in there get the next 20 and so on till the 1M finishes.
I wish they find a better way
