### ISSUE TITLE
v0.107.30 Clients set upstream DNS query fail

### ISSUE THREAD

**Issue by NV3S** [AdguardTeam/AdGuardHome#5873]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

x86

### Installation

Docker

### Setup

On a router, DHCP is handled by the router

### AdGuard Home version

v0.107.30

#### What did you do?
I deployed ADG(192.168.100.199) on an x86 Debian Docker host and used Watchtower for automatic updates.(wh)

I have set up a group of clients in ADG, using the unique upstream 192.168.100.200:7874(this server both 53/7874 with internal forward ) to handle DNS.

This morning, it was discovered that the devices in this group of clients were unable to perform DNS query. Upon inspection, it appears that the forwarded domain name resolution has failed.（but can manual using the upstream DNS server,its worked OK)
using “nslookup” it reported "Server failed"

ADG query log without these queries
and
with add a new client to the group ,also the same.
try set upstream to  192.168.100.200:53,same

![image](https://github.com/AdguardTeam/AdGuardHome/assets/17755534/c074bb1b-df6f-4b54-b8a6-7eed0c3c31a0)

![image](https://github.com/AdguardTeam/AdGuardHome/assets/17755534/a611e5a8-7186-451b-ba27-4ceb1effc037)

Then I realized through the group email that adg received the push update of 0.107.30 today, so I tried to roll back to 0.107.29 and the problem disappeared.
![image](https://github.com/AdguardTeam/AdGuardHome/assets/17755534/1f5e6843-b7ae-4062-b948-86b81cfaf2fa)

Updated again to version 0.107.30 and the issue reappeared.

![image](https://github.com/AdguardTeam/AdGuardHome/assets/17755534/ace49aba-f558-4e7e-98a6-b713b1af7f4b)

**Comment by NV3S** [comment]
udpate:
with 107.30 ,I set the clients upsteam DNS to another ,problem disappeared.
There is something between each other

**Comment by vhansjee** [comment]
Same issue here, reverting to previous build resolves issues.

**Comment by sz2013** [comment]
Same issue here

**Comment by gnightboy** [comment]
Same issue here

**Comment by binarri** [comment]
Same issue here

**Comment by axllent** [comment]
Wow, this took me about an hour today to debug, but I came to the same exact conclusion and so found this discussion. Things in my network were randomly failing to resolve after the update. My AdGuardHome uses a different internal server (dnsmasq) for upstream queries. I've tried both UDP and TPC, same issue on both.  I've also had to downgrade back to v0.107.29 and things are working perfectly fine again.

**Comment by nwps** [comment]
Same issue here. Using Unbound as an upstream server doesn't work anymore. Once I added 8.8.8.8 as an upstream everything started working again.

**Comment by dfsworld** [comment]
Same here, downgrade solved the issue

**Comment by sdttttt** [comment]
Same issue here

**Comment by yyysuo** [comment]
Same here, downgrade solved the issue.

7874 is the clash dns port, in version v0.108.0-b.34, the upstream test is failed  but works well,in version v0.108.0-b.35, no log generated.

**Comment by Insight16** [comment]
@ameshkov @ainar-g there are problems in the latest release :(

**Comment by ainar-g** [comment]
@NV3S, thanks for the report.  We cannot reproduce this exact bug in our tests: custom upstreams for clients seem to work as usual.

You've mentioned that 192.168.100.200 is running OpenWrt, but what DNS server is it using?  The same release introduced a bug in OpenWrt, see #5872, so if you're running AGH there as well, that could cause the failures.

If not, please [enable verbose logging](https://github.com/adguardteam/adguardhome/wiki/faq#verboselog) and check if there are logs related to the failing queries.  You can also send the verbose logs to us at <devteam@adguard.com>, if you don't want to post it publicly.

**Comment by GonzoTG** [comment]
I use a Ubiquity UDMSE to resolve all LAN addresses and have the entry setup 
[[lh.xxx.com]]]192.168.7.1

When I try to ping and LAN addresses, the Adguard server chokes/times out. Like others reverting back to v0.107.29 makes everything start working again

**Comment by ainar-g** [comment]
We have found a potential bug, and are working on a fix.

**Comment by orosseel** [comment]
> You can use this command to test that your dns server support tcp query : `dig test. @<dns_server> +tcp`

What should be the result of this test? I just get a NXDOMAIN response when I do the test with the LAN IP address of my Asus router, within an acceptable time. Yet ADH blocks when I set this IP address as upstream DNS and with the private reverse DNS servers.

The only option at the moment seems to be not setting the router as upstream DNS and disabling reverse DNS resolvers to resolve hostnames.

**Comment by chesskuo** [comment]
Hello @orosseel ,

NXDOMAIN is also ok, it means your dns server can handle tcp query.
This command is just test your dns server response or not.

In my original case, my dns server is in the remote private network.
I need using port forwarding to get dns query, but I only set udp 53 dst-nat on that time.
And I got a upstream check failed when I click test_upstream button.
When I add the other dst-nat for tcp 53, it works.

I am using PowerDNS as my dns server.

And I also test ASUS router as upstream and reverse dns, but I cannot reproduce your problem, sorry QQ

**Comment by EugeneOne1** [comment]
Hello, @NV3S, and others concerned.  We've pushed the newest `edge` build that should fix this issue.  Could you please try it and report if it now resolves over UDP correctly?  We're also preparing a proper release if this one is fixed.

**Comment by MiKing233** [comment]
Same issue with v0.107.30 on OpenWrt

**Comment by NV3S** [comment]
edge build works fine, you catch it 🎉发自我的 iPhone在 2023年6月8日，22:50，Eugene ***@***.***> 写道：﻿
Hello, @NV3S, and others concerned.  We've pushed the newest edge build that should fix this issue.  Could you please try it and report if it now resolves over UDP correctly?  We're also preparing a proper release if this one is fixed.

**Comment by yyysuo** [comment]
fixed in new version，thanks。

**Comment by candybars2021** [comment]
I think this bug is back on the latest v0.107.48, so I would appreciate if the issue can be reopened or you would direct me otherwise, I willl elaborate:

or my AdGuard Home on my Raspberry Pi, I have added Pi-hole as a private DNS proxy (using its custom.list mappings ), which is installed on different machine in the one on Lan segment shared with other clients. While pi hole responds from any device correctly to DNS requests, and although Adguard home is configured to use it as upstream for log list of domains [/doamin/domain../]192.168.2.43, AdGuard Home isn't showing queries forwarded to Pi-hole in verbose logging, even though Pi-hole logs show receiving them and correct resolution, nor using the pihole responses. Exactly the same as described here. BTW - domain overrites/hosts file in adguard home, were not a solution as they override blocks. 

According to verbose logging, queries for domains included in the upstream pi hole local DNS mapping list (or all queries I set it up as exclusive default upstream) take many seconds to resolve incorrectly, going first through fallback DNS serverst then default ones, unlike domains not set to use pihole, resolving immediately on default in parallel mode. 

For example, when hitting [max.com](https://max.com/), (on the list for pihole 'proxy) AdGuard Home takes 5 seconds to resolve according to cloudflare resolution (not the IP it should resolve to set it pihole), while [google.com](https://google.com/) (or anything not destined to use pi hole as proxy) resolves in 10ms, without hitting fallback etc... It's as if the use of local IP device as upstream is like "disallowed clients/domains" not leaving a trace in the logs....

Would appreciate any advice on resolving this, and thanks in advance.

From settings and logs:

https://dns.quad9.net/dns-query
tls://dns.quad9.net
https://dns.cloudflare.com/dns-query
tls://1dot1dot1dot1.cloudflare-dns.com
And long list of fallbacks. 

Domains excepted in Adguard format[/domain1/domain2/.../max.com]192.168.2.43

Example from verbose logs.- live domain resolved immediately by default upstream, max.com, endless lookup (my fallbacks is a long list for 'lazies" and it goes through them all, e.g:

{"T":"2024-04-15T18:28:26.56996638+03:00","QH":"live.com","QT":"A","QC":"IN","CP":"","Upstream":"https://dns.quad9.net:443/dns-query","Answer":"e2WBgAABAAEAAAAABGxpdmUDY29tAAABAAHADAABAAEAAA26AATMT8XU","IP":"192.168.2.10","Result":{},"Elapsed":30763290}
{"T":"2024-04-15T18:28:38.230704385+03:00","QH":"max.com","QT":"A","QC":"IN","CP":"","Upstream":"194.90.1.5:53","Answer":"1f2BBQABAAAAAAAAA21heANjb20AAAEAAQ==","IP":"192.168.2.50","Result":{},"Elapsed":20143984645}
{"T":"2024-04-15T18:28:38.237450071+03:00","QH":"max.com","QT":"HTTPS","QC":"IN","CP":"","Upstream":"194.90.1.5:53","Answer":"EdCBBQABAAAAAAAAA21heANjb20AAEEAAQ==","IP":"192.168.2.50","Result":{},"Elapsed":20152578860}
{"T":"2024-04-15T18:28:39.044969016+03:00","QH":"max.com","QT":"HTTPS","QC":"IN","CP":"","Upstream":"80.179.52.100:53","Answer":"EdCBgAABAAAAAQAAA21heANjb20AAEEAAcAMAAYAAQAAA4QARQZucy04MjYJYXdzZG5zLTM5A25ldAARYXdzZG5zLWhvc3RtYXN0ZXIGYW1hem9uwBAAAAABAAAcIAAAA4QAEnUAAAFRgA==","IP":"192.168.2.50","Result":{},"Elapsed":20043149615}
{"T":"2024-04-15T18:28:39.12439319+03:00","QH":"max.com","QT":"A","QC":"IN","CP":"","Upstream":"80.179.52.100:53","Answer":"1f2BgAABAAQAAAAAA21heANjb20AAAEAAcAMAAEAAQAACWAABA3iAkLADAABAAEAAAlgAAQN4gJPwAwAAQABAAAJYAAEDeICWsAMAAEAAQAACWAABA3iAhg=","IP":"192.168.2.50","Result":{},"Elapsed":20075261387}
{"T":"2024-04-15T18:28:41.149634677+03:00","QH":"max.com","QT":"A","QC":"IN","CP":"","Upstream":"212.143.212.143:53","Answer":"1f2BBQABAAAAAAAAA21heANjb20AAAEAAQ==","IP":"192.168.2.50","Result":

Still, Pi hole shows receiving this unlogged max.com and subsequent ones right away
:
2024-04-15 18:28:47	A	max.com	                172.17.0.1	  OK (cache)
2024-04-15 18:28:47	A	max.com	                172.17.0.1	 OK (cache)
2024-04-15 18:28:46	A	www.max.com	172.17.0.1	OK (cache)
2024-04-15 18:28:46	A	www.max.com	172.17.0.1	OK (cache)
2024-04-15 18:28:44	A	www.max.com	172.17.0.1	OK (cache)

Therefore, I think it's worth reopening the issue, and I would greatly appreciate help resolving it.
