### ISSUE TITLE
Windows: register service to work under "Local system" user

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#598]
Using "network service" appears to be problematic in some configurations. We'd better simply use "local system".

**Comment by AnthonyBe** [comment]
Just came here to report this exact issue :)

Issue I hit is that "NETWORK SERVICE" doesn't have permissions on file system anywhere so after initial install, on first attempt to start service it fails because it cannot write the update config file.

The exact Windows error log was:
`Couldn't save YAML config: rename C:\install\AdGuardHome\AdGuardHome.yaml.tmp C:\install\AdGuardHome\AdGuardHome.yaml: Access is denied.`

After giving the "NETWORK SERVICE" account Modify permission to the folder the service now starts fine.

I've then noticed that it wouldn't ingest previous logs and so all statistics have reset.
