### ISSUE TITLE
AdGuardHome管理页面安全风险问题

### ISSUE THREAD

**Issue by duckxx** [AdguardTeam/AdGuardHome#6041]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, ARM64

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

107.34以及以往版本

### Action

adguardhome后台管理有个bug。就是不用输入端口号也能找到后台管理页面。并且HTTPS重定向是关闭状态。这会使不怀好意的人在建设在公网的adguardhome不费吹灰之力找到管理页面，并且建议增加防止搜索引擎收录后台管理页面功能。
例如：
访问http://youdomain.com，会拒绝访问。
访问https://youdomain.com，不用加端口号也会自动跳转到管理页面。
访问https://youdomain.com:3000，跳转到管理页面。
访问http://youdomain.com:3000，会拒绝访问。

我的建议是：未打开HTTPS重定向状态下需要加入端口号才能访问。

### Expected result

跳转管理页面

### Actual result

HTTPS重定向关闭状态下。不加端口号访问https直接跳转管理页面。

**Comment by fernvenue** [comment]
**Don't rush to claim that you have found a bug.**

If you believe that opening the AdGuardHome dashboard on the public network is not secure, what you should do is configure your iptables/firewall instead of using non-80/443 ports in the hope that no one will scan other ports. In reality, it is very easy to discover a dashboard that is not on port 80/443. Additionally, you can also control and handle AdGuardHome's DNS services and dashboard in fine-grained manner by using a reverse proxy, as mentioned in the [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy).

Here I can also share a simple solution I have used. I used to access the AdGuardHome dashboard on my server and other service dashboards through WireGuard, using WireGuard itself for authentication and secure transmission. Now, I expose the AdGuardHome dashboard directly on Cloudflare through Cloudflare Zero Trust, and I authenticate using methods such as GitHub. This approach is also very secure and efficient.

Hope this can help you :)

**Comment by duckxx** [comment]
> **不要急于宣称你发现了一个bug。**
> 
> 如果您认为在公共网络上打开AdGuardHome仪表板不安全，那么您应该配置iptables/防火墙，而不是使用非80/443端口，希望没有人会扫描其他端口。实际上，很容易发现不在端口80/443上仪表板。此外，您还可以使用反向代理以细粒度的方式控制和处理AdGuardHome的DNS服务和仪表板，如[文档](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy).
> 
> 这里我还可以分享一个我使用过的简单解决方案。我曾经通过WireGuard访问服务器上的AdGuardHome仪表板和其他服务仪表板，使用WireGuard本身进行身份验证和安全传输。现在，我通过CloudflareZeroTrust直接在Cloudflare上公开AdGuardHome仪表板，并使用GitHub等方法进行身份验证，这种方法也非常安全和高效。
> 
> 希望这能帮助您：)



> **Don't rush to claim that you have found a bug.**
> 
> If you believe that opening the AdGuardHome dashboard on the public network is not secure, what you should do is configure your iptables/firewall instead of using non-80/443 ports in the hope that no one will scan other ports. In reality, it is very easy to discover a dashboard that is not on port 80/443. Additionally, you can also control and handle AdGuardHome's DNS services and dashboard in fine-grained manner by using a reverse proxy, as mentioned in the [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy).
> 
> Here I can also share a simple solution I have used. I used to access the AdGuardHome dashboard on my server and other service dashboards through WireGuard, using WireGuard itself for authentication and secure transmission. Now, I expose the AdGuardHome dashboard directly on Cloudflare through Cloudflare Zero Trust, and I authenticate using methods such as GitHub. This approach is also very secure and efficient.
> 
> Hope this can help you :)

用https://协议访问。你就算把端口号改到65535都可以自动跳转。

**Comment by duckxx** [comment]
> **Don't rush to claim that you have found a bug.**
> 
> If you believe that opening the AdGuardHome dashboard on the public network is not secure, what you should do is configure your iptables/firewall instead of using non-80/443 ports in the hope that no one will scan other ports. In reality, it is very easy to discover a dashboard that is not on port 80/443. Additionally, you can also control and handle AdGuardHome's DNS services and dashboard in fine-grained manner by using a reverse proxy, as mentioned in the [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy).
> 
> Here I can also share a simple solution I have used. I used to access the AdGuardHome dashboard on my server and other service dashboards through WireGuard, using WireGuard itself for authentication and secure transmission. Now, I expose the AdGuardHome dashboard directly on Cloudflare through Cloudflare Zero Trust, and I authenticate using methods such as GitHub. This approach is also very secure and efficient.
> 
> Hope this can help you :)

doh和dot和管理页面都可以通过绑定的ssl证书域名访问，如果访问此域名加个身份验证，是否会影响dot和doh？跟绑定域名进行传输时加个身份验证？
并且CloudflareZeroTrust在中国访问延迟很高，甚至有cloudflare的cdn网站概率性无法访问。

**Comment by fernvenue** [comment]
DoT use different port, so dashboard doesn't give a shit about DoT. As for DoH, I mentioned above that you can control it in a fine-grained manner through a reverse proxy. You can easily add a authentication method you want to the dashboard through the reverse proxy, while ensuring that DoH is not affected at all. You really should read the [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy), seriously.

By the way, as I mentioned above, do not rely on the assumption that nobody will scan other ports. It's soooo easy to discover a dashboard on a different port. Therefore, the issue is not whether DoH will redirect to the dashboard, so your issue is just a pseudo-proposition.

**Comment by duckxx** [comment]
> DoT use different port, so dashboard doesn't give a shit about DoT. As for DoH, I mentioned above that you can control it in a fine-grained manner through a reverse proxy. You can easily add a authentication method you want to the dashboard through the reverse proxy, while ensuring that DoH is not affected at all. You really should read the [documentation](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#reverseproxy), seriously.
> 
> By the way, as I mentioned above, do not rely on the assumption that nobody will scan other ports. It's soooo easy to discover a dashboard on a different port. Therefore, the issue is not whether DoH will redirect to the dashboard, so your issue is just a pseudo-proposition.

但是，不使用反向代理呢？不使用别的第三方办法呢？能否解决使用https://访问，忽略端口号，都可以访问管理页面的问题？

**Comment by fernvenue** [comment]
As @ainar-g said in https://github.com/AdguardTeam/AdGuardHome/issues/6026#issuecomment-1640701316:

> I'm a bit wary about turning AGH into a full-blown Nginx replacement.

And I completely agree with him. Some things should be left to more mature products, and AdGuardHome should focus on what it should do best at the moment. If you don't wanna introduce any other applications or additional services at all, as I mentioned above, you can still choose to implement secure restrictions through configuring iptables/firewall.

**Comment by duckxx** [comment]
> As @ainar-g said in [#6026 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/6026#issuecomment-1640701316):
> 
> > I'm a bit wary about turning AGH into a full-blown Nginx replacement.
> 
> And I completely agree with him. Some things should be left to more mature products, and AdGuardHome should focus on what it should do best at the moment. If you don't wanna introduce any other applications or additional services at all, as I mentioned above, you can still choose to implement secure restrictions through configuring iptables/firewall.

我只是建议就算使用https://访问，也需要输入完整的端口号，才能访问管理页面。
