### ISSUE TITLE
Please update translations of Simplified Chinese.

### ISSUE THREAD

**Issue by Zhijie327** [AdguardTeam/AdGuardHome#611]
I have translated it into Simplified Chinese(简体中文)(zh-CN) yet.
Hope you will use my [translations.](http://adguard.oneskyapp.com/collaboration/project?id=153384)

Thanks.

**Comment by lancelot-moon** [comment]
Your translations need to be approved by the moderator of Simplified Chinese or AG team.

But they maybe need to communicate with each other first since there is a moderator for the language.

**Comment by lancelot-moon** [comment]
In your translation of #48541893, there is a mistake.

English: If you want to enable the built-in DHCP server, make sure that there is no other active DHCP server. Otherwise, it can break the internet for connected devices!

Your translation: 如果你想要启用内置的动态主机设置协议（DHCP）服务器，确保在当前网络中没有活动的动态主机设置协议（DHCP）服务器。否则，该操作可能会破坏在当前网络中已连接的设备！

But you translated the last sentence as "Otherwise, the operation can break the connected devices in the current network!", which is wrong.

It can break the internet, not the connected devices.
I suggest you to check your other translations.

**Comment by Zhijie327** [comment]
Alright, I've got the information! I have corrected it to this. ==>“否则，该操作可能会破坏已连接设备的网络！”
I'll check my translations soon. Thanks a lot!

**Comment by ameshkov** [comment]
@Zhijie327 thank you for your contribution!

@aalpatkina and @IldarKamalov, please take care.

**Comment by LenKiMo** [comment]
Hi, I am one of the currency Simplified Chinese moderators, and had known you had finished the AdGuard Home translation, thanks for your work.

It may takes someday to check your translation and do some editing if needed. I will inform you and developers once the translation checking finished, and update them for the software.

Thanks for your understanding.

**Comment by ameshkov** [comment]
Guys, any update on this? Can we download these new strings?

**Comment by LenKiMo** [comment]
@ameshkov 
Sorry for late. The Simplified Chinese translation for AdGuard Home is ready to update into the program now.
Thanks @Zhijie327 's work.

**Comment by ameshkov** [comment]
Thank you so much!
