### ISSUE TITLE
is there anyway to enable upstream_dns_file in client setting？

### ISSUE THREAD

**Issue by hjchjchjc4352** [AdguardTeam/AdGuardHome#6205]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

i want to edit different upstream_dns with different clients, but i cannot edit upstream_dns_file like in dns setting, including edit adguardhome.yaml. it doesn't work

### Proposed solution

is it possible add upstream_dns_file in client settings

**Comment by schzhn** [comment]
Hello, @hjchjchjc4352. Sorry for the late response.
If you want to specify `upstream_dns_file` in [configuration file](https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file).

1. Stop AdGuardHome.
2. Edit `AdGuardHome.yaml` and save the changes.
3. Start AdGuardHome.

`Otherwise, any changes to the file will be lost because the running program will overwrite them.`

**Comment by ainar-g** [comment]
@schzhn, OP means having separate files for separate clients.  It seems like they reported that again in #6339, so this one should probably be closed.
