### ISSUE TITLE
Do not display non significant Average processing time

### ISSUE THREAD

**Issue by Gandulf78** [AdguardTeam/AdGuardHome#6220]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I have set up two fallback resolvers on Adguard Home (v0.108.0-b.46) and I get average processing time of 28343 ms just for 1 query for each of them. 
Besides this value seems strange to me, it may also include the initial query to the DNS server and not only the query to the fallback?
![IMG_20231013_132649.jpg](https://github.com/AdguardTeam/AdGuardHome/assets/44120190/819d989c-6581-487d-b222-34d353d77281)

### Proposed solution

Do not display non statically significant average processing time.

**Comment by Werewolfke** [comment]
same here, indeed it is a wrong measurement.
(i think) As it is a fall back it does not sent from the instant its needed, but only after x amount of seconds of not getting a responds from the main set dns resolvers. and only after that it sends to the fallback... so if it starts counting from the query request, it indeed will take so long before the dns resolver has processed it... bcs it has not recived it for most of the time too.
(so... no its not the dns resolver thats slow, its just a miss calculation for the fallback dns resolvers.)

But if anyone reads this i would like to add to theis too, that it always shows the slowest processed times first... i would like i to be set automatically or atleast save that i set it so that it show the fastest processing ones first.

**Comment by ainar-g** [comment]
There seem to be two things at play here: the total duration of an upstream query and the duration of the query to the fallback.  Currently, the entire duration of a query, including the failed attempts to reach the main upstreams is counted.

@EugeneOne1, I feel like this needs to be fixed in the DNS proxy module somehow.

**Comment by Werewolfke** [comment]
(update) Was fixed for a few versions but got it back since last 2 or 3 alpha versions. Now I'm on v0.108.0-a.725+5fa11567
And it's back...

**Comment by schzhn** [comment]
The upcoming v0.107.41 release will contain improved average upstream response time calculation.
