### ISSUE TITLE
Option to mark a DNS domain query as "Do not log"

### ISSUE THREAD

**Issue by adrianh-za** [AdguardTeam/AdGuardHome#623]
Would like an option to mark a domain query as "Do not log" so that it does not get added into query log,, and also does not form part of stats. Of course, this would also be a nice feature for privacy to give user opertunity to not log certain domain queries.

Reason being, I have a device from [Efergy](https://efergy.com/engage-online-monitoring/) that monitors my house's power consumption and sends the info to the cloud, but it seems to do a call every 15 to 20 seconds filling up the query log.  Unfortunately, I have no control of the device as it is a block box.

**Comment by GOODTESTA** [comment]
I think this "do not log" is just like a filter in Fiddler.
I've mention about 1 week ago. Maybe you can take a look.
The author says this feature will be implement in next version...
https://github.com/AdguardTeam/AdGuardHome/issues/594

**Comment by adrianh-za** [comment]
Indeed!

I suppose the decision is either to log all DNS queries and then hide what you do not want to see, or mark DNS queries as "private" meaning they never get logged in the first place.  The latter might be a good option for privacy seeing that Adgaurd is basically about privacy, while the first is enhanced filter capabilities of the query log.

Guess we have to wait for @ameshkov weigh in :)

**Comment by ameshkov** [comment]
Well, I prefer the solution proposed in #594. The reason is simple - it's easy to forget about ignored queries, and then miss something really important. Marking this issue as duplicate.

Guys, please vote for feature requests, that's how we understand what to do in the future.

> The latter might be a good option for privacy

Well, it's your own log, and I am not sure if hiding things from yourself has anything to do with privacy :)
