### ISSUE TITLE
Automatically create a systemd service

### ISSUE THREAD

**Issue by talonric332** [AdguardTeam/AdGuardHome#6390]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

When AdGuard is installed it doesn’t automatically start on a system start or reboot

### Proposed solution

When installing, Adguard home should automatically create a systemd  service

### Alternatives considered and additional information

And for existing installation it should be able to check if there’s one already set up. If not it’ll set one up. There should also be a panel in the settings section to adjust the startup setting

**Comment by EugeneOne1** [comment]
@talonric332, hello.  Could you please specify, how have you installed the AdGuard Home?  Since installing it as a service, either via the installation script from [README](https://github.com/AdguardTeam/AdGuardHome/#automated-install-linux-and-mac), or via the `-s install` [command-line option](https://github.com/AdguardTeam/AdGuardHome/wiki/VPS#initial-installation), should actually create a systemd service instance on the systemd-aware Linux systems, enabling the autostart by default.

**Comment by EugeneOne1** [comment]
@talonric332, well, there probably some error occurred while installing as a service.  Could you please repeat the installation process, if needed, and show the command's output?

**Comment by talonric332** [comment]
AdGuard home works fine other then that minor issue
