### ISSUE TITLE
AdGuard Home v0.107.42 not working correctly with keepalived / virtual IP

### ISSUE THREAD

**Issue by nohn** [AdguardTeam/AdGuardHome#6506]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

Other (please mention in the description)

### AdGuard Home version

v0.107.42

### Action

I'm running two AdGuardHome instances in a high availability setup using keepalived and virtual IP. 

### Expected result

AdGuardHome responds to DNS requests on both host and virtual IP.

### Actual result

Up until v0.107.41 this worked fine. After upgrading to v0.107.42, DNS does not respond on the virtual IP, only on the host IP. The web interface works on all IPs. Downgrading to v0.107.41 immediately fixes this issue.

**Comment by Hippo240** [comment]
I have a similar issue, after updating to v0.107.42 (Adguard Home in Ubuntu 20.04 in WSL2 in Win11) adguard appears to only bind to one IP address (not the same one as before the update). Changed my config from bind: 0.0.0.0 to use <primary IP> and 127.0.0.1 and its working again.

**Comment by Magelo** [comment]
I have a similar setup. AdGuardHome running in a Proxmox LXC container for my primary DNS with keepalived and the secondary is running on a raspberry pi. v0.107.42 was not working at all, I lost all DNS resolution. I had downgrade too to v.107.41. Now it's working again.

**Comment by oekomat** [comment]
I have the same problem...no dns forwarding on v0.107.42. Runs in docker on unraid

**Comment by 0berkampf** [comment]
> I have a similar issue, after updating to v0.107.42 (Adguard Home in Ubuntu 20.04 in WSL2 in Win11) adguard appears to only bind to one IP address (not the same one as before the update). Changed my config from bind: 0.0.0.0 to use {primary IP} and 127.0.0.1 and its working again.
> 
> ```
> dns:
>   bind_hosts:
>     - {primary IP}
>     - 127.0.0.1
> ```

Thx, it works for me

**Comment by ardel** [comment]
> I have the same problem. UDP responses do not reach the client. TCP responses are ok. Docker virtual IP in Synology
> 
> ```
> $ dig +short dns.google @192.168.1.12
> ;; connection timed out; no servers could be reached
> ```
> 
> ```
> $ dig +short +tcp dns.google @192.168.1.12
> 8.8.8.8
> 8.8.4.4
> ```

After changing the bind_hosts from 0.0.0.0 to 192.168.1.12 it works fine

**Comment by 0berkampf** [comment]
How do you proceed to downgrade, I was not able to find a detailed procedure?

**Comment by ainar-g** [comment]
@nohn, hello.  A few questions to clarify:

* Have you inspected AdGuard Home's logs?  Do you see any errors there?

* What value of `dns.bind_hosts` are you using?

* Does TCP resolution work?

* You haven't mentioned it in the description, but just to be safe, are you running AdGuard Home in Docker/VM?

**Comment by Zoey2936** [comment]
> We've released a fix to a similar issue in version v0.108.0-a.788+7b5cce51 on the Edge channel. Can anyone affected by this one check?

I've pulled the adguard/adguardhome:edge and now plain DNS over UDP works again for me

**Comment by ainar-g** [comment]
@nohn, releases on the Edge channels are basically daily builds and are not uploaded to GitHub.  We have the links to all release channels on the [*Platforms* page on the Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki/Platforms).

**Comment by ainar-g** [comment]
Great, thanks for testing.  We'll release a fix next week then.

**Comment by x86txt** [comment]
Yep, I'm here too. The latest upgrade broke this for me. Se nice to see such a super-fast response ... and that I'm not the only geek running a keepalived setup with AGH!

**Comment by EugeneOne1** [comment]
For those who have been following this issue, we've just released the [`v0.107.43`](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.43) with the fix.

**Comment by msalmon4** [comment]
issue resolved here as well now with v.0.107.42. Thanks!

**Comment by ItsRaaaw** [comment]
Hi all, I have the same problem of the author of that post.

I have the AdGuard Home MASTER running on a Ubuntu 22.04 CT in Proxmox and the BACKUP one is running on a standalone mini PC with Ubuntu server 22.04.
I'm using keepalived for high availability and adguardhome-sync to sync the two AGH instances. Also, I have OPNsense as FW/router and a TP-Link Omada ecosystem with switches and APs.

Everything is working fine, I can access both webUI, the sync is working and if I try to enter the VIP created with keepalived I get redirected to the webUI of the AGH configured as MASTER.
If in OPNsense I use the real IP of the MASTER AGH in the DHCP server settings everything works and all my devices have access to the internet, but as soon as I change the DNS IP to the virtual one, nothing works anymore and devices have no internet.

Reading the comments I saw that this was a bug of v0.107.42, solved in v0.107.43
I'm actually running the latest version (v0.107.53)
So, do you know if this problem came back? Has anyone had the same problem recently?

I don't consider myself an expert. I'm doing some experiments to improve my home network and actually, this is my first experience with high availability and sync between servers. So feel free to tell me if I'm doing something wrong or if I can improve something.

Hope someone can help.
Thanks

**Comment by lntrpdx** [comment]
hi, 
I am facing the issue in version v0.107.55 as well.
placing all IP addresses in bind_hosts parameter helped temporarily solve the problem.

thanks in advance for your help

**Comment by ItsRaaaw** [comment]
> hi, I am facing the issue in version v0.107.55 as well. placing all IP addresses in bind_hosts parameter helped temporarily solve the problem.
> 
> thanks in advance for your help

Can I ask you which IP addresses do I have to place in bind_hosts?
I can't understand if it's the virtual IP of keepalived on both configuration files or the real IP of each machine in the respective config file.

Thanks
