### ISSUE TITLE
[Feature] Export all blacklist as a hosts file or an adguard-syntax file

### ISSUE THREAD

**Issue by peasoft** [AdguardTeam/AdGuardHome#7047]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to request a feature or enhancement and not ask a question

### The problem

I have to use my phone and PC away from home, so AdGuard Home isn't available there. But I have the permission to modify the machines' /etc/hosts. Can AdGuard export all the blocked domains to a hosts file or an AdGuard-syntax file (for browsers)?

### Proposed solution

Add a new page to export all blocked domains to a file.

And

Provide an api for browsers to update the merged adblock list.

**Comment by ainar-g** [comment]
This is unlikely to be a part of AdGuard Home, at least in the near future.  Such compilation is often just not possible, because hosts syntax doesn't support wildcards and a lot of other features provided by the AdBlock syntax.

Besides, this sounds more like a job for <https://github.com/AdguardTeam/HostlistCompiler> or a similar tool.  Or using an on-device app for DNS filtering that understands AdBlock syntax.
