### ISSUE TITLE
Unable to see clients MAC address

### ISSUE THREAD

**Issue by iptvcld** [AdguardTeam/AdGuardHome#7064]
### Platform

Linux

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Your configuration

I have AGH installed on a Proxmox CT (Debian) - my dhcp server is on pfsense which has multiple vlans. 
AGH1: 10.150.1.50
AGH2: 10.150.1.51
Pfsense: 10.150.1.1
I have clients in 192.168.x.x and 10.10.x.x

### Issue Details

Under persistent clients it only displays the client host name and IP address not the Mac so I am not able to apply some block / allow rules to a single client that has a dhcp address such as a mobile device or kids iPad etc. these device IPs will change and the block/ allow rules will stop working. I don’t thinking setting up reservations via pfsense is too great as I cannot just quickly apply a rule to a device on the fly. 

### Expected Behavior

See the device IP, Mac and hostname

### Actual Behavior

Under persistent clients it only displays the client host name and IP address not the Mac so I am not able to apply some block / allow rules to a single client that has a dhcp address such as a mobile device or kids iPad etc. these device IPs will change and the block/ allow rules will stop working. I don’t thinking setting up reservations via pfsense is too great as I cannot just quickly apply a rule to a device on the fly. I also want to leave my pfsense as the dhcp server

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by iptvcld** [comment]
Having the option to set the device host name would also work but I am not able to set that as the identifier under persisted client. Should I be able to, is this an option because then that host name would always just ping back to that dhcp IP and work.

**Comment by ainar-g** [comment]
I'm not sure I understand what you mean, sorry.  If you mean the kind of data that can be obtained from the DHCP server using rDNS, it has the same issues as the MAC detection.  That is, AGH would be unable to recognize a client from the request info alone.  I think there is a feature request about that somewhere, and you can react with :+1: on that one, if you find it.

**Comment by iptvcld** [comment]
For example the following client was discovered via rDNS
IP: 192.168.2.5
Name: Main-Desktop.example.com

This client has a dynamic IP via pfSense DHCP, without setting this device to a static IP, how can i make sure the rules i set for this client only stay in place and wont be affected if the client gets a new IP (without using AGH DHCP)?

I tried to click on New Client and as the identifier, i tried to use the hostname (Main-Desktop) but this does not work as its still taking the global settings even though i also made sure use global settings is unchecked. If I change that identifier to the IP then it will work, but again this IP will change and I dont want to see ip reservations to a my devices (extra step to maintain)

Is there anthor way to get this working? Perhaps I am doing something wrong?
Thanks again..

**Comment by horstmartinelli** [comment]
Guys, I use an Asus router at home and I have ADH installed on an orange pi mini pc. 

In order for me to identify the client of a web request, do I need to disable the router's DHCP and leave it active only in the ADH? I can't leave both connected because this will cause conflict later?

My desire is to centralize all routing and navigation rules on the ASUS router, and leave the DNS server for queries and filters only in the ADH, allowing client identification in each web request in the ADH.

Is there another way to do this? Thank you

**Comment by iKowex** [comment]
The same problem.
MAC addresses cannot be used, neither if the DHCP server is enabled, nor if it is disabled. MAC addresses can only be seen if DHCP is enabled.
There are 2 servers, Debian12 on which AGH.
1. DHCP is disabled. Addresses are issued by UniFi USG. It is impossible to configure the client filter if only the MAC address is specified in the identifier, AGH simply does not understand it.
2. DHCP is enabled, addresses are issued by ADH. It is impossible to configure the client filter if only the MAC address is specified in the identifier, AGH simply does not understand it.
Yes, you can assign static addresses to everyone, but this is not a solution to the problem, these are crutches.
It turns out that using MAC addresses is generally impossible and there is no point in enabling DHCP in AGH.

Is there any way to fix this?
