### ISSUE TITLE
Stick to POST and GET requests everywhere

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#710]
Otherwise, reverse proxies might be causing issues like this:
https://github.com/AdguardTeam/AdGuardHome/issues/709

@IldarKamalov replace `ensurePUT` with `ensurePOST` in Go code to achieve this.

**Comment by rfgamaral** [comment]
I just want to add that the reverse proxy **was not** the cause for the #709 issue (I'll be opening a new issue about the actual problem). Feel free to still make the change to `POST` instead of `PUT` if you think that makes sense.

**Comment by ameshkov** [comment]
Well, you still had the issue with response code 405, and tbh, you're not the first one with this issue.

**Comment by szolin** [comment]
I think "405" response code can only occur when proxy server has cached the content we sent.  And when a client tries to execute the same request once again, proxy server fails to respond because PUT method isn't supported for static content.  Normally a proxy shouldn't cache a response to PUT request.

Anyway, we should disable caching of our response content to API methods (via Cache-Control).

**Comment by szolin** [comment]
In our code we have this:
`http.Error(w, "This request must be "+method, http.StatusMethodNotAllowed)`
So in case someone issues `GET /control/filtering/set_rules` request, we will reply with 405 error.
