### ISSUE TITLE
unable to set up on ubuntu 19.04

### ISSUE THREAD

**Issue by Techguyprivate** [AdguardTeam/AdGuardHome#722]
### Steps to reproduce

First of all , I am a noob . I don't know anything about computer, softwares or linux. So I beg your pardon from begginning. I am describing step by step of what I did.

1. Download, install or use the live cd, usb, or  live install  option of Ubuntu 19.04 64bit desktop . create a root account. log in as root in terminal.
2. Download AdGuardHome from github release pages for linux 64 bit. Extract it to any folder. Open terminal from there or change the path to adguardhome directory or path. 
3. Run sudo ./AdGuardHome 
4. open 127.0.0.1:3000 or 192.168.1.50:3000 or 0.0.0.0:3000 in your browser .
5 . click start set up
6. in the next page , it shows that port 53 is binding to another service. 
7. I type sudo netstat -ntlup | grep 53 . Found systemd-resolved using port 53 .
8. I use the following commands. 
    
     pkill systemd 
     sudo systemctl stop systemd-resolved
    sudo systemctl disable systemd-resolved

9. Type again in terminal sudo netstat -ntlup | grep 53 to see who is using port 53. No one. 
10. Now, refresh the browser page . Now no warning in red letters that port 53 is binding. Continue further. Set up password. 

11. Now, put 127.0.0.1 or adguardhome address in dns adress in network place .

 12. Adguardhome is not working or resolving dns. 

13. Restart your computer or type sudo systemctl restart NetworkManager in terminal. Adgaurdhome not working, dns not resolving. 

14.  Open terminal , type sudo nano /etc/resolv.conf . Type 127.0.0.1 in place of 127.0.0.53

15 .  Restart your computer or type sudo systemctl restart NetworkManager in terminal. Adgaurdhome not working, dns not resolving. 
### Expected behavior

Adguardhome should work. The dns resolvr put in setting in adguardhome should resolve dns address. 
### Actual behavior

Dns is not getting resolved at all.

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Version of AdGuard Home server:| (e.g. v1.0) 0.94
| How did you setup DNS configuration:| (System/Router/IoT) system
| If it's a router or IoT, please write device model:| (e.g. Raspberry Pi 3 Model B)
| Operating system and version:| (e.g. Ubuntu 18.04.1) Ubuntu 19.04

**Comment by ibksturm** [comment]
hi there

try to help you

a) what does `service AdGuardHome status` say?
b) on  `sudo nano /etc/resolv.conf` nameserver 127.0.0.1 belongs right... because of reasons theres no ability to get different ports for dns other than 53
  <offtopic>a quick, dirty and nasty workaround is to run nginx (+ streaming module) as a load balancer, streaming directly to different dns servers... but that's pain in the ass... so if your a neeby as you write,  let the finger off it... more infos on my git repo </offtopic> 

c) is the AGH only for your local machine or belongs to your full network? think thats a very important information

thanks to more information
