### ISSUE TITLE
Always random I/O timeouts

### ISSUE THREAD

**Issue by GalaxyAlpha** [AdguardTeam/AdGuardHome#7288]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Linux, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.107.52

### Action

![2024-09-25_12-14](https://github.com/user-attachments/assets/f88a422d-e6d3-4146-ba7d-fb3c7282c303)

### Expected result

All domain names should resolve normally

### Actual result

Erros reported above

**Comment by GalaxyAlpha** [comment]
Sorry, there are similar issues that already exist.
#7048 #7065

**Comment by Turab** [comment]
I think it's not the same as the other issues. Because in other issues, it looks like the local IP is timing out and the discussion is all about reverse DNS. While in this issue, the upstream DNS server is timing out and it's not normal. In my case, tls://1.1.1.1 is timing out occasionally and this is a sign of something very wrong; as Cloudflare servers wouldn't timeout this much. I don't have any reverse DNS enabled; so the other issues you linked doesn't apply to this case. My version is v0.107.52 (which is the latest as of now).

`[error] dnsproxy: tls://1.1.1.1:853: response received over tcp: "reading response from tls://1.1.1.1:853: read tcp 172.18.0.6:40216->1.1.1.1:853: i/o timeout"`

**Comment by GalaxyAlpha** [comment]
> I think it's not the same with those issues. Because in other issues, it looks like the local IP is timing out and the discussion is all about reverse DNS. While in this issue, the upstream DNS server is timing out and it's not normal. In my case, tls://1.1.1.1 is timing out occasionally and this is a sign of something very wrong; as Cloudflare servers wouldn't timeout this much. I don't have any reverse DNS enabled; so the other issues you linked doesn't apply to this case. My version is v0.107.52 (which is the latest as of now).
> 
> `[error] dnsproxy: tls://1.1.1.1:853: response received over tcp: "reading response from tls://1.1.1.1:853: read tcp 172.18.0.6:40216->1.1.1.1:853: i/o timeout"`

The reason that may cause the problem is the same; I'm not sure.

**Comment by 32bitx64bit** [comment]
Starting to think this is a ISP issue... I tried while this is happening on my router, to use a app called Portmaster, same damn f**king thing. Encrypted DNS wont work.
Starting to think this is purposeful blocking of secure DNS by a ISP provider... Typical ISP scum.
