### ISSUE TITLE
AdGuardHome Windows edge version [Unknown error: Access is denied. (0x80070005)]

### ISSUE THREAD

**Issue by pekkle-hksar** [AdguardTeam/AdGuardHome#7400]
**NOTE:** For most relevant workaround see the [comment](https://github.com/adguardTeam/adGuardHome/issues/7400#issuecomment-2483341957).

### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

Windows, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

v0.108.0-a.977+1d2026bf

### Action

run "AdGuardHome.exe" in command prompt with admin right

### Expected result

start AdGuardHome properly

### Actual result

Error message shown "Unknown error: Access is denied. (0x80070005)"

### Additional information and/or screenshots

seems latest edge release in Windows is having problem
I fallback the previous version by remove the whole folder, and unzip the previous edge version (Version: 
v0.108.0-a.975+e529d29e), AdGuardHome could start properly

**Comment by bestpika** [comment]
I discovered that the latest edge version modifies the access rights of the entire folder, which is the main cause of this issue.

**Comment by pekkle-hksar** [comment]
Yes, it changed everything in the folder. Even I grant access right again,
it did but work. I need to grant access right, delete the whole folder, and
setup the old version again. Luckily, I have backup the yaml file,
otherwise I will have to setup everything from the very beginning.

在 2024年11月3日週日 13:55，観月唯 ***@***.***> 寫道：

**Comment by bestpika** [comment]
I found this to be significantly related to #7314.

**Comment by EugeneOne1** [comment]
@pekkle-hksar, hello and apologies for the delayed response.  It's definitely related to the issue @bestpika mentioned, and we've already pushed the new edge release, that should avoid this behavior.  Could you please try updating to it?  Note that it indeed changes the permissions of the files in the working directory due to security concerns.  I strongly recommend that you to backup the directory before updating AdGuard Home.

AFAIK, the problem only appears after an update, so I believe it could be fixed by giving full access rights to `AdGuardHome.exe` to the Administrators group (the owner).  In fact, AdGuard Home expects to be [run by an administrator user](https://adguard-dns.io/kb/adguard-home/faq/#manual-update-win) with its rights, so any other scenario is now considered unsafe.

**Comment by bestpika** [comment]
@EugeneOne1 The problem still exists, and there is an issue with the permission design.

1. The SYSTEM should have full permissions.
1. You should not assign permissions to a specific user, but rather to the Administrators group.

**Comment by StoneOfStones** [comment]
When starting service it now says access denied.
Windows 11

**Comment by EugeneOne1** [comment]
@bestpika, how do you install the AdGuard Home service?  Are you using PowerShell running with Administrator privileges?  If so, could you please show the result of the following command:
```PS
([Security.Principal.WindowsPrincipal]
    [Security.Principal.WindowsIdentity]::GetCurrent()
).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
```

If not, could you please provide a detailed description of the process?  Also, which security identifier corresponds to the "SYSTEM"?  If it is listed in this [resource](https://learn.microsoft.com/en-us/windows/win32/secauthz/well-known-sids)?

@StoneOfStones, what permissions are assigned to the file `AdGuardHome.exe`?

**Comment by Eyeborgs** [comment]
После обновления на v0.107.54 у меня была тоже ошибка с доступом и служба не могла работать и мне пришлось самому по стандарту все учетные записи добавлять и в каждом убирать эти галочки которые на фото.

After the update to v0.107.54, I also encountered an access error, and the service could not function. I had to manually add all the accounts according to the standard and uncheck those boxes in each one, as shown in the photo.

![image](https://github.com/user-attachments/assets/2b7141c2-c426-492a-af4c-16573558f079)

**Comment by StoneOfStones** [comment]
> @StoneOfStones, what permissions are assigned to the file `AdGuardHome.exe`?

@EugeneOne1 don't know.

I fix it with:
1. Renamed the folder to `AdGuardHomeOld`.
2. Create new folder and named it `AdGuardHome`, it creates folder with default permissions.
3. Copied contents of the `AdGuardHomeOld` to `AdGuardHome`.
4. Downloaded version `v0.107.53` and extracted exe to `AdGuardHome`.
5. Changed permissions to files/folders of `AdGuardHome` with [this instruction](https://gist.github.com/groovenectar/7f3a4471555d12b722211d5d94664d0b) **except step 6**, if option **7** is not present click **Change permissions**.
6. Started service as usual and it is now fixed.

Don't want to update to a new version just to break it again

**Comment by c15412** [comment]
> If not, could you please provide a detailed description of the process? Also, which security identifier corresponds to the "SYSTEM"? If it is listed in this [resource](https://learn.microsoft.com/en-us/windows/win32/secauthz/well-known-sids)?

Services on a windows system run with SYSTEM permissions, so SYSTEM permissions must be kept

**Comment by pekkle-hksar** [comment]
> @pekkle-hksar, hello and apologies for the delayed response. It's definitely related to the issue @bestpika mentioned, and we've already pushed the new edge release, that should avoid this behavior. Could you please try updating to it? Note that it indeed changes the permissions of the files in the working directory due to security concerns. I strongly recommend that you to backup the directory before updating AdGuard Home.
> 
> AFAIK, the problem only appears after an update, so I believe it could be fixed by giving full access rights to `AdGuardHome.exe` to the Administrators group (the owner). In fact, AdGuard Home expects to be [run by an administrator user](https://adguard-dns.io/kb/adguard-home/faq/#manual-update-win) with its rights, so any other scenario is now considered unsafe.

same as others, it's not working... after updated to the new version, it will be access denied.
it's because of wrong permissions settings of adguardhome.exe and the data folder, too.

**Comment by avatartw** [comment]
>which security identifier corresponds to the "SYSTEM"? If it is listed in this [resource](https://learn.microsoft.com/en-us/windows/win32/secauthz/well-known-sids)?

SECURITY_LOCAL_SYSTEM_RID
String value: S-1-5-18

https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-identifiers
SID: S-1-5-18
Display name:    System (or LocalSystem) 
An identity that's used locally by the operating system and by services that are configured to sign in as LocalSystem. System is a hidden member of Administrators. That is, any process running as System has the SID for the built-in Administrators group in its access token. When a process that's running locally as System accesses network resources, it does so by using the computer's domain identity. Its access token on the remote computer includes the SID for the local computer's domain account plus SIDs for security groups that the computer is a member of, such as Domain Computers and Authenticated Users.

[WELL_KNOWN_SID_TYPE enumeration](https://learn.microsoft.com/en-us/windows/win32/api/Winnt/ne-winnt-well_known_sid_type)
WinLocalSystemSid = 22

**Comment by Micheiii** [comment]
Hi, I am also using Windows Server 2025 as the OS. Initially, I had issues too. Currently, the new version is running. The AdGuardHome folder has been granted permissions for Administrators under Security -> Advanced -> Owner Administrators. The selection was: Owner for everything in the folder. Inheritance was enabled. The folder contains the .exe, .yml, and data folders. The service was set up using nssm.exe.
With nssm install -> select exe

**Comment by 88keyz** [comment]
My temp workaround is to start AdGuardHome with the following batch file instead of starting it as a Windows service.

Change both instances of `C:\Path\to\AdGuardHome` to your AGH install path and then save the batch file to your Start-up folder (`%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup`).

It works by adding a short delay after starting the AdGuardHome executable and then resetting the folder permissions to NTFS defaults.

```
@set @_cmd=1 /*
@echo off
setlocal EnableExtensions
title AdGuardHome

whoami /groups | findstr "S-1-16-12288" >nul && goto :admin
if "%~1"=="RunAsAdmin" goto :error

echo Requesting privileges elevation for managing the AdGuardHome service . . .
cscript /nologo /e:javascript "%~f0" || goto :error
exit /b

:error
echo.
echo Error: Administrator privileges elevation failed,
echo        please manually run this script as administrator.
echo.
goto :end

:admin
pushd "C:\Path\to\AdGuardHome"
AdGuardHome.exe -s start
ping /n 5 /w 10000 localhost >nul
icacls "C:\Path\to\AdGuardHome" /reset /T /C /L
popd
echo.
echo Thank you for using AdGuardHome!

:end
`exit` /b */

// JScript, restart batch script as administrator
var objShell = WScript.CreateObject('Shell.Application');
var ComSpec = WScript.CreateObject('WScript.Shell').ExpandEnvironmentStrings('%ComSpec%');
objShell.ShellExecute(ComSpec, '/c ""' + WScript.ScriptFullName + '" RunAsAdmin"', '', 'runas', 1);

```

**Comment by pekkle-hksar** [comment]
I'm running Windows 11 canary build + AdGuardHome Edge build.
AGH is running as service.
Using command prompt or terminal or power shell with admin right also got
the same access denied error.

在 2024年11月11日週一 22:43，Eugene ***@***.***> 寫道：

**Comment by micceo** [comment]
Temporary solution until AdGuard stops mocking around with permissions.
Create a local user account which is not member of the Administrator group, that is a normal user.
Change the login account for AdGuard server to use this (you get a popup that the account has been granted Login as service)
Change the permission on the folder so the Authenticated Users or Users have **Change** (not Full).

**Comment by ImmortalD** [comment]
Actually, this is generally not done on Windows. This kind of practice is more suitable for Linux. Therefore, is it possible to disable this permission check on Windows?

**Comment by blihlyi** [comment]
win10 LTSC 2019 has same behavior with Windows 11 24H2

**Comment by M0n7y5** [comment]
This issue currently broke internet connections on all windows machines where I installed AGH as service.
Some workaround would be nice.

**Comment by junyan-zhang** [comment]
> > This issue currently broke internet connections on all windows machines where I installed AGH as service. Some workaround would be nice.
> 
> yes.. what a mess.. what i did was to completely remove it and reinstall the latest beta from github. works fine now without having to mess with permissions. you can either backup the yaml config file and restore it or just set it up from scratch which is faster

did you try restart? It will fail to restart I think

**Comment by 1aTa** [comment]
Beta v0.108.0-b.60 doesn't resolve the issue.

You have to change file and folder permissions every time ADH is restarted to workaround the problem.

**Comment by 1aTa** [comment]
I did yeah, but I used a copy of my existing yaml configuration file.

Are you saying there's something in the configuration which is causing the broken permissions to be applied at startup of the latest beta?

**Comment by 1aTa** [comment]
Yep I did that and the beta behaved in exactly the same way as the stable with the broken file and folder permissions applied at startup.

**Comment by pekkle-hksar** [comment]
To avoid the problem, I've back to stable release already.

在 2024年11月18日週一 18:07，M0N7Y5 ***@***.***> 寫道：

**Comment by EugeneOne1** [comment]
Hello again everyone!  We apologise for not releasing a fix for this issue for a long time and are currently working on it.  As far as we can see, the most common problem is the "access denied" error due to insufficient permissions.  The main workaround at the moment is to manually reset the permissions via the file properties.  For each file in the working directory, do the following:
* Go to _"Properties"_ → _"Security"_ → _"Advanced"_.
* If the file is owned by the _"Administrator"_ account, give this account _"Full Access"_.  If the file is owned by another account, e.g. _"SYSTEM"_, give it _"Full access"_.
Note that AdGuard Home uses the permissions of the configuration file to determine whether they should be changed, so if the permissions have changed after startup, it's possible that this particular version of Windows (the Services subsystem) expects a different owner for the file, which should also be changed.

We'd really appreciate any detailed feedback on this workaround.  If it works or if the error has changed.

**Comment by junyan-zhang** [comment]
> Hello again everyone! We apologise for not releasing a fix for this issue for a long time and are currently working on it. As far as we can see, the most common problem is the "access denied" error due to insufficient permissions. The main workaround at the moment is to manually reset the permissions via the file properties. For each file in the working directory, do the following:
> 
> * Go to _"Properties"_ → _"Security"_ → _"Advanced"_.
> * If the file is owned by the _"Administrator"_ account, give this account _"Full Access"_.  If the file is owned by another account, e.g. _"SYSTEM"_, give it _"Full access"_.
>   Note that AdGuard Home uses the permissions of the configuration file to determine whether they should be changed, so if the permissions have changed after startup, it's possible that this particular version of Windows (the Services subsystem) expects a different owner for the file, which should also be changed.
> 
> We'd really appreciate any detailed feedback on this workaround. If it works or if the error has changed.

Is this mean, until further fix been issued, it is not recommended to run AdGuard Home as a "Windows Service"?

**Comment by EugeneOne1** [comment]
@junyan-zhang, well, it's indeed true, because the Service subsystem seems to use some opaque permissions logic, as opposed to straightforward PowerShell with Administrator rights.

**Comment by okastl** [comment]
> A stable urgent update is needed that disables permission changes in the Windows system as it was before.

I agree. I don't like the idea of an application changing folder permissions and ownership without my consent.

**Comment by xiao-mantou** [comment]
I am on the stable release, and I got the same issue.

**Comment by EugeneOne1** [comment]
Hello again everyone.  We're still working on a better solution to the original security issue, but we've just released the **edge** build which adds a command line option to disable the whole permission checking feature.  Here is how to use it:
 * Make a backup of the working directory.
 * If you already have AdGuard Home installed as a service, it should be uninstalled:
    ```ps
    .\AdGuardHome -s uninstall
    ```
 * Then update the binary to the latest edge.  If you're using the edge channel, you can use the command line update:
    ```ps
    .\AdGuardHome --update
    ```
 * Re-install AdGuard Home as a service with the `--no-permcheck' option specified:
    ```ps
    .\AdGuardHome -s install --no-permcheck
    ```

Any feedback is still welcome.  Note that it's not yet in beta channel.  We'll release a fixed version as soon as possible.

**Comment by 1aTa** [comment]
Also agree with this.

**Comment by pekkle-hksar** [comment]
Agree. It's to minimize the problem to current users using the standard
command to install service. New feature that may caused problem would be
better an opt-in feature rather than turn on by default.

在 2024年11月23日週六 02:47，Roman ***@***.***> 寫道：

**Comment by xiao-mantou** [comment]
> > Hello again everyone! We apologise for not releasing a fix for this issue for a long time and are currently working on it. As far as we can see, the most common problem is the "access denied" error due to insufficient permissions. The main workaround at the moment is to manually reset the permissions via the file properties. For each file in the working directory, do the following:
> > 
> > * Go to _"Properties"_ → _"Security"_ → _"Advanced"_.
> > * If the file is owned by the _"Administrator"_ account, give this account _"Full Access"_.  If the file is owned by another account, e.g. _"SYSTEM"_, give it _"Full access"_.
> >   Note that AdGuard Home uses the permissions of the configuration file to determine whether they should be changed, so if the permissions have changed after startup, it's possible that this particular version of Windows (the Services subsystem) expects a different owner for the file, which should also be changed.
> > 
> > We'd really appreciate any detailed feedback on this workaround. If it works or if the error has changed.
> 
> Is this mean, until further fix been issued, it is not recommended to run AdGuard Home as a "Windows Service"?

Wow, in stable release, it's happening even when it's not running as service. I just tried the edge biuld, seems fine with ``--no-permcheck``.

**Comment by xiao-mantou** [comment]
> How does one download the edge build? I only see the beta and normal in release/tags?

[Here](https://github.com/AdguardTeam/AdGuardHome/wiki/Platforms)

**Comment by Arthur-Kenichi-Condino** [comment]
So issues #7439 and #7454 are duplicates of this Issue; I had to fall back to version v0.107.53 from v0.107.54. AdGuard Home is already installed as a service, and updating it manually by replacing the executable and then running the service resulted in AdGuard blocking itself from running because it set only Write permissions to a non-privileged unknown user to its folders (not even myself, as an Admin User, could open the folders because it had permissions which made no actual sense: the yaml file and the data folder had **only** Write permission, not even Read or Traverse files and folders); I won't update to another stable version until this is fixed because whenever I do that, I have to set AdGuard from scratch. 

Setting permissions of full control may allow AdGuard to run **once**, because it'll set its permissions wrong again in the next run. Also, setting all permissions to the right ones (suggested here in this Issue), but leaving the folders "data" and the yaml file with the Write **only permissions** AdGuard set automatically when it runs (not even read or traverse files and folders), will allow AdGuard to run on startup normally **but I believe it'll not be able to read its settings consistently**, so that may be the cause of the DNS filtering not working in my other post on Issue #7439. If the folder has all the permissions with Full Control (even data and yamls file), AdGuard will run normally **once** and then break again.

Even the Owner of the folder in the security permissions is Unknown and not Administrator or an Admin User (me). So AdGuard won't be able to be run with PowerShell or cmd.

By the way, how would I update to a newer version (but never again v0.107.54) and then **not** let AdGuard change its permissions? What I understood is that if you install it from scratch as a service, you can do _-s install --no-permcheck_, but what should I do as an end user, to update it, if it's already installed as a service: after I just replace the executable file? Because I don't need to change permissions: I know it's safer to restrict permissions in important folders, but I'm already an Admin User in my computer, so this changes nothing in the question of security, because I think it's redundant, in Windows: suppose a bad actor invades my computer: it'll be able to do anything it wants, even to AdGuard, because I'm also an Admin User; I know it's safer to create an account without Admin Privileges and leave the Administrator account with its privileges only, but here where I live we don't have so much software security and safety education, so many stores already sell the computer with a new user with administrative privileges (access to root) and with some bloatware sometimes.

I want to restrict my current user and enable Windows's built-in Administrator account with UAC messages with password required to make system changes, but I'm a little bit buzy/lazy to do that right now, it's too much to change.

So for most Windows end users, like myself, who bought a computer and started using it the way it came from the store, changing permissions may be also redundant. Because if I'm infected with malware, the malware will grant itself privileges and access AdGuard with my own credentials (as I'd do manually).

P.S.: I'm **not** a professional IT, a security technician or anything, I'm just explaining my suppositions and the experience I had installing the new AdGuard stable version.

Also, I'm using _Windows 11 Pro 22631.4391 Windows Feature Experience Pack 1000.22700.1047.0_ and _avast!_

I installed AdGuard with PowerShell as service with _.\AdGuardHome -s install_

**Comment by EugeneOne1** [comment]
Hello, @Arthur-Kenichi-Condino, thank you for a very thorough response!  The issues mentioned are really duplicates of this one and all have the same origin, which is the inability to access the files with invalid permissions.  We’re already testing the new beta, which should be much more accurate in terms of access rights on Windows.

 >  Even the Owner of the folder in the security permissions is Unknown and not Administrator or an Admin User (me). So AdGuard won’t be able to be run with PowerShell or cmd.

Who owns AdGuard Home’s working directory and its parent directory?  The latest release shouldn’t affect the owners of files and directories, it just sets the permissions for them, assuming that the working directory was originally owned by the Administrators account.

 >  What I understood is that if you install it from scratch as a service, you can do -s install --no-permcheck, but what should I do as an end user, to update it, if it’s already installed as a service: after I just replace the executable file?

The service uninstall command shouldn’t affect permissions, so it can be run either before or after the executable is replaced.  Could you please try the following:
 *  Change the permissions of the working directory to give the “Full control” to the Administrators account and make the Administrators own it.  Do that for each file within the working directory.
 *  Stop the service, if not already done:
    ```ps1
    .\AdGuardHome.exe -s stop
    ```
 *  Uninstall the service:
    ```ps1
    .\AdGuardHome.exe -s uninstall
    ```
 *  Replace the executable with the [latest edge](https://github.com/AdguardTeam/AdGuardHome/wiki/Platforms#packaged-releases), since the option is currently only available on the `edge` channel.
 *  Install the service again with `--no-permcheck`:
    ```ps1
    .\AdGuardHome.exe -s install --no-permcheck
    ```
This should fix skip the unwanted permissions manipulations.

 >  I’m just explaining my suppositions and the experience I had installing the new AdGuard stable version as an end user, so please correct me when I said something wrong.

You’re always welcome to share your experiences with us to help us develop AdGuard Home and other products.  However, as a security-aware, server-based software, AdGuard Home strives to avoid all possible vulnerabilities, one of which is insecure access rights (#7314).

**Comment by sausje** [comment]
So I followed the instructions given in this topic to update and get it working again, but somehow my filterlists have 0 entries? Even after forcing an update to them. I can see the files in explorer and they have the right data in them. So I guess this way of "forcing" adguard to run renders it unable to read the filter files??

**Comment by M0n7y5** [comment]
> So I followed the instructions given in this topic to update and get it working again, but somehow my filterlists have 0 entries? Even after forcing an update to them. I can see the files in explorer and they have the right data in them. So I guess this way of "forcing" adguard to run renders it unable to read the filter files??

I suggest you to nuke your current adg installation and reinstall it from scratch.

**Comment by sausje** [comment]
> > So I followed the instructions given in this topic to update and get it working again, but somehow my filterlists have 0 entries? Even after forcing an update to them. I can see the files in explorer and they have the right data in them. So I guess this way of "forcing" adguard to run renders it unable to read the filter files??
> 
> I suggest you to nuke your current adg installation and reinstall it from scratch.

No need, last update fixed this.

**Comment by canronglan** [comment]
这个权限控制完全没必要，都已经是home了，还要担心什么权限问题？多此一举！

**Comment by EugeneOne1** [comment]
Hello everyone!  We've pushed the edge build that contains a more proper implementation of the access rights handling.  For now, AdGuard Home will only check the working directory permissions and migrate them if necessary.  The expected permissions (which won't be migrated) for now are the following:

 *  _"Full Control"_ for the _Administrators_ account;
 *  any deny access rights for any account;
 *  no access rights for any other account;

Note that any file within the working directory is expected to inherit its permissions and therefore be considered protected.

It works fine on our test machines, but we'd really appreciate it if someone would check it before we release a beta and eventually a stable version.  If you want to help us test this feature, and you previously installed the service with the `--no-permcheck' option, it will still take effect, so you'll need to reinstall the service without it.  Please make a full backup of the working directory before upgrading.

For those who don't want to use this feature, the `--no-permcheck' option will also be released in stable and beta.

**Comment by 1aTa** [comment]
> Hello everyone! We've pushed the edge build that contains a more proper implementation of the access rights handling. For now, AdGuard Home will only check the working directory permissions and migrate them if necessary. The expected permissions (which won't be migrated) for now are the following:

This seems to be working well from my testing so far. Permissions are set correctly, Windows states that I don't have access to the working directly but I can click continue to get access as an admin, configuration is editable from the webUI, no issues on restart of the service.

**Comment by EugeneOne1** [comment]
For anyone interested, the fix is available on the [beta channel](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.108.0-b.61).

**Comment by EugeneOne1** [comment]
We're closing this issue for now and preparing a stable release, thanks again to everyone who tested the fix.

**Comment by bestpika** [comment]
@EugeneOne1 Can the `--no-permcheck` option of the edge version be used after installation as well?

**Comment by EugeneOne1** [comment]
@bestpika, sure.  It's also available in the latest beta.

**Comment by Zerorigin** [comment]
> После обновления на v0.107.54 у меня была тоже ошибка с доступом и служба не могла работать и мне пришлось самому по стандарту все учетные записи добавлять и в каждом убирать эти галочки которые на фото.
> 
> After the update to v0.107.54, I also encountered an access error, and the service could not function. I had to manually add all the accounts according to the standard and uncheck those boxes in each one, as shown in the photo.
> 
> ![image](https://private-user-images.githubusercontent.com/46345396/384471095-2b7141c2-c426-492a-af4c-16573558f079.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDYyNDgsIm5iZiI6MTczMzcwNTk0OCwicGF0aCI6Ii80NjM0NTM5Ni8zODQ0NzEwOTUtMmI3MTQxYzItYzQyNi00OTJhLWFmNGMtMTY1NzM1NThmMDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDAwNTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZjcxMmM2YzRmNGVjNDVlNWIxZDI1ZmVkYWVlMzAyMmM0Yjk4MjIwNTBhMTk5ZTgyOWJiZTY1ZTM2MjczOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P3slOoQ0PbrPueOPJhgrh8nS45v7kcdrzO96z5c26Kg)

It works for me. 
3Q~ (Thank you).

**Comment by candrapersada** [comment]
why is there no information about `--no-permcheck` for windows at https://adguard-dns.io/kb/adguard-home/getting-started/#installation or https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started ?
