### ISSUE TITLE
Increase size of query log

### ISSUE THREAD

**Issue by adrianh-za** [AdguardTeam/AdGuardHome#776]
Increase the number of DNS records logged.  I am around 20000 logs per day and normally can only go back around 6 hours or so.

If possible make it configurable in YAML config file.

**Comment by ArchiveBase** [comment]
Please let us store unlimited logs for go back days/months since installation. (I aware it's possible download log file each day for example but it's annoying thing to do)
 _(someway if it considered privacy-risk then make it customizable for preferred users to configure it through web interface or YAML config)_

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/750

**Comment by ameshkov** [comment]
Add "Query Log" settings section:

* checkbox "Enabled"
* "Query logs retention": (the same periods as with statistics)
* "Clear query logs" button
