### ISSUE TITLE
[Feature request] Set different DNS for individual clients

### ISSUE THREAD

**Issue by Vansinnet** [AdguardTeam/AdGuardHome#821]
Hi!

I have a request for a new feature. I'd like to be able to individually set a different DNS for a client than the globally set one. One of the reasons I'd like to do this is because the AdGuard parental control/secure browsing modules are so slow (I get over 1000 ms increased average proccessing time when I enable them) that I want to use a DNS with built in family protection for the devices my childen use. At the same time I don't want family filter for all devices, so using for instance AdGuard family DNS globally isn't an option. 

Maybe an option like this:

![Untitled](https://user-images.githubusercontent.com/46295914/59148650-f4551200-8a0b-11e9-901a-ebb863c9e957.png)

**Comment by Eyeborgs** [comment]
![Upstream DNS-серверы для клиента](https://user-images.githubusercontent.com/46345396/59149041-0db08b00-8a19-11e9-9846-abfd057a9590.png)
I think that would be better.

**Comment by Vansinnet** [comment]
Yes, you got my idea perfectly right!

Is my idea doable?

**Comment by ameshkov** [comment]
Yeah, this is doable, but not too easy. Let's see how many upvotes it gets.

**Comment by alexsannikov** [comment]
I'd like to expand the "User Profiles" feature and have the possibility to configure EVERYTHING for each user. It may include EVERY option available in global settings, as well as chance to choose which filter lists to apply to this user, which upstream DNS to use, and any specific settings which must be applied to this particular profile.
Unfortunately, now "User Profiles" feature works differently I expected. I wanted to use it to disable some access for children devices, applying some custom filters to the kid's profile (for example, not to give access to any social networks), but leave access to other users globally. Currently, I cannot choose/allow the specific filter to specific user (maybe I use it wrongly?).
Again: User's Profile for specific device must have as much settings as possible, fully replicating the Global settings featureset plus Filters plus maybe some specific settings applicable to this profile only (for example, don't log this user's activities). The list of settings must be extendable for future expansion.
Just my two cents.
Thanks.

**Comment by iophobia** [comment]
+1 for this idea since my iRobot and TPlink switches apparently don't play along with AGH. I don't know where the culprit is though because the problem persists even when filtering is exempted for these clients.

**Comment by ArchiveBase** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/962

**Comment by alexj-m** [comment]
+1

I'd really like this feature. My main usecase being to allow my TV's etc to use a SmartDNS service (as their upstream DNS) whilst the rest of my devices use a different upstream DNS.

**Comment by candybars2021** [comment]
I ran into this post. Did anything ever get planned according to this great feedback? It's a totally necessary feature, since the whole point of identifying specific clients, turns from passive monitoring, to active filtering and DNS resolving, profiles and all. For me, the initial idea of this post, different DNS per client (more relevant than per domain in my opinion) is vital. In the example of DNS proxy and bypassing geo restrictions, there really are no mass market solutions that enable both filtering (say of annoying tv ads), and DNS resolution that will hide your original location. DNS proxy services don't filter, and the main alternative to resolving DNS "correctly" on the remote location that tracks your origin (privacy issue), the other main option is 3rd party VPN, where even if it is not blocked, the use of vpn per se is tracked (eg google ignores IP you obtain from VPN tunnel and still tracks your original non vpn IP for months without consent). Moreover, 3rd party VPN does not allow you to properly filter anything (certainly not for a network wide solution when you are using a config file with your router/firewall), so you have to decide between filtering, or geoanoymity. with enabling DNS resolution per client (much more relevant than per domain, as the resolution on the "remote end" differs per client, vs per domain locally where whatever DNS server you use they will resolve similarly. Anyway, I hope this is added soon. It's possible with pinhole but I hate that platform and its the biggest "blanc spot" in my opinion for Adguard Home. Sad to see this discussion was closed and not developed into the next gen Adguard Home...

**Comment by ctml91** [comment]
+1 for this, I'm in need of setting one specific client directly to the ISPs modem for DNS because Adguard running on my pi4 is causing issues for it.

If unsupported with AdguardHome are there any other DHCP/DNS services that offer this?

**Comment by iophobia** [comment]
The since-then-implemented "custom DNS upstream per client" should already suit your requests. Check back in the client settings.

**Comment by ctml91** [comment]
> The since-then-implemented "custom DNS upstream per client" should already suit your requests. Check back in the client settings.

It's better than nothing but I'm looking for custom primary DNS per client rather than upstream. I'd like certain clients to go direct to my modem rather than to AdGuard first. 

For whatever reason a specific device (IPTV Box) from my service provider does NOT work properly when going through AGH for DNS, there are intermittent DNS request failures affecting the service. Not adblocking related, as it still occurs when it's complete disabled. 

Being able to configure the primary DNS on a per client basis in DHCP would resolve the issue.

**Comment by smithbill17** [comment]
Is this feature not implemented yet?

I thought I would be able to setup a DHCP Static IP Lease & specify what IP to handout as it's DNS server, but this option isn't there??

PiHole v6 can do this using manually entered dnsmasq tags, is there no option for this on AGH?
