### ISSUE TITLE
Use whois for public client IP addresses

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#861]
This might be useful for the VPS setup case to see additional details about the IP address by querying the whois database.

We can get the organization the IP address belongs to, and the country code as well. 

Relevant library (maybe there are more):
https://github.com/domainr/whois

1. For an IP address, we can get `org-name`, `city`, `country`.
2. We should query and print this information for every client IP (even if we got some info from arp/rdns).
3. This should only be done for public IP addresses only.

**Comment by ArchiveBase** [comment]
Even bit irrelevant, I prefer comment here rather than else

> https://www.robtex.com/as/AS16509.html (scroll down far for AS details)
Seems good for see AS details and able search hostname/ipnumber/route include whois however most details display for logged users)
https://www.robtex.com/ip-lookup/176.103.130.130 (include whois)

> https://whotracks.me already use for AG. Panic! 😭😉

**Glasswire recently launched host info page (beta) (It shows most necessary things include basic details, attributes, geo, http, ssl, whois)** 
It's really nice for common person as my opinion and begin search through their desktop software logged IPs/hostnames

https://www.glasswire.com/host/172.217.10.78 
(ofcourse better than https://domainr.com)

Then the main idea of this to take adguard team's valuable spare time ;) Combine that all and host a page will make everyone's choice and wanna say, It's Cool !
( just similar https://reports.adguard.com/en/google.com/report.html as adguard subdomain)

**Comment by szolin** [comment]
875905ce8a7b831375b60998ed07079bede029d9

**Comment by ameshkov** [comment]
A couple more things to improve:

1. Add icons near location and orgname/netname: https://uploads.adguard.com/up04_7hxmx_AdGuard_Home.pnghttps://uploads.adguard.com/up04_7hxmx_AdGuard_Home.png

Location: https://uploads.adguard.com/up04_lkgym_Location_Icons_for_iOS.png
Smth like this for orgname/netname: https://uploads.adguard.com/up04_q57l7_Wi_fi_Icons_for_iOS.png

2. Change the "requests count" default width to about 25%
3. Parse more fields from the whois output in the case if org-name is not present (descr, netname)

**Comment by ameshkov** [comment]
Another issue:
1. There's a "runtime client" in the list with whois info
2. Then when I add a new client manually, this client's info is not transferred
