### ISSUE TITLE
Please join the video advertising function! 

### ISSUE THREAD

**Issue by shenzt68** [AdguardTeam/AdGuardHome#938]
Please join the video advertising function! In China, the time of video advertisement is too long to bear!

**Comment by ameshkov** [comment]
Most likely, we just don't have Chinese ad servers in the AdGuard SDN filter. Is there any popular Chinese ad  hosts list?

**Comment by lancelot-moon** [comment]
For your reference:

1. Yhosts: (last updated 2 days ago)
https://github.com/vokins/yhosts
https://raw.githubusercontent.com/vokins/yhosts/master/hosts.txt

But the author said he subjectively made the list on his GitHub.
It's because he'll also block domains which he dislikes.

Discuss with AdamWr before...
https://github.com/AdguardTeam/AdguardFilters/issues/18813#issuecomment-469004724
https://github.com/AdguardTeam/AdguardFilters/issues/18813#issuecomment-469043735

ex: `||t7z.cupid.iqiyi.com^` is useful for its mobile page and apps.
But it causes anti-adblock warning for its desktop page without AdGuard filters (AdamWr's rules can skip the ad video and anti-adblock warning).
So we only added `||t7z.cupid.iqiyi.com^` in AdGuard Mobile Ads filter and SDN filter.
Generally, we don't enable AdGuard Mobile Ads filter and SDN filter for desktop page.

2. ad-wars: (last updated 2 months ago)
https://github.com/jdlingyu/ad-wars/
https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts

However, I don't know if AdGuard team have time to check those domains in the 2 lists.

**Comment by lifansama** [comment]
> For your reference:
> 
> 1. Yhosts: (last updated 2 days ago)
>    https://github.com/vokins/yhosts
>    https://raw.githubusercontent.com/vokins/yhosts/master/hosts.txt
> 
> But the author said he subjectively made the list on his GitHub.
> It's because he'll also block domains which he dislikes.
> 
> Discuss with AdamWr before...
> [AdguardTeam/AdguardFilters#18813 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/18813#issuecomment-469004724)
> 
> ex: `||t7z.cupid.iqiyi.com^` is useful for its mobile page and apps.
> But it causes anti-adblock warning for its desktop page without AdGuard filters (AdamWr's rules can skip the ad video and anti-adblock warning).
> So we only added `||t7z.cupid.iqiyi.com^` in AdGuard Mobile Ads filter and SDN filter.
> Generally, we don't enable AdGuard Mobile Ads filter and SDN filter for desktop page.
> 
> 1. ad-wars: (last updated 2 months ago)
>    https://github.com/jdlingyu/ad-wars/
>    https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
> 
> However, I don't know if AdGuard team have time to check those domains in the 2 lists.

Maybe you can use [neohosts](https://hosts.nfz.moe/) instead of yhosts. It's more righteous.

**Comment by lancelot-moon** [comment]
Neohosts doesn't block iqiyi ads and trackers.
